### ISSUE TITLE
Mupen64Plus has own Screen Resolution on 1.15.0

### ISSUE THREAD

**Issue by TradeDraft** [mupen64plus/mupen64plus-core#1000]
I put Show Refresh Rate Automatically to Off and works for all Cores except for Mupen64Plus Core.

Only did it after Updating to 1.15.0

Found it only does it using Glide64 Video Plugin

How can I fix this or have to wait for a Update with it Fixed?

**Comment by richard42** [comment]
are you using retroarch? if so, you'll need to file a bug with them.

**Comment by TradeDraft** [comment]
Yes I am but I asked here as Mupen64plus was the Only Core with that Issue

**Comment by richard42** [comment]
No, they have a different code base and I don't even know what this option "Show Refresh Rate Automatically" is. Each mupen64plus video plugin has it's own options and capabilities, so if this feature only works with Glide64 then that's probably because the other video plugins don't implement it.

**Comment by TradeDraft** [comment]
Okay Got Ya.

I figured the issue out.

Was the Config File as when I Moved the File and Allowed a New One to be Generated it worked fine after that
