### ISSUE TITLE
How To Correctly Install Mupen64Plus in Ubuntu

### ISSUE THREAD

**Issue by rafaelimaf** [mupen64plus/mupen64plus-core#1003]
I downloaded the tar.gz file from the package assets. After that i'v extracted the files, then i runned the `sudo sh install.sh` command. The terminal logged me this exit:

```cli
Installing Mupen64Plus Binary Bundle to /usr/local
install: creating directory '/usr/local/share/mupen64plus'
install: creating directory '/usr/local/share/mupen64plus/doc'
install: creating directory '/usr/local/share/man'
install: creating directory '/usr/local/share/man/man6'
install: creating directory '/usr/local/share/applications'
install: creating directory '/usr/local/lib/mupen64plus'
Installation successful.
```

But then when i run `mupen64plus` in the terminal, the only thing i get is:

```cli
 __  __                         __   _  _   ____  _             
|  \/  |_   _ _ __   ___ _ __  / /_ | || | |  _ \| |_   _ ___ 
| |\/| | | | | '_ \ / _ \ '_ \| '_ \| || |_| |_) | | | | / __|  
| |  | | |_| | |_) |  __/ | | | (_) |__   _|  __/| | |_| \__ \  
|_|  |_|\__,_| .__/ \___|_| |_|\___/   |_| |_|   |_|\__,_|___/  
             |_|         https://mupen64plus.org/               
Mupen64Plus Console User-Interface Version 2.5.9

UI-Console: attached to core library 'Mupen64Plus Core' version 2.5.9
UI-Console:             Includes support for Dynamic Recompiler.
Core Warning: No version number in 'Core' config section. Setting defaults.
Core Warning: No version number in 'CoreEvents' config section. Setting defaults.
Core: Using full mem base
UI-Console Error: no ROM filepath given
```

There is no user interface, and there isn't  any application icon or something in my Ubuntu applications. If i try to search the packages in the apt, i can see all the packages but not the core one. And even the other packages as `mupen64plus-video-rice` `mupen64plus-ui-console` aren't installed from the apt.

I'm currently using Ubuntu 23.04. If someone could help me, i would be very glad.

**Comment by Jj0YzL5nvJ** [comment]
Using [RMG](https://github.com/Rosalie241/RMG/releases/latest) is highly recommended...

**Comment by richard42** [comment]
that looks correct; you are using the UI-Console application, which is command-line only. Just give it a single argument which is the path to the ROM file.  Or if you want to use a GUI you can get Rosalie's front-end or m64py.
