### ISSUE TITLE
Remove SDL1.2 support for Windows in favor of SDL2

### ISSUE THREAD

**Issue by Narann** [mupen64plus/mupen64plus-core#101]
This ticket is to engage a discussion started on the IRC about removing SDL1.2 dependency for Windows bins in favor of SDL2.

So:
- Remove SDL1.2 from win32dep repo.
- Put SDL2 in win32dep repo.
- Clean VS projects (the hardest part).

Pros? Cons?

**Comment by rlabrecque** [comment]
Implementing, let me know if there's any cons to it.

**Comment by conchurnavid** [comment]
I don't understand the question. I thought the windows builds are already SDL2 and they are not using the win32dep repos.

Or is this question about the people which want to make their own builds using VS2013?

**Comment by rlabrecque** [comment]
This is specifically for VS2013.

**Comment by Narann** [comment]
@conchurnavid If Windows doesn't use 1.2 anymore, do we need [this](https://github.com/mupen64plus/mupen64plus-win32-deps/tree/master/SDL-1.2.14)?

**Comment by rlabrecque** [comment]
Mingw/mxe builds don't need that, but the VS2013 projects do use that currently. Replacing that with SDL2 and updating the project files ended up being very easy with no visible side effects so far.

**Comment by richard42** [comment]
@Narann, he would replace that SDL 1.2 tree in the win32deps module with an SDL2 tree including the libs and headers.  I'm fine with the move to SDL2 for the MSVC Win32 build, though I might wait to merge it until after the upcoming 2.5 release, just to avoid introducing regression.

**Comment by strycore** [comment]
Why would that be Windows specific? The Linux builds would greatly benefit from a SDL 2 upgrade, especially with everything regarding fullscreen handling and resolution switching.

**Comment by rlabrecque** [comment]
The Linux builds already use SDL 2 by default.

**Comment by strycore** [comment]
Ah, thanks for the info, since I was having fullscreen issues I assumed it used SDL 1.2. 
I'll investigate a bit more and leave and issue in the rice video plugin repo.

**Comment by richard42** [comment]
Done.
