### ISSUE TITLE
Control Stick in Pokemon Snap not working

### ISSUE THREAD

**Issue by Papermanzero** [mupen64plus/mupen64plus-core#1037]
https://github.com/libretro/mupen64plus-libretro-nx/issues/471

Already created an issue for but in reddit people say it is an upstream topic.

the control stick is not working when you actually start the game in pokemon snap. the focus is always in the centre. you cannot move the camera. However the buttons like z are working. in the menus evetything is working

**Comment by loganmc10** [comment]
Do you mean at the very start of the first level? It makes you take 3 pictures without moving the stick first to show you how to target Pokemon. After you take pictures of 3 pigeons, then it lets you move the camera around.

**Comment by Papermanzero** [comment]
No, this is exactly not coming. I am starting beach, the 3 pigeons appear and I still cannot move the camera

**Comment by Jj0YzL5nvJ** [comment]
https://imgur.com/a/M9kOJSA

**Comment by Papermanzero** [comment]
Thanks a lot. Then it is a libretro core issue. 
This is exactly not coming up. So you don’t have the tutorial at the start. The game continues.

**Comment by Papermanzero** [comment]
Yes I am trying different settings to see what gfx setting is causing the problem.

**Comment by Papermanzero** [comment]
However with the aux buffer activated Prof Eichs detection is not working. 
https://github.com/gonetz/GLideN64/issues/380

The best solution is to use Parallel RDP for the moment
