### ISSUE TITLE
Help, unplayable stuttering 

### ISSUE THREAD

**Issue by reignerdeustcher** [mupen64plus/mupen64plus-core#1041]
It's been some time that i don't play this core and the last time it worked great, today i opened a game and it's unplayable, it goes like 2 fps, even on the quick menu in retroarch is stuttered

i don't know what happened, tried downloading it again and is the same... all the other cores work properly

**Comment by richard42** [comment]
you need to file an issue report with retroarch; they are a downstream fork and break things all on their own for which we are not responsible.

**Comment by m4xw** [comment]
Nah I didnt break shit, some stuff on his end, probably frontend configuration
