### ISSUE TITLE
request a new release

### ISSUE THREAD

**Issue by chenrui333** [mupen64plus/mupen64plus-core#1070]
👋 it has been like four years since the last release, would be good to have a new one to refresh the downstream package. 

Also the 2.5.9 tag is a pre-release, might be good to bump it to latest release as well? Thanks!

![image](https://github.com/mupen64plus/mupen64plus-core/assets/1580956/82016168-a0f2-4d3a-8995-c02619dad55a)

**Comment by richard42** [comment]
Done.
