### ISSUE TITLE
Plugins error

### ISSUE THREAD

**Issue by def22** [mupen64plus/mupen64plus-core#1102]
![2024-12-15_13-45-58](https://github.com/user-attachments/assets/9e2a0195-cdfd-48be-847a-752368f084c7)
How can I fix it?

**Comment by Jj0YzL5nvJ** [comment]
Very limited info, but I can make a guess. The emulator is missing several components or the console front-end can't find them.

After seeing your issue report in PJ64, I can conclude that you may be running the ui-console from a path containing Cyrillic characters. Unfortunately, ui-console only supports English characters, it doesn't even support some Spanish, German or French characters. See mupen64plus/mupen64plus-ui-console#71.

Try [RMG](https://github.com/Rosalie241/RMG/releases/latest), in theory it should work fine in any language... but the same cannot be guaranteed for some of the components...
