### ISSUE TITLE
ARM build creates broken PIC with TEXTREL

### ISSUE THREAD

**Issue by ghost** [mupen64plus/mupen64plus-core#119]
Just tested on armhf with build script from https://launchpad.net/~random-stuff/+archive/ubuntu/ppa

The build contains TEXTREL (aka - which makes the .so a broken/not PIC shared object)

    CFLAGS="-g3 -O0" make -C projects/unix/ NEON=1 USE_GLES=1 OPTFLAGS=""  all -j4
    readelf -d projects/unix/libmupen64plus.so.2.0.0|grep -i TEXTREL
     0x00000016 (TEXTREL)                    0x0
    scanelf -qT projects/unix/libmupen64plus.so.2.0.0
      libmupen64plus.so.2.0.0: (memory/data?) [0xD6600] in (optimized out: previous .B8) [0xD65CC]
      libmupen64plus.so.2.0.0: (memory/data?) [0xD6604] in (optimized out: previous .jiptr) [0xD6600]
      libmupen64plus.so.2.0.0: (memory/data?) [0xD6608] in (optimized out: previous .jdptr) [0xD6604]
      libmupen64plus.so.2.0.0: (memory/data?) [0xD660C] in (optimized out: previous .tlbptr) [0xD6608]
      libmupen64plus.so.2.0.0: (memory/data?) [0xD696C] in (optimized out: previous new_dyna_start) [0xD6938]
      libmupen64plus.so.2.0.0: (memory/data?) [0xD6970] in (optimized out: previous .dlptr) [0xD696C]
      projects/unix/libmupen64plus.so.2.0.0

A valid PIC build is created when compiling without NEW_DYNAREC:

    CFLAGS="-g3 -O0" make -C projects/unix/ NEON=1 USE_GLES=1 OPTFLAGS="" DYNAREC="" -j4 all
    readelf -d projects/unix/libmupen64plus.so.2.0.0|grep -i TEXTREL
    scanelf -qT projects/unix/libmupen64plus.so.2.0.0

All broken instruction/definitions which require a relocation can be found in src/r4300/new_dynarec/arm/linkage_arm.S

**Comment by littleguy77** [comment]
So is this the source of this warning in the Android logcat?
```
W/linker(24206): libmupen64plus-core.so has text relocations. This is wasting memory and prevents security hardening. Please fix.
```

**Comment by conchurnavid** [comment]
Yes, this is the source of this warning and many other problems

**Comment by Gillou68310** [comment]
@conchurnavid Why trying to build the core as a PIC shared library? IMO load-time relocation should be faster (at runtime) than PIC in this case.

**Comment by conchurnavid** [comment]
For example because the new dynarec arm code automatically enables PIC?

**Comment by Gillou68310** [comment]
PIC is only enabled if using the -fPIC option at compile time, otherwise a non-PIC shared library is created. On android we're using non-PIC libraries.

**Comment by conchurnavid** [comment]
Android is even requiring -fPIE -pie for newer API levels. Also the standard toolchain setup of the NDK sets -fPIC or -fpic since ages for almost (all?) targets. Check toolchains/arm-linux-androideabi-*/setup.mk

**Comment by Gillou68310** [comment]
Yep you're right I totally missed this one, thanks for the info ;-)

**Comment by Gillou68310** [comment]
Lol the core library don't even link without PIC anyway, I now understand the issue here. Better late than never ;-)

**Comment by Gillou68310** [comment]
@conchurnavid in case you missed it @ecsv created a patch to fix the TEXTREL issue at
http://anonscm.debian.org/cgit/collab-maint/mupen64plus-core.git/tree/debian/patches/arm_pic_notextrel.patch?h=armhf_test&id=cd15ffe60ce3363d3ff78374f082e8f4b42407f0

Tested and working on android ;-)

**Comment by conchurnavid** [comment]
Thanks. I couldn't find a pull request. Created my own at #120 with the patch from Debian

**Comment by Gillou68310** [comment]
Thanks for creating the PR ;-)

**Comment by conchurnavid** [comment]
PR was merged but then the problem was reintroduced by 87b9b5778caf57f957028574a7665318966a17f9

**Comment by Gillou68310** [comment]
@richard42, @Narann this issue can be closed

**Comment by Narann** [comment]
Thanks!
