### ISSUE TITLE
Can map buttons with controller, game play doesnt work. Sixaxis

### ISSUE THREAD

**Issue by drewdoog** [mupen64plus/mupen64plus-core#126]
Im sure I shouldnt be posting here, but im at a loss. Ive posted to the mupen64+ forum, with no responses.
Im using Mupen64+ 2.2.4 (version 36) on android 4.0.4. and using Sixaxis (no version. download from playstore 7-2-15)
I can map buttons on the controller, I can go through the menu, but when I start to play a game, nothing on the controller registers.
Ive got the controller setting set in android. Ive set the controller (non-touchscreen) set on Mupen64+, but it just wont play.
Its a generic Gasia controller, but SixAxis recognizes it, and found a 'work around', and every other emulator I have works without issue. 
Any ideas?

**Comment by Narann** [comment]
Hello drewdoog! :)

There is some Mupen64Plus AE (which is the name of mupen64plus Android Edition) devs here so you would have some help.

But I have to say this is not the good place. :)

I guess the place would have been: https://github.com/mupen64plus-ae/mupen64plus-ae

mupen64plus is used by many platform and there is no "centralized" way to report things. We know it's confusing for users so don't worry, I will let the ticket here and assign it to @littleguy77.

littleguy77, feel free to unassign and/or close the ticket if you feel its irrelevant. Hope it's ok. :)

**Comment by littleguy77** [comment]
Thanks @Narann :)

@drewdoog Sorry I missed your original post on the paulscode forum, have been traveling.  I can answer your questions there:
http://www.paulscode.com/forum/index.php?topic=4415

**Comment by Narann** [comment]
Was Mupen64Plus AE related, fixed on the forum, closing now.
