### ISSUE TITLE
Several Rare games locking up while using LLE video plugins

### ISSUE THREAD

**Issue by GPDP2** [mupen64plus/mupen64plus-core#127]
Platform: Windows 7 64-bit
Emulator build: Mupen64Plus 2.5 64-bit

This issue deals with four games specifically: Banjo-Kazooie, Banjo-Tooie, Donkey Kong 64, and Perfect Dark. These games all lock up during their intros at some point or another while using any LLE video plugin. I've tested this using both z64 and GLideN64, with both the CXD4 and z64 RSP plugins. The same thing also happens in the libretro fork, which uses Angrylion's plugin as its LLE plugin. Happens using both the dynarec and interpreter cores.

For what it's worth, these games do not have this problem on Mupen64Plus 1.5, nor on the original Mupen64, with the exception of Donkey Kong 64.

**Comment by GPDP2** [comment]
So after much testing, it turns out the first release to have this problem was 2.0rc2. Banjo-Kazooie, Banjo-Tooie, and Perfect Dark all go in-game using LLE graphics on all releases before it, although both Banjo games suffer from visual stuttering.

After some digging, I found these commits, which purport to fix DK64 and Blast Corps (which I just found out, by the way, has the same issue):

https://github.com/mupen64plus/mupen64plus-core/commit/f37674f32df41462bab8c98661ae294e235d8e95
https://github.com/mupen64plus/mupen64plus-core/commit/31aaa633abc202e1e2953d78772c3ea67b11ef3a

Seems like a good place to start.

**Comment by GPDP2** [comment]
Just want to mention that the libretro fork fixed this issue for the most part, by backporting some code from Project64. Blast Corps, Banjo-Kazooie, Banjo-Tooie, and Donkey Kong 64 all work without any issues in both HLE and LLE. Only Perfect Dark fails to go past the intro in LLE, though it still works just fine in HLE.  Said fix also solved the issue with Resident Evil 2's voice acting not working in cutscenes, as well as Donkey Kong 64's character models glitching out randomly, which was a famous, long-standing problem with the game.

https://github.com/libretro/mupen64plus-libretro/commit/3609c5a117098953da789b5e535421e2007e860c

This is the commit that fixed these games.

**Comment by loganmc10** [comment]
I believe this was fixed by https://github.com/mupen64plus/mupen64plus-core/commit/f594eacd6745eec6791fe648ebaa898bad56ae75 and can probably be closed

**Comment by loganmc10** [comment]
Using HatCat's/cxd4 RSP (in LLE mode) in Project64 has the same issue with Perfect Dark, it locks up right after the "Rareware" screen.

**Comment by Narann** [comment]
@cxd4 any though about this? :)

**Comment by loganmc10** [comment]
This is the same issue as https://github.com/mupen64plus/mupen64plus-core/issues/379 and was fixed by https://github.com/mupen64plus/mupen64plus-core/commit/cdfebcf8fe39a47fd0d378c885764b78b3d9dd18
