### ISSUE TITLE
Remove processDList() from code and API

### ISSUE THREAD

**Issue by Narann** [mupen64plus/mupen64plus-core#130]
I realize [processDList()](https://github.com/mupen64plus/mupen64plus-core/search?utf8=%E2%9C%93&q=processDList) function is totally useless and should be remove both from core and API.

**Comment by Narann** [comment]
It seems, despite what API doc say, `ProcessDList()` is actually used.

* First the code retrieve the function [here](https://github.com/mupen64plus/mupen64plus-core/blob/master/src/plugin/plugin.c#L173). (`ProcessDList` became `gfx.processDList`)
* Then [it's passed](https://github.com/mupen64plus/mupen64plus-core/blob/master/src/plugin/plugin.c#L491) to the `rsp_info` structure in `plugin_start_rsp()` function. (`gfx.processDList` became `rsp_info.ProcessDlistList`)
* Then [it's passed](https://github.com/mupen64plus/mupen64plus-rsp-hle/blob/master/src/plugin.c#L213) to the HLE plugin. (`rsp_info.ProcessDlistList` became `l_ProcessDlistList`)
* And it's finally called by the HLE plugin [here](https://github.com/mupen64plus/mupen64plus-rsp-hle/blob/master/src/plugin.c#L101).

Anyone know why we've assumed in the API `ProcessDList()` function where not used?

**Comment by Narann** [comment]
I don't know what to think about this but as we can't remove it, I close this ticket.

**Comment by loganmc10** [comment]
It is definitely used by HLE graphics plugins. The docs just need to be updated to remove that note about it not being used.
