### ISSUE TITLE
si/eeprom.o (symbol from plugin): memset used with constant zero length parameter;

### ISSUE THREAD

**Issue by Narann** [mupen64plus/mupen64plus-core#136]
Mainly a question but when I compile the core I have this:
```
_obj/si/eeprom.o (symbol from plugin): warning: memset used with constant zero length parameter; this could be due to transposed parameters
```
I never notice it before.

**Comment by richard42** [comment]
yeah I looked into this some time ago.  I'm pretty sure that I eventually decided that it was some kind of defect in GCC.  Hopefully it should get resolved in a newer version.

**Comment by mackal** [comment]
Is it this bug https://sourceware.org/bugzilla/show_bug.cgi?id=16746 ? (which was fixed and I don't get any messages)

**Comment by Narann** [comment]
Thanks! Let's don't waste our time with this.
