### ISSUE TITLE
Configurable VI Refresh Rate

### ISSUE THREAD

**Issue by Gillou68310** [mupen64plus/mupen64plus-core#139]
A few people on paulscode.com are asking about a configurable VI refresh rate option (like PJ64).
The main motivation is when using a lag remover cheat code (which typically disable ingame framelimiter), but such a cheat code should be reversed compensated by lowering VI Refresh Rate value in order to get back initial framerate.

Using this combo sometimes help fixing framerate issues in some games.

@richard42 @Narann do you mind if I add such an option?

**Comment by Narann** [comment]
I mainly see such thing as more code to add and maintain to try to workaround thing on some games (and to be honest, I'm not even sure it will improve frame-rate).

You can't have an efficient _lag removing cheat_ effect with HLE without workaround. I'm just afraid the final code will be a bunch of nested if/if everywhere in the code while there is already many.

I don't know about PJ64. Have you any screenshot to share?

**Comment by richard42** [comment]
Hi Gillou68310,

Can you explain a bit more about how this feature would work and what it would
do?  I assume that the main purpose is to just modify the VI timing interval
(real opengl frames drawn per second) and not do anything like changing
emulated CPU instructions per VI ala CounterPerOp, correct?  This is already
done for the Fast Forward feature, so simply adding an option to change the
base VI rate (which is currently set by the game: I think 50 for PAL / 60 for
NTSC) shouldn't be a big deal.  Would this be a user option in the config file
or a per-game option in the INI?

Richard

**Comment by Gillou68310** [comment]
Thanks for your comments,

I guess codes speaks more than words, here's what I have in mind:
https://github.com/Gillou68310/mupen64plus-core/commit/d60eefba9262cb057c89cb1c5f464f494b90ec3c

I don't really need this option myself so I'm probably not the right person to defend it.
I invited people from paulscode.com to join this discussion and explain why they need this option.

**Comment by richard42** [comment]
I see from this commit that it's a pretty simple option, and it's in the global config file.  It looks like this will change the number of r4300 instructions which get executed before the next VI fires.  Does anyone have experience with this setting, and can offer some examples of games which perform better with higher values than the default 1500?

**Comment by Isotarge** [comment]
From myself and @cronikeys experience, tweaking this setting along with cycle count per instruction can have a pretty drastic effect on DK64's in game timer accuracy and demo sync. During the Japes DKTV demo these settings can be the difference between DK successfully jumping and catching the vines and turning right too soon completely missing them and falling into the water, which curiously also happens in the VC re-release of the game. Can any core experts explain how and why 1500 was chosen in the first place? Also worth noting that PJ64 currently supports modifying this setting.

**Comment by richard42** [comment]
I suspect that the number 1500 was arbitrarily chosen because it provided an acceptable balance of working well with most games and maintaining good performance.  If this number is too small then the emulator will not execute enough R4300 cycles before a VI fires, and there will be glitches/bugs in the game.  But if it's too high then there will be wasted CPU time while the emulator is running some R4300 loop which is spinning, waiting for the next VI to occur.

**Comment by MaximeMorel** [comment]
It can be quite nice for some games. For example, Conker's bad fur day, raising the value beyond 1500 will make the game a lot smoother, solid 30 fps. And the game will still run at normal speed, not accelerated. It seems the game does not care about R4300 frequency (if we can consider raising this 1500 value as a kind of overclocking...) and will adjust the frame duration to run at normal speed.
But Perfect Dark or Golden Eye will be accelerated and seems to rely heavily on this cycles frequency...
I guess there is a lot of hacks in the "1964 60 fps bundle" about that.

**Comment by richard42** [comment]
OK, I'll accept an option for this parameter, but it needs to be a per-game option (in the mupen64plus.ini file) and not a global option in the .cfg file.  If someone sends me a pull request like this I'll merge it.

**Comment by loganmc10** [comment]
@Gillou68310 I am going to submit a pull request for this (per game setting), just one question.

in vi_controller.c, you change:
```
: (vi->regs[VI_V_SYNC_REG] + 1)*1500;
```
to:
```
: (vi->regs[VI_V_SYNC_REG] + 1)*g_vi_refresh_rate;
```

But why did you leave:
```
vi->regs[VI_CURRENT_REG] = (vi->delay - (vi->next_vi - cp0_regs[CP0_COUNT_REG]))/1500;
```

I assume it is referring to the same 1500?

**Comment by Gillou68310** [comment]
I backported this from project64, maybe I did it wrong. You should double check what project64 is doing just to be sure.
