### ISSUE TITLE
Bomberman 64: transition and effets are not rightly emulated

### ISSUE THREAD

**Issue by legluondunet** [mupen64plus/mupen64plus-core#149]
Hello,

Mupen64  does not emulate rightly Bomberman64: transition effect are not correct.
It is not easy to describe this, look at the video:
https://www.youtube.com/watch?v=mE1DaVMN6pE

and now try this game with Mupen64: at start the transition are not right.

**Comment by conchurnavid** [comment]
Why should I try mupen64? This here is about mupen64plus-core (which has nearly nothing to do with graphics emulation) and not mupen64.

If you want to make such a vague bug report for mupen64plus then maybe you use https://github.com/mupen64plus/mupen64plus-user-issues/issues  as written under http://mupen64plus.org/contact/ - and please also specify what graphics plugin you've used. glide64mk2, gliden64, glide64, rice, arachnoid, z64, ...?

**Comment by legluondunet** [comment]
Oooops wrong place, sorry. Too much mupen64plus places on Github.
