### ISSUE TITLE
Matching code for input neglects spaces in controller names

### ISSUE THREAD

**Issue by paradadf** [mupen64plus/mupen64plus-core#152]
Some internal controller names differ only in spaces from each other.  As it subdivides the words between spaces, the spaces are not being taken into account. The name has to do with the firmware of the controllers, and cannot always be changed if the firmware isn't upgradable. As a consequence, many controllers can't be used together.

**Comment by Narann** [comment]
I'm not sure to understand. Why not add both in the ini?

Have you any name example?

**Comment by paradadf** [comment]
http://pastebin.com/N604xSm3

Please take a look at the first and last controller settings. They are two different controllers (8bitdo NES30 PRO and 8bitdo Zero). The only difference between both names are the spaces at the end of the name.

[Bluetooth Wireless Controller   ]
[Bluetooth Wireless Controller]

**Comment by richard42** [comment]
that is truly unfortunate..  I designed this space-agnostic thing as a feature; I thought it would be good to allow some flexibility for slight differences in the names..  But maybe I'll to revisit that idea. It would be easy enough to make it require the exact same name.

**Comment by paradadf** [comment]
This is just an idea, as I don't know how the configuration itself works...
What about checking first if there are exact names that match the controllers and assign them respectively and, if there are unassigned ones, use the space-agnostic feature for the remaining?

**Comment by richard42** [comment]
Okay, I just pushed a change to address this issue.  It's actually in the mupen64plus-input-sdl module, not the core.
