### ISSUE TITLE
Paper Mario (U) flash written incorrectly

### ISSUE THREAD

**Issue by roothorick** [mupen64plus/mupen64plus-core#154]
The libretro guys observed this issue a good two years ago: https://github.com/libretro/mupen64plus-libretro/issues/63 Seeing the same symptoms in M64Py 2.3; from a quick skim of the commit log I didn't see any attempt to directly address it.

By all appearances ingame: when game-save data is written, a copy is written in all subsequent slots i.e. saving in slot 2 replicates the data to 3 and 4. The errant duplicates appear after returning to the title screen and reopening the load menu. Trying to copy saves has the same effect, starting from the slot copied to. Bizarrely, deleting a save doesn't behave the same way.

Seen claims that Project64 shows the same issue. Makes me wonder if the game had an unusual flash RAM setup that nobody noticed.

**Comment by loganmc10** [comment]
@roothorick I finally figured out a solution to this problem:

https://github.com/mupen64plus/mupen64plus-core/pull/375
