### ISSUE TITLE
Crash during Mario Party (Coin Block Bash)

### ISSUE THREAD

**Issue by loganmc10** [mupen64plus/mupen64plus-core#158]
Every single time I try to play "Coin Block Bash (Mario Party 1)" while playing a regular game (doesn't matter what map), mupen64plus crashes, this is the error I get:

```
mupen64plus: ../../src/r4300/new_dynarec/new_dynarec.c:9777: new_recompile_block: Assertion `(branch_regs[i].is32&(1LL<<f_regmap[hr]))== (regs[i+2].was32&(1LL<<f_regmap[hr]))' failed.
```

This is on a Raspberry Pi 3 using the latest git source.

**Comment by Gillou68310** [comment]
This should fix the issue
https://github.com/Gillou68310/mupen64plus-core/commit/735425a08fddeb0dec26d99ee8129dccee8c7870

**Comment by Gillou68310** [comment]
@loganmc10 Could you provide a savestate so I can check if my patch fixes the issue?

**Comment by Gillou68310** [comment]
@fzurita could check if my patch fixed the issue I'd like to make a new PR with all fix to the new dynarec.

**Comment by loganmc10** [comment]
Sorry I'll try and test this tonight, I'm not really setup to provide a savestate since I don't use mupen64plus (I use GLupeN64, a RetroArch plugin), but I'll test this out and let you know.

**Comment by Gillou68310** [comment]
Thanks for your time ;-)

**Comment by Gillou68310** [comment]
> Huh well I swear I'm not crazy lol maybe it depends on what map us being played? I don't remember what map it happened on but it happened twice to me a while ago

Lol don't worry I know you're not crazy because the assertion failure happens to me on my wip arm64 branch, unfortunately I don't remember which game was causing the issue. Anyway this patch https://github.com/Gillou68310/mupen64plus-core/commit/c212ad75ad43b0803c01163dc8086923c9ca232a fixes the issue for me.

**Comment by codyxmeadows** [comment]
Call me a noob but how do I apply this fix to Mupen on my Raspberry pi? I searched for the directory the attached file is in but I cant seem to find it.

**Comment by fzurita** [comment]
You have to edit the code by applying this commit: https://github.com/Gillou68310/mupen64plus-core/commit/c212ad75ad43b0803c01163dc8086923c9ca232a

Then you have to rebuild the core library.

**Comment by loganmc10** [comment]
Isn't this fixed though? I closed it because I tested it and it no longer happened, should this be reopened?

**Comment by fzurita** [comment]
Good point, it should already be in the latest code. So unless he is trying to apply a patch to an older version....

**Comment by codyxmeadows** [comment]
I updated and it seems to be fixed. Sorry for the confusion. I am getting a crash at another point in the game. I will investigate that further. Thread can be closed.
