### ISSUE TITLE
Vidext SDL2 compatibility overrides context profile mask, making attribute useless

### ISSUE THREAD

**Issue by wareya** [mupen64plus/mupen64plus-core#160]
The SDL_SetVideoMode reimplementation sets the profile mask attribute, with no care whether it has already been set.

    #ifndef USE_GLES
        SDL_GL_SetAttribute(SDL_GL_CONTEXT_PROFILE_MASK, SDL_GL_CONTEXT_PROFILE_COMPATIBILITY);
    #else // !USE_GLES

Part of the purpose of this function is to open the GL context, so reordering calls on the video plugin side of things can't work around this.

    if (flags & SDL_OPENGL) {
        SDL_VideoContext = SDL_GL_CreateContext(SDL_VideoWindow);

This makes opening a 3.2 or higher context on Mesa impossible because Mesa does not allow versions higher than 3.1 to be opened in compatibility profile. Leaving the profile mask unset causes it to default to CORE for 3.2 and higher.

    [...] If the requested OpenGL version is less than 3.2,
    GLX_CONTEXT_PROFILE_MASK_ARB is ignored and the functionality of the
    context is determined solely by the requested version.
    [...]
    The default value for GLX_CONTEXT_PROFILE_MASK_ARB is
    GLX_CONTEXT_CORE_PROFILE_BIT_ARB. All OpenGL 3.2 implementations are
    required to implement the core profile, but implementation of the
    compatibility profile is optional.

This prevents GLideN64 from working correctly on Mesa, because it requires GL 3.3 for shaders. I still only get a black screen with sound after patching both the core and the plugin, but at least it doesn't segfault or take down my system just trying to boot anymore.

**Comment by richard42** [comment]
I tried reproducing this problem with my system (Gentoo linux, AMD 7750 GPU) but I was not able to.  Can you provide a patch that fixes this problem?

**Comment by wareya** [comment]
The solution is to outright delete this line: https://github.com/mupen64plus/mupen64plus-core/blob/d6880e5/src/api/vidext_sdl2_compat.h#L418

However, the OSD only works with oldschool SDL. I hacked up a modern GL OSD here, but it doesn't work *exactly* the same as the current one, and my branch changes other random stuff that I don't remember the reasoning behind: https://github.com/wareya/mupen64plus-core/commit/b3f6a2f8a9c53eada4dc65d0ba5d6f9a951faf0e

**Comment by richard42** [comment]
If we remove the compatibility profile OpenGL attribute in that line, will it break the operation of the other video plugins using the legacy opengl pipeline?

**Comment by wareya** [comment]
The profile mask attribute only applies to opengl versions 3.2 and newer. It's not a feature of any former opengl versions, and doesn't affect them. Basically, setting compatibility profile mode just ensures that modern GL plugins won't work at all if the driver doesn't support compatibility profile at that GL version. What it does ensure is that the legacy GL OSD might work with a modern GL plugin, if the driver supports compatibility profile at the plugin's GL version. I don't think the modern GL OSD will work with legacy GL plugins, though. That's why I never tidied up and made a PR.

**Comment by richard42** [comment]
Right, it's all coming back to me now.  I think the Windows and most of the Linux (HW) GL drivers support the compatibility profile with >=3.2 opengl, while Mac OSX (and apparently Linux/Intel) does not.

So this particular behavior of this SDL wrapper prevents the glideN64 plugin from working with Intel GPUs on systems with SDL2? And if we remove the line forcing the compatibility context, it will work but you won't get any OSD (with Intel drivers and possibly with other drivers as well).

We could have a sort of compromise to get at least as much working as possible.  The glideN64 plugin should call the VidExt_GL_SetAttribute() function to request a SDL_GL_CONTEXT_PROFILE_CORE context before calling SetVideoMode(), right?  So in the SDL2 wrapper we could call SDL_GL_GetAttribute() to query the state of this flag, and then only request a compatibility context if the Core context had not already been requested.  This would allow the OSD to work on other (non-Intel) drivers, and allow the glideN64 plugin to at least work with the Intel hardware.

**Comment by wareya** [comment]
>while Mac OSX (and apparently Linux/Intel) does not.

On Linux it's with mesa. I'm running mesa on an AMD card.

> So this particular behavior of this SDL wrapper prevents the glideN64 plugin from working with Intel GPUs on systems with SDL2?

Yes. (GLideN64 uses GL4 features that Mesa doesn't support yet, but they can be patched out; I have a fork that makes GLideN64 run on GL 3.3 only, letting it run on Mesa with a patched m64p)

> And if we remove the line forcing the compatibility context, it will work but you won't get any OSD (with Intel drivers and possibly with other drivers as well).

I think I had to disable the OSD in ini before I ported it, but I'm not sure.

> We could have a sort of compromise to get at least as much working as possible. The glideN64 plugin should call the VidExt_GL_SetAttribute() function to request a SDL_GL_CONTEXT_PROFILE_CORE context before calling SetVideoMode(), right?

As long as the sdl2 compat layer doesn't set SDL_GL_CONTEXT_PROFILE_CORE at all, yes, that's correct.

> So in the SDL2 wrapper we could call SDL_GL_GetAttribute() to query the state of this flag, and then only request a compatibility context if the Core context had not already been requested.

I think that trying to force compatibility profile mode should be something that the user has to manually turn on in the settings, and that if m64p itself ever tries to force the profile, it should do what you said and make sure the video plugin isn't trying to override it to core. The legacy OSD will never work on modern GL plugins on OSX/Mesa anyway.

It would be better to have multiple OSDs in the core, but that's a lot of work. Or there could be a plugin OSD system /sarcasm

**Comment by Tele42** [comment]
For reference, Apple devs stopped at GL 2.1 and Mesa devs stopped at GL 3.0 for the compatibility profile. The current intent of those devs is to push only the core profiles.

With mesa, if your chipset does not support all the features needed to expose GL 4 (mostly fp64), but has the extensions you need to run your application, you can use the ```MESA_GL_VERSION_OVERRIDE``` and possibly ```MESA_GLSL_VERSION_OVERRIDE``` env variables to lie about your supported version on a per-application basis.

**Comment by richard42** [comment]
please see commit 986c228, and let me know if this fixes the issue for you.

**Comment by wareya** [comment]
It looks like it should. I'll test it within the next few days.

**Comment by wareya** [comment]
It works, though I still *really* don't like it how the video plugin has to explicitly ask for core profile. We should get a second OSD instead.

**Comment by richard42** [comment]
I agree it would be nice to have an OSD that uses shaders and would work under either compatibility or core profiles, but that would also be quite a bit of work.
