### ISSUE TITLE
Does not work on Windows XP (but works if binaries are patched)

### ISSUE THREAD

**Issue by dsp2003** [mupen64plus/mupen64plus-core#163]
The Win32 subsystem version for generated binaries is set to "6.0", which does not allow the emulator to work on Windows NT 5.x series (2000, XP and 2k3).

If patched to "4.0", the emulator works with no problem. Since the emulator does not appear to use any NT 6.x-specific functions, it's meaningless to set subsystem version to "6.0".

**Comment by richard42** [comment]
Which binaries are you referring to?  One of our binary bundle releases (if so, which release version?)  Or one that you built yourself (if so, with Visual Studio or MXE?)

**Comment by dsp2003** [comment]
Yours, of course.

**Comment by richard42** [comment]
OK, I just committed project file changes to fix this.  Thanks for bringing it up.
