### ISSUE TITLE
glide64mk2 requires libboost 1.46.1

### ISSUE THREAD

**Issue by groverj3** [mupen64plus/mupen64plus-core#166]
Hey there,

I was having the hardest time figuring out why I was unable to load the glide64mk2 plugin from the 2.5 release, but it seems that was due to a missing dependency, libboost-system-1.46.1 and libboost-filesystem-1.46.1. I'm on Linux Mint 17 and that was not available from the repos. I was, however, able to get it working by manually downloading a deb from and older Ubuntu repo.

I wasn't sure if this should go in the repository for the plugin or here, but I figure it'd be of interest to anyone using the official release.

Any chance things could be updated to use a newer version of libboost? I have no idea if this is trivial or difficult.

**Comment by richard42** [comment]
I think you have to bring this issue up with the debian/ubuntu/mint package
maintainer(s).  Our makefile just builds against whatever version of boost you
have installed.  On my gentoo machine it's 1.56.0.

Richard

**Comment by groverj3** [comment]
I didn't download the version on the Ubuntu/Mint reps since they aren't up to date with the latest release. I downloaded the 2.5 release directly so it's likely a problem of the official release being built referencing the old version of boost.
