### ISSUE TITLE
N64 from open emu suddenly stopped working. 

### ISSUE THREAD

**Issue by ratedsc** [mupen64plus/mupen64plus-core#167]
It was working great. I beat mario 64 on it. Had it for 2 weeks. Suddenly out of no where, any game I open with N64, i get an error message saying "Couldn't communicate with a helper application" Can I get help? All other roms works fine. Its just the n64 emulator. I play open emu on a Macbook Air. Thanks!

**Comment by richard42** [comment]
This sounds like an error coming from open emu itself; you will probably have to get in touch with their development team to solve this.

**Comment by ratedsc** [comment]
I updated it to the newest version 2.0.2 and it works now! but... with the new version, the power button is no longer functional so I have to force quit every game and reopen the app -.- Hopefully they'll release a patch soon to fix that.
