### ISSUE TITLE
With mouse input disabled, mouse still gets captured and ctrl alt does nothing

### ISSUE THREAD

**Issue by ledoge** [mupen64plus/mupen64plus-core#169]
Using the latest core bundle on Windows.

Issue: When I alt-tab out, I can not move the mouse. It is stuck in the top left corner. ctrl alt in the emulator does not release the mouse.

Expected behavior: ctrl alt should show and release the mouse cursor

Steps to reproduce: With mouse = False set on every controller, launch a ROM and alt-tab out.

**Comment by richard42** [comment]
I have a few questions about this:
1. Which version of Windows are you using?
2. Are you running in fullscreen mode or windowed mode?

**Comment by ledoge** [comment]
Using Windows 7 and fullscreen mode.
If it helps, I uploaded my mupen64plus.cfg [here](https://upl.io/ohppj7)

**Comment by richard42** [comment]
Thanks, I tested this on my win 7 laptop with an nvidia quadro card.  I was able to reproduce the problem with the 2.5 release, but it has been fixed in the latest code in our git repository.  It's probably about time to make a new release.
