### ISSUE TITLE
Banjo-Tooie crash

### ISSUE THREAD

**Issue by fzurita** [mupen64plus/mupen64plus-core#170]
@Gillou68310 

I'm seeing this crash reported on the ARM version of the new dynarec:

"oops, branch at end of block with no delay slot"

I'm seeing this happen in Banjo-Tooie. Here is a save state: 
[Banjo-Tooie-crash.zip](https://github.com/mupen64plus/mupen64plus-core/files/387481/Banjo-Tooie-crash.zip)

Face the big digging machine and throw an egg at it by holding Z and C-UP

This is happening in new_dynarec.c at line 8553.

**Comment by Gillou68310** [comment]
I managed to reproduce it on arm64 but x86 does not have the issue, I'll investigate ;-)

**Comment by Gillou68310** [comment]
I'm in vacation for 3 weeks so I won't be very active

**Comment by fzurita** [comment]
OK, thanks!

**Comment by Gillou68310** [comment]
@fzurita I can't reproduce it anymore on arm64!
Only think I did was to update GLiden64 to the latest version.
Did you checked if this was actually happening with other video plugin?

**Comment by fzurita** [comment]
That's a good point, I didn't try any other plugins, but the crash seems to be at the core. I'll check again.

**Comment by fzurita** [comment]
I just tried Angrylion and Glide64. Both crashed in the 32bit dynarec.

**Comment by fzurita** [comment]
Maybe you fixed it by accident?

**Comment by Gillou68310** [comment]
I didn't changed anything in the core that's weird

**Comment by fzurita** [comment]
I can try building your latest 64bit core and check if I get a crash there. It will have to wait until later tonight though.

**Comment by Gillou68310** [comment]
Could you test with latest GLiden64 version just to be sure

**Comment by Gillou68310** [comment]
And with interpreter ;-)

**Comment by fzurita** [comment]
Sure

**Comment by fzurita** [comment]
Interpreter doesn't crash with latest GLideN64

**Comment by Gillou68310** [comment]
But new dynarec does?

**Comment by fzurita** [comment]
Yes

**Comment by Gillou68310** [comment]
Ok I guess I'll have to do the test on arm32 to be in the same conditions. Time to resurrect my RPi2!

**Comment by Gillou68310** [comment]
Here's the only fixes I made to the arm64 branch that you can test
https://github.com/mupen64plus/mupen64plus-core/pull/177
https://github.com/mupen64plus/mupen64plus-core/pull/178

**Comment by Gillou68310** [comment]
Ok now this is weird I built the latest version of mupen64plus-ae tested with both GlideN64 and Glide64 and it's not crashing

**Comment by Gillou68310** [comment]
It would be great if you can get me a savestate with the egg already thrown and crashing everytime you do a loadstate.

**Comment by fzurita** [comment]
Really, you can't reproduce it with the above steps and save state?

**Comment by fzurita** [comment]
I'll do that real quick.

**Comment by fzurita** [comment]
Here it is

[tooie-crash.sav.zip](https://github.com/mupen64plus/mupen64plus-core/files/437681/tooie-crash.sav.zip)

Load that save state and it should crash almost immediately.

**Comment by fzurita** [comment]
Ok, I tried pull requests:
https://github.com/mupen64plus/mupen64plus-core/pull/177
https://github.com/mupen64plus/mupen64plus-core/pull/178

Neither of these fixes the crash here.

**Comment by Gillou68310** [comment]
Ok I see what's happening here, you'll have to do the loadstate real quick after the core startup or it won't crash. I usually wait until the first logo screen and it's not crashing in this situation. This is because the block causing the assertion error is already recompiled as part of another block.
Anyway it's now 100% reproducible so I can start investigating!

**Comment by Gillou68310** [comment]
Ok the crash happens because we are compiling junk! Speculative precompilation is disabled very early for this game (stop_after_jal=1) but if you do a loadstate before it has been detected, when recompiling block address 0x8037ecd0 the dynarec will try to recompile the code located after a JAL instruction which in this case is junk.

**Comment by fzurita** [comment]
Oh, nice. Is there any way to make that flag part of the sace state?

**Comment by fzurita** [comment]
1.

**Comment by fzurita** [comment]
Whoops, fat finger in mobile.

**Comment by fzurita** [comment]
Could we add additional data to the save state so that we store that flag there? We could make the save state compatible with older versions of the core as long as we add to the end of the save state, right?

Also, does the same thing apply to the uses_tlb flag?

**Comment by Gillou68310** [comment]
These flags have nothing to do in the savestate IMO. We need to find a better way to check if we're compiling junk.

**Comment by fzurita** [comment]
Ok, that seemed like a feasible solution to me since these errors can only happen if loading from a save state. The flag state is not saved which causes this issue.

**Comment by Gillou68310** [comment]
I wonder why @Ari64 checks ````opcode[i]==0x11````? All "Not Implemented" instructions should be considered as junk IMO.

````
// Stop if we're compiling junk
if(itype[i]==NI&&opcode[i]==0x11) {
  done=stop_after_jal=1;
  DebugMessage(M64MSG_VERBOSE, "Disabled speculative precompilation");
}
````

**Comment by fzurita** [comment]
Is there something special about that opcode?

**Comment by Gillou68310** [comment]
These are instructions for co-processor 1 nothing special to me

**Comment by fzurita** [comment]
If we were to check all non-implemented instructions by checking to make sure it's one of the implemented ones, wouldn't that make that if statement very long? Is there a better way of doing that?

**Comment by Gillou68310** [comment]
> Is there a better way of doing that?

````if(itype[i]==NI)```` means that the current MIPS opcode is not valid (at least for that processor version)

**Comment by fzurita** [comment]
Oh, gotcha. Sounds like that's an easy fix. The bigger question is if it's the right fix.

**Comment by Gillou68310** [comment]
It's unlikely to brake anything else, the real question is will this fix have an impact on performance. Maybe ````if(itype[i]==NI)```` is happening quite often disabling speculative precompilation in almost every scenarios.

**Comment by Gillou68310** [comment]
Ok I think you can provide a build to mupen64plus-ae testers with ````stop_after_jal```` set to 1 in ````new_dynarec_init```` to see the impact of speculative precompilation on performance.

**Comment by fzurita** [comment]
That change fixes this issue?

**Comment by fzurita** [comment]
I tested that I don't really see any performance difference at all. I'll give the update to willing/unwilling testers and see what they think.

So little time is spent in the core compared to the graphics that I doubt it will make much difference.

**Comment by fzurita** [comment]
Retroben tried it in his usual performance tests. He didn't see a difference in performance either.

**Comment by retrobenny** [comment]
Hullo! ✋

**Comment by Gillou68310** [comment]
Well actually I was talking about cheat codes that work with mupen's interpreter and don't work with new dynarec!

**Comment by Gillou68310** [comment]
> Retroben tried it in his usual performance tests. He didn't see a difference in performance either.

Ok let's set stop_after_jal to 1 by default. I think this should be done with a core config parameter.

**Comment by retrobenny** [comment]
I need to test Groggy again to see if he crashes without legacy blending enabled.

**Comment by fzurita** [comment]
Ok, there is a problem with this. With ```stop_after_jal=1``` Blast corps doesn't get past the opening N64 logo.

**Comment by Gillou68310** [comment]
For some reason @Ari64 also stops speculative precompilation after a SYSCALL. 
````if(i>0&&itype[i-1]==SYSCALL&&stop_after_jal) done=1;````

The problem is when a JAL is located just behind the SYSCALL you get a branch at end of block with no delay slot.

  0x8029e624: ADDIU r21,r0,20
...
* 0x8029e6b4: ADDIU r1,r0,1
  0x8029e6b8: BEQ r30,r1,8029e6d4
  0x8029e6bc: SLL r0,r0,0
* 0x8029e6c0: SYSCALL
* 0x8029e6c4: JAL 8029ef80 <- end of block

Since SYSCALL doesn't have a delay slot I think we can safely end the block after the SYSCALL.
````if(i>0&&itype[i]==SYSCALL&&stop_after_jal) done=1;````

**Comment by fzurita** [comment]
Ok. I'm glad you are really good at finding these issues.

**Comment by Gillou68310** [comment]
Well actually issues triggering asserts are the easy ones. This one https://github.com/mupen64plus/mupen64plus-core/issues/174 is going to be harder ;-)

**Comment by fzurita** [comment]
Oh, yeah, that will be tough I'm sure.

**Comment by retrobenny** [comment]
Oops,forgot to say it happily still doesn't crash on Groggy anymore using GLideN64 with non-legacy blending,maybe make that change only affect certain games,one being Banjo-Tooie obviously.

Slightly off topic but,too bad performance is still sucky though,even at 640x480 at the most optimal and sacrificial settings on Conker,but at least the Buga's Knuts pixelated defeat scene is still smooth.
Maybe we need to get Nvidia to add Mupen64Plus AE/FZ to the profiles list like Dolphin Emu already has before the big update comes out for Shield TV so it comes with it.
Primarily to use from 600Mhz to 900Mhz of GPU clock rate on their X1 chip.
Does GLideN64 even utilize the 256 cores within it for multi-threading?

**Comment by fzurita** [comment]
With fragment shaders, the driver makes the decision about how many copies to use. Usually it will use as many as it can.

With CUDA/OpenCL you have fine grained control about how many to use.

**Comment by richard42** [comment]
This should be fixed with the pull request that I just merged from Gillou68310.  fzurita, can you build the latest and test?

**Comment by fzurita** [comment]
Yes, I will test this tomorrow.

**Comment by fzurita** [comment]
It's fixed.
