### ISSUE TITLE
Screenshots broken on raspberry pi

### ISSUE THREAD

**Issue by ricrpi** [mupen64plus/mupen64plus-core#172]
On raspberry pi we have to use GL_RGBA with glReadPixels(). This means the buffer must be 4x the pixel count. However the core is expecting on 3x as GL_RGB is currently used.

Increasing the buffer size will stop mupen64plus from locking up the GPU but changing SaveRGBBufferToFile() to use 'width * 4',  to get good screenshots, would require a change in all video plugins or an API change to get the expected pixel width from the video plugin.

Does anyone have any suggestions for the way forward?

**Comment by ricrpi** [comment]
After some more thinking I can probably do some form of translation from RGBA to RGB within the video plugin before writing to the buffer from the core

**Comment by richard42** [comment]
This is a good idea.  24-bit RGB pixels are not at all friendly with modern hardware so I'm not surprised it's not supposed on the rpi.   Probably the best thing to do is convert it in the plugin as you suggested; it would be a pain to change the API.

**Comment by ricrpi** [comment]
Video plugins now convert and screenshots work with the official core
