### ISSUE TITLE
Audio cuts off in Army Men: Sarge's Heroes with new dynarec

### ISSUE THREAD

**Issue by fzurita** [mupen64plus/mupen64plus-core#174]
Copied and pasted from: http://www.paulscode.com/forum/index.php?topic=1818.915

> Army Men: Sarge's Heroes-- The game's sound completely cuts out in the beginning of the second level. Restarting the game brings the sound back, but it just quickly cuts out again after you reload the second level and play it for about 30 seconds to a minute. I decided to keep playing until I made it to the third level. I then restarted the game again and loaded up the third level where I left off. The sound was there for about 30 seconds and then quickly cut out again. Changing the graphic and audio plugin didn't fix it. 

This was fixed by switching to cached interpreter.

**Comment by Gillou68310** [comment]
Just check on both x86 and ARM and I can't reproduce it.

**Comment by fzurita** [comment]
Hmmm, interesting, I wonder if it got fixed somehow.

**Comment by Gillou68310** [comment]
Might be worth saying that I tested with this branch https://github.com/Gillou68310/mupen64plus-core/tree/new_dynarec_fix

**Comment by fzurita** [comment]
Ok. Apparently, it was only on the third level that had this issue. Maybe I should ask for a save state.

**Comment by Gillou68310** [comment]
I just finished level 3 with no issue

**Comment by Gillou68310** [comment]
Maybe we are playing a different version of the game, if you ask for a savestate, please also ask for the ROM MD5

**Comment by fzurita** [comment]
Ok, I was able to experience a similar issue. But it was all sound that cut out on the first level. Whenever I would fire my gun, I would also very weird noises.

**Comment by fzurita** [comment]
Here is my md5: B8085C2EDB1C6D23E52ED8C06D92B4F8

**Comment by loganmc10** [comment]
I just came across this issue (Android), I took a save state and it still happened after I closed and loaded from that save state

**Comment by Gillou68310** [comment]
@fzurita @loganmc10 is this still an issue with #871?

**Comment by fzurita** [comment]
I can't reproduce this any more. I get music on the second level now. I can't believe how hard the first level is to beat though, lol. We should close it once #871 is merged.
