### ISSUE TITLE
NBA live 2000 crash

### ISSUE THREAD

**Issue by fzurita** [mupen64plus/mupen64plus-core#179]
@Gillou68310 

NBA live 2000 causes the core to crash when entering the first set of menus. This crash is happening using the arm32 new dynarec.

This crash doesn't happen with interpreter.

**Comment by Gillou68310** [comment]
Ok this is caused by a divide by zero in div64. Checking if divisor is not null fixes the issue. I'll make a PR.

**Comment by fzurita** [comment]
Fixed in latest
