### ISSUE TITLE
Top Gear Really 2 freezes

### ISSUE THREAD

**Issue by fzurita** [mupen64plus/mupen64plus-core#181]
I'm heading a lot that Top Gear Rally 2 is freezing mid race or right after the race finishes. This is regardless of RSP or video plugins, or interpreter or dynarec mode.

This is similar to the Tarzan freezes that were just fixed.

**Comment by loganmc10** [comment]
I tested this on Linux and it froze all the time with:

```
Core Warning: two events of type 0x80 in interrupt queue
```

Seemingly random, but quite often, could never get through a full lap.

Setting ```CountPerOp=1``` fixed the problem for me, did a few laps without freezing. Perhaps someone else could confirm. If that does fix it then it can be added to the ini

**Comment by loganmc10** [comment]
Actually with ```CountPerOp=1``` I get a ```Core Warning: two events of type 0x80 in interrupt queue``` error and a freeze in the menu if I let it sit there. I get the same thing with CountPerOp=2

However, if I comment this out:
https://github.com/mupen64plus/mupen64plus-core/blob/master/src/device/r4300/interrupt.c#L155

Then I still get ``Core Warning: two events of type 0x80 in interrupt queue```, but no freeze. It seems that hack should be specific to Perfect Dark.

Since I rambled a bit: I think the best way to fix this game is set CountPerOp=1 and make that interrupt hack specific to Perfect Dark

On a side note, @bsmiles32. I notice that you were working on this: https://github.com/bsmiles32/mupen64plus-core/commit/9b98afade1ea609dc738108709874339829629d0.

Is this (https://github.com/bsmiles32/mupen64plus-core/commit/a1b6df0800dd86936b8500cb7b731b10ee8d79ac) still possible? Can we do that and get rid of the Perfect Dark hack altogether?

**Comment by bsmiles32** [comment]
These commits are old and I unfortunately don't remember exactly why I did them this way... Will have to rethink why. Sorry

**Comment by loganmc10** [comment]
No problem, I submitted a PR to look at (https://github.com/mupen64plus/mupen64plus-core/issues/307) that implements that idea. So far my testing results are quite promising, and it fixes the crashes in this game without having to play with the CountPerOp settings. But obviously that kind of change will need quite a bit of testing to avoid regressions.

**Comment by fzurita** [comment]
This one should be closed.
