### ISSUE TITLE
Building on Windows

### ISSUE THREAD

**Issue by AlessandroPorcelli91** [mupen64plus/mupen64plus-core#183]
How do I start? I'd like to test the latest source but I don't know what to use in order to build mupen64plus under Windows. Is there a buildbot somewhere? What toolchain should I be using? Thanks.

**Comment by rlabrecque** [comment]
https://github.com/mupen64plus/mupen64plus-core/tree/master/projects/VisualStudio2013

Visual Studio 2013.

VS2015 works fine as well once you upgrade the projects.

**Comment by AlessandroPorcelli91** [comment]
Man, I suck at navigating these pages :D Thanks a lot.
