### ISSUE TITLE
Perfect Dark freezes occasionally when attempting to start next level

### ISSUE THREAD

**Issue by SigmaVirus** [mupen64plus/mupen64plus-core#186]
This is an old issue that have been around for ages in both Mupen64/Mupen64Plus and Project64 AFAIK.
It's easy to reproduce too, and the fastest way to reproduce it is to clear the first level/mission on Agent which can be made in 45-50 seconds if you're fast enough.

Don't know if you can savestate just before you finish the level in order to reproduce the freeze but anyway, once the level has ended after the elevator and gun reload scene with Joanna you'll see the status screen for the completed level and given the option to either go to the next level or go back to Carrington Institute.

When you choose next level two things can happen here:
1. The game proceeds normally to the next level
or
2. It freezes the game and you have to end the emulation and restart

I've heard using a memory/controller pak save instead of game pak save will sometimes fix it but whether or not it's true I don't know.

I really hope this can be fixed permanently.

**Comment by SigmaVirus** [comment]
Well I've been investigating this further and the "myth" of changing from game pak save to memory/controller pak save can be considered busted, it doesn't work at all as it still freezes.

When I tested this out it didn't freeze the first time, it didn't freeze the second time but it froze the third time unfortunately just when I was about to think it were true.

So apparently the freezing doesn't seem to be related to saves at all.

As I said earlier this is an issue that goes back way back when and most of you have probably heard or read about it at some point in time.

**Comment by SigmaVirus** [comment]
Changing between the different CPU core types (dynamic_recompiler, cached_interpreter, pure_interpreter) doesn't seem to make any difference at all.

There's really not much else that I can try at this point, at least not that I can think of.

**Comment by SigmaVirus** [comment]
I'm still having these problems as of today, sure it's not a big problem and the game is beatable but I'll just have to live with it so I'll close this issue.

**Comment by loganmc10** [comment]
Have you tested this recently? I just tested the 1st level 4 times in a row (deleting all save files each time) and it never froze after I hit accept.

**Comment by SigmaVirus** [comment]
@loganmc10 

That's interesting, it's been a while since I tried something newer than what I had back then but I gave up on Perfect Dark since it always froze on me occasionally after some levels.

So you're saying that it's not happening for you, have there been any major work or progress made to the Mupen64Plus core since I closed this in February?

As far as I know this is still a problem in Project64.

**Comment by loganmc10** [comment]
> have there been any major work or progress made to the Mupen64Plus core since I closed this in February?

Yes there have been quite a few changes to mupen64plus-core since February, there was nothing done specifically to address this issue, but there have been a number of accuracy improvements. I could have just been lucky, but I haven't run into this for a while

**Comment by SigmaVirus** [comment]
OK, I have to try your m64p project out some time and see if it's fixed and if it's fixed then thank god!
