### ISSUE TITLE
OSD should support OpenGL core profile

### ISSUE THREAD

**Issue by loganmc10** [mupen64plus/mupen64plus-core#193]
As you are probably aware, the OSD needs to be re-written to support the OpenGL core profile.

Relevant related issues:

https://github.com/loganmc10/GLideN64/issues/1
#160

**Comment by wareya** [comment]
I have an incomplete core profile OSD here: https://github.com/wareya/mupen64plus-core/commit/b3f6a2f8a9c53eada4dc65d0ba5d6f9a951faf0e

It replaces the existing text renderer with SDL_TTF and adds gl3w to interface with modern GL.

**Comment by Narann** [comment]
@wareya thanks, it also seems to break the compatibility mode right?

**Comment by wareya** [comment]
Compatibility profile is the one place that both OSDs would work.

However, openGL drives *DO NOT* need to support compatibility profile in any meaningful way.

If you mean old GL (e.g. GL 2), yes, it won't work there, and there's no fixing it. A mupen64plus supporting an OSD on both old and new GL would either need to somehow implement the OSD without using low level GL, or have two OSDs in it.

**Comment by loganmc10** [comment]
Also it's not just whether the device supports the compatibility profile, if the graphics plugin requests a core profile then compatibility code in the OSD isn't going to work, even if the device supports it.

**Comment by wareya** [comment]
And graphics plugins *have to* request a core profile if they want to work on standard modern opengl.

**Comment by loganmc10** [comment]
In my opinion: the OSD should just support the core profile, leave GL2 behind. It doesn't even need to support GLES2, GLES2 devices like the Raspberry Pi are already happily running with --no-osd

**Comment by wareya** [comment]
The issue is the default video plugin still only supports GL2, and any reasonable consumer 3D program. especially an emulator, is still expected to support GL2.

Honestly, I think that the OSD should just, *somehow*, piggyback off of the video plugin's 3D support. But it might be too late to add that kind of thing to the video API.
