### ISSUE TITLE
Add custom ini support 

### ISSUE THREAD

**Issue by orbea** [mupen64plus/mupen64plus-core#217]
Could mupen64plus support loading a custom ini if they are provided by a plugin? For example in GLideN64 there is GLideN64.custom.ini which some games will not work properly unless its used. Various projects like projectj64, mupen64plus-ae and etc are already implementing their own custom ini loader, but maybe this should be implemented in mupen64plus itself so everyone can benefit?

Please read this issue for more information.
https://github.com/gonetz/GLideN64/issues/1271

**Comment by richard42** [comment]
It's kind of out of control already.  The video-rice plugin has an INI reader.  The video-glide64mk2 has one.  The input plugin has one.  The core has 2 (one for cheats and one for per-game hacks). It's not really a terribly difficult thing to write, and GlideN64 already has one, so it seems like the best thing for them to do would be to convert their custom.ini file to be in the same format that their existing INI file reader handles, and then use that.

If their requirements are very simple and this file could be read with the same INI handler that we're using for the per-game hacks (ie, just section names in brackets and equals-sign-separated key/value pairs) then I suppose we could provide an API (maybe in the Config handler) to parse INI files and support some querying by the plugins.  It would be nice to get rid of the handlers in the other plugins and use a common one in the core as well, but it is sort of wasted work.  I mean, it would be nice and all from a code simplicity standpoint, but it wouldn't bring us anything that we don't already have.

**Comment by orbea** [comment]
I can totally see where you are coming from, but on the other hand given that this can lead to unexpected configuration issues it would be really nice that this it is solved. That said either you guys or the various plugin developers will have to give, it would probably be ultimately less work in the long run to do it once in the core than reinvent it again and again in the plugins. However in the short term it will be less work for each plugin to do it.

**Comment by gonetz** [comment]
> GlideN64 already has one

Already has not. GLideN64 uses external ini parsers: QT for Zilmar spec build, Mupen64Plus API for Mupen64Plus build. I don't want to add yet another ini parser. I think, it will be better to add just one API function ConfigOpenFile to open external config file and work with it as with regular Mupen64Plus configuration.

**Comment by Papermanzero** [comment]
If Mupen64Plus builts upon an external plugin system a functionality to open configs is necessary.
If Mupen64Plus aims to integrate "main" plugins (like audio and input) to become a "complete" and "consistent" emulator, the implementation of an overall API to open config is not needed. In this case Mupen64Plus only open its own config. 

So it depends what the future goal of mupen64plus is. As I understood so far, the vision of the mupen64plus team is to have a N64 emulator which does not rely on plugins.

**Comment by loganmc10** [comment]
This was recently merged, so this is fixed now
