### ISSUE TITLE
World Driver Championship | Video Error: Error: Unsupported uCode! crc: 844b55b5

### ISSUE THREAD

**Issue by FeralBytes** [mupen64plus/mupen64plus-core#222]
Mupen64Plus developers, I have a bug for a game that happens to be one of my favorites. I would like to hunt this down and fix it but with your guidance. I know near nothing about mupen64plus, but I am a programmer and will likely be able to figure out enough once I have some guidance.
So my initial questions are: where in mupen are the uCode's handled? How does the LLE system work? I will probably try to figure out what project64 did to handle this and implement a similar fix. 
Thanks for your guidance.
```
wolfrage@wolfrage-700-210xt ~ $ /opt/retropie/emulators/mupen64plus/bin/mupen64plus --configdir /home/wolfrage/roms/configs/ /home/wolfrage/roms/n64/World\ Driver\ Championship\ \(U\)\ \[\!\].z64 
 __  __                         __   _  _   ____  _             
|  \/  |_   _ _ __   ___ _ __  / /_ | || | |  _ \| |_   _ ___ 
| |\/| | | | | '_ \ / _ \ '_ \| '_ \| || |_| |_) | | | | / __|  
| |  | | |_| | |_) |  __/ | | | (_) |__   _|  __/| | |_| \__ \  
|_|  |_|\__,_| .__/ \___|_| |_|\___/   |_| |_|   |_|\__,_|___/  
             |_|         http://code.google.com/p/mupen64plus/  
Mupen64Plus Console User-Interface Version 2.5.0

UI-Console: attached to core library 'Mupen64Plus Core' version 2.5.0
UI-Console:             Includes support for Dynamic Recompiler.
Core: Goodname: World Driver Championship (U) [!]
Core: Name: WORLD DRIVER CHAMP  
Core: MD5: 7C567A5BB1AD4CBE414FB6BBFF66E336
Core: CRC: 308DFEC8 CE2EB5F6
Core: Imagetype: .z64 (native)
Core: Rom size: 16777216 bytes (or 16 Mb or 128 Megabits)
Core: Version: 1449
Core: Manufacturer: Nintendo
Core: Country: USA
UI-Console Status: Cheat codes disabled.
UI-Console: using Video plugin: 'Glide64mk2 Video Plugin' v2.5.0
UI-Console: using Audio plugin: 'Mupen64Plus SDL Audio Plugin' v2.5.0
UI-Console: using Input plugin: 'Mupen64Plus SDL Input Plugin' v2.5.0
UI-Console: using RSP plugin: 'Hacktarux/Azimer High-Level Emulation RSP Plugin' v2.5.0
Video: opening /opt/retropie/configs/n64/Glide64mk2.ini

INI_FindSection trying to find name for DEFAULT
Video: 3DNOW! detected.

Input: 0 SDL joysticks were found.
Input: N64 Controller #1: Using manual config for SDL joystick 0
Input: N64 Controller #2: Using manual config for SDL joystick 1
Input: N64 Controller #3: Using manual config for SDL joystick 2
Input: N64 Controller #4: Using manual config for SDL joystick 3
Input: 4 controller(s) found, 4 plugged in and usable in the emulator
Input Warning: Couldn't open joystick for controller #1: There are 0 joysticks available
Input Warning: Couldn't open rumble support for joystick #1
Input Warning: Couldn't open joystick for controller #2: There are 0 joysticks available
Input Warning: Couldn't open rumble support for joystick #2
Input Warning: Couldn't open joystick for controller #3: There are 0 joysticks available
Input Warning: Couldn't open rumble support for joystick #3
Input Warning: Couldn't open joystick for controller #4: There are 0 joysticks available
Input Warning: Couldn't open rumble support for joystick #4
Input: Mupen64Plus SDL Input Plugin version 2.5.0 initialized.
Core Status: Selected state slot: 9
INI_FindSection trying to find name for DEFAULT
INI_FindSection trying to find name for WORLD DRIVER CHAMP
Could not find [WORLD DRIVER CHAMP] section in INI file!Video: Using TEXUMA extension.

&ConfigOpenSection is 0x7f9292bc6d98
(II) Setting video mode 1920x1080...
Core: Setting video mode: 1920x1080
Congratulations, you have 4 auxilliary buffers, we'll use them wisely !
packed pixels extension used
NPOT extension used
use_fbo 1
Video: InitCombine() 
Video: extensions 
Video: initialized.
Video: 

Audio: Initializing SDL audio subsystem...
Input Warning: Couldn't open joystick for controller #1: There are 0 joysticks available
Input Warning: Couldn't open rumble support for joystick #1
Input Warning: Couldn't open joystick for controller #2: There are 0 joysticks available
Input Warning: Couldn't open rumble support for joystick #2
Input Warning: Couldn't open joystick for controller #3: There are 0 joysticks available
Input Warning: Couldn't open rumble support for joystick #3
Input Warning: Couldn't open joystick for controller #4: There are 0 joysticks available
Input Warning: Couldn't open rumble support for joystick #4
Core: Starting R4300 emulator: Dynamic Recompiler
Core: R4300: starting 64-bit dynamic recompiler at: 0x7f929e94e190
INI_FindSection trying to find name for UCODE
Video Error: Error: Unsupported uCode!

crc: 844b55b5
^CCore Status: Stopping emulation.
Core: R4300 emulator finished.
Core Status: Rom closed.


###### RUN 2

wolfrage@wolfrage-700-210xt ~ $ /opt/retropie/emulators/mupen64plus/bin/mupen64plus --configdir /home/wolfrage/roms/configs/ /home/wolfrage/roms/n64/World\ Driver\ Championship\ \(USA\).n64 
 __  __                         __   _  _   ____  _             
|  \/  |_   _ _ __   ___ _ __  / /_ | || | |  _ \| |_   _ ___ 
| |\/| | | | | '_ \ / _ \ '_ \| '_ \| || |_| |_) | | | | / __|  
| |  | | |_| | |_) |  __/ | | | (_) |__   _|  __/| | |_| \__ \  
|_|  |_|\__,_| .__/ \___|_| |_|\___/   |_| |_|   |_|\__,_|___/  
             |_|         http://code.google.com/p/mupen64plus/  
Mupen64Plus Console User-Interface Version 2.5.0

UI-Console: attached to core library 'Mupen64Plus Core' version 2.5.0
UI-Console:             Includes support for Dynamic Recompiler.
Core: Goodname: World Driver Championship (U) [!]
Core: Name: WORLD DRIVER CHAMP  
Core: MD5: 7C567A5BB1AD4CBE414FB6BBFF66E336
Core: CRC: 308DFEC8 CE2EB5F6
Core: Imagetype: .v64 (byteswapped)
Core: Rom size: 16777216 bytes (or 16 Mb or 128 Megabits)
Core: Version: 1449
Core: Manufacturer: Nintendo
Core: Country: USA
UI-Console Status: Cheat codes disabled.
UI-Console: using Video plugin: 'Glide64mk2 Video Plugin' v2.5.0
UI-Console: using Audio plugin: 'Mupen64Plus SDL Audio Plugin' v2.5.0
UI-Console: using Input plugin: 'Mupen64Plus SDL Input Plugin' v2.5.0
UI-Console: using RSP plugin: 'Hacktarux/Azimer High-Level Emulation RSP Plugin' v2.5.0
Video: opening /opt/retropie/configs/n64/Glide64mk2.ini

INI_FindSection trying to find name for DEFAULT
Video: 3DNOW! detected.

Input: 0 SDL joysticks were found.
Input: N64 Controller #1: Using manual config for SDL joystick 0
Input: N64 Controller #2: Using manual config for SDL joystick 1
Input: N64 Controller #3: Using manual config for SDL joystick 2
Input: N64 Controller #4: Using manual config for SDL joystick 3
Input: 4 controller(s) found, 4 plugged in and usable in the emulator
Input Warning: Couldn't open joystick for controller #1: There are 0 joysticks available
Input Warning: Couldn't open rumble support for joystick #1
Input Warning: Couldn't open joystick for controller #2: There are 0 joysticks available
Input Warning: Couldn't open rumble support for joystick #2
Input Warning: Couldn't open joystick for controller #3: There are 0 joysticks available
Input Warning: Couldn't open rumble support for joystick #3
Input Warning: Couldn't open joystick for controller #4: There are 0 joysticks available
Input Warning: Couldn't open rumble support for joystick #4
Input: Mupen64Plus SDL Input Plugin version 2.5.0 initialized.
Core Status: Selected state slot: 9
INI_FindSection trying to find name for DEFAULT
INI_FindSection trying to find name for WORLD DRIVER CHAMP
Could not find [WORLD DRIVER CHAMP] section in INI file!Video: Using TEXUMA extension.

&ConfigOpenSection is 0x7faccefebd98
(II) Setting video mode 1920x1080...
Core: Setting video mode: 1920x1080
Congratulations, you have 4 auxilliary buffers, we'll use them wisely !
packed pixels extension used
NPOT extension used
use_fbo 1
Video: InitCombine() 
Video: extensions 
Video: initialized.
Video: 

Audio: Initializing SDL audio subsystem...
Input Warning: Couldn't open joystick for controller #1: There are 0 joysticks available
Input Warning: Couldn't open rumble support for joystick #1
Input Warning: Couldn't open joystick for controller #2: There are 0 joysticks available
Input Warning: Couldn't open rumble support for joystick #2
Input Warning: Couldn't open joystick for controller #3: There are 0 joysticks available
Input Warning: Couldn't open rumble support for joystick #3
Input Warning: Couldn't open joystick for controller #4: There are 0 joysticks available
Input Warning: Couldn't open rumble support for joystick #4
Core: Starting R4300 emulator: Dynamic Recompiler
Core: R4300: starting 64-bit dynamic recompiler at: 0x7facdad73190
INI_FindSection trying to find name for UCODE
Video Error: Error: Unsupported uCode!

crc: 844b55b5
^CCore Status: Stopping emulation.
Core: R4300 emulator finished.
Core Status: Rom closed.


```

**Comment by FeralBytes** [comment]
Following the directions from here: [mupen64plus debugging](https://github.com/mupen64plus/mupen64plus-core/issues/162#issuecomment-244819902)

I ran GDB and the game actually starts but only displays the first frame before freezing, here is the output from the GDB session.
```
gdb --args ./mupen64plus --emumode 0 --windowed --audio dummy /home/wolfrage/tmp/World\ Driver\ Championship\ \(U\)\ \[\!\].z64
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.04) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./mupen64plus...done.
(gdb) break pthread_exit
Function "pthread_exit" not defined.
Make breakpoint pending on future shared library load? (y or [n]) y
Breakpoint 1 (pthread_exit) pending.
(gdb) run
Starting program: /home/wolfrage/tmp/mupen64plus/test/mupen64plus --emumode 0 --windowed --audio dummy /home/wolfrage/tmp/World\ Driver\ Championship\ \(U\)\ \[\!\].z64
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
 __  __                         __   _  _   ____  _             
|  \/  |_   _ _ __   ___ _ __  / /_ | || | |  _ \| |_   _ ___ 
| |\/| | | | | '_ \ / _ \ '_ \| '_ \| || |_| |_) | | | | / __|  
| |  | | |_| | |_) |  __/ | | | (_) |__   _|  __/| | |_| \__ \  
|_|  |_|\__,_| .__/ \___|_| |_|\___/   |_| |_|   |_|\__,_|___/  
             |_|         http://code.google.com/p/mupen64plus/  
Mupen64Plus Console User-Interface Version 2.5.0

UI-Console: attached to core library 'Mupen64Plus Core' version 2.5.0
UI-Console:             Includes support for Dynamic Recompiler.
Core: Couldn't open configuration file '/home/wolfrage/.config/mupen64plus/mupen64plus.cfg'.  Using defaults.
Core Warning: No version number in 'Core' config section. Setting defaults.
Core Warning: No version number in 'CoreEvents' config section. Setting defaults.
[New Thread 0x7fffee1a4700 (LWP 8468)]
UI-Console Warning: No version number in 'UI-Console' config section. Setting defaults.
Core: Goodname: World Driver Championship (U) [!]
Core: Name: WORLD DRIVER CHAMP  
Core: MD5: 7C567A5BB1AD4CBE414FB6BBFF66E336
Core: CRC: 308DFEC8 CE2EB5F6
Core: Imagetype: .z64 (native)
Core: Rom size: 16777216 bytes (or 16 Mb or 128 Megabits)
Core: Version: 1449
Core: Manufacturer: Nintendo
Core: Country: USA
UI-Console Status: Cheat codes disabled.
Video Warning: No version number in 'Rice-Video' config section. Setting defaults.
Video Warning: Old parameter config version detected : 0, updating to 1;
UI-Console: using Video plugin: 'Mupen64Plus OpenGL Video Plugin by Rice' v2.5.0
UI-Console: using Audio plugin: <dummy>
Input Warning: Missing or incompatible config section 'Input-SDL-Control1'. Clearing.
Input Warning: Missing or incompatible config section 'Input-SDL-Control2'. Clearing.
Input Warning: Missing or incompatible config section 'Input-SDL-Control3'. Clearing.
Input Warning: Missing or incompatible config section 'Input-SDL-Control4'. Clearing.
Input: Using auto-config file at: 'InputAutoCfg.ini'
UI-Console: using Input plugin: 'Mupen64Plus SDL Input Plugin' v2.5.0
UI-Console: using RSP plugin: 'Hacktarux/Azimer High-Level Emulation RSP Plugin' v2.5.0
Input: 0 SDL joysticks were found.
Input: N64 Controller #1: Forcing default keyboard configuration
Input: Using auto-config file at: 'InputAutoCfg.ini'
Input: 1 controller(s) found, 1 plugged in and usable in the emulator
Input Warning: Couldn't open rumble support for joystick #1
Input Warning: Couldn't open rumble support for joystick #2
Input Warning: Couldn't open rumble support for joystick #3
Input Warning: Couldn't open rumble support for joystick #4
Input: Mupen64Plus SDL Input Plugin version 2.5.0 initialized.
Core Warning: No audio plugin attached.  There will be no sound output.
Video: SSE processing enabled.
Video: Found ROM 'WORLD DRIVER CHAMP', CRC c8fe8d30f6b52ece-45
Video: Initializing OpenGL Device Context.
Core: Setting 32-bit video mode: 640x480
Video Warning: Failed to set GL_SWAP_CONTROL to 0. (it's 24)
Video Warning: Failed to set GL_BUFFER_SIZE to 32. (it's 24)
Video Warning: Failed to set GL_DEPTH_SIZE to 16. (it's 24)
Video: Using OpenGL: GeForce GTX 950M/PCIe/SSE2 - 4.5.0 NVIDIA 367.57 : NVIDIA Corporation
Input Warning: Couldn't open rumble support for joystick #1
Input Warning: Couldn't open rumble support for joystick #2
Input Warning: Couldn't open rumble support for joystick #3
Input Warning: Couldn't open rumble support for joystick #4
Core: Starting R4300 emulator: Pure Interpreter
^Z
Thread 1 "mupen64plus" received signal SIGTSTP, Stopped (user).
0x00007ffff7bcac1d in nanosleep () at ../sysdeps/unix/syscall-template.S:84
84	../sysdeps/unix/syscall-template.S: No such file or directory.
(gdb) thread apply all bt

Thread 2 (Thread 0x7fffee1a4700 (LWP 8468)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007ffff4fe2cbe in ?? () from /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0
#2  0x00007ffff56a9747 in workqueue_get_work (thread=<optimized out>)
    at ../../src/main/workqueue.c:70
#3  workqueue_thread_handler.lto_priv.1003 (data=0x63a9a0) at ../../src/main/workqueue.c:87
#4  0x00007ffff4f9409c in ?? () from /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0
#5  0x00007ffff4fe2399 in ?? () from /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0
#6  0x00007ffff7bc16ba in start_thread (arg=0x7fffee1a4700) at pthread_create.c:333
#7  0x00007ffff78f782d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 1 (Thread 0x7ffff7fca700 (LWP 8460)):
#0  0x00007ffff7bcac1d in nanosleep () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007ffff4fe68b5 in ?? () from /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0
#2  0x00007ffff568ba3b in apply_speed_limiter () at ../../src/main/main.c:777
#3  new_vi () at ../../src/main/main.c:824
#4  vi_vertical_interrupt_event (vi=<optimized out>) at ../../src/vi/vi_controller.c:144
#5  gen_interupt () at ../../src/r4300/interupt.c:548
#6  0x00007ffff5681b15 in BEQ_IDLE (op=268500991) at ../../src/r4300/interpreter_r4300.def:24
#7  InterpretOpcode.lto_priv.929 () at ../../src/r4300/pure_interp.c:401
#8  0x00007ffff56a1709 in pure_interpreter () at ../../src/r4300/pure_interp.c:739
#9  r4300_execute () at ../../src/r4300/r4300.c:199
#10 main_run () at ../../src/main/main.c:1006
#11 0x00007ffff567bd80 in CoreDoCommand (Command=<optimized out>, ParamInt=0, ParamPtr=0x0)
    at ../../src/api/frontend.c:214
#12 0x0000000000402e09 in main (argc=<optimized out>, argv=<optimized out>) at ../../src/main.c:782
(gdb) 
```

**Comment by FeralBytes** [comment]
I was saying that the game was freezing but then again I am unsure going to test with no sound and see if it advances. Also I am Running Linux Mint 18 (Ubuntu 16.04) x64.

**Comment by FeralBytes** [comment]
Nope still crashes with audio = dummy; so next step is to pull from git on my steam-link machine and run the git-hub version from there with the controller enabled to see if the game advances or crashes; then if it crashes to debug that.

**Comment by FeralBytes** [comment]
So some further testing reveals that the Game Starts, the first frame is drawn to the screen. Then the CPU gets used a bunch likely initial warm up of the emulator Core; but the game is basically frozen; although I can still use "P" to pause and continue and I can use the numbers on the keyboard to change the selected state slot; but changing the selected state slot results in the screen getting the white text smeared to the point of being unreadable. However with the latest version from git-hub I no longer get an immediate crash; unless I apply the additional settings that seem to be default for Raspberry PI; although again I was just taking those default settings from the Raspberry PI project to setup my emulators on Linux Mint 18. But currently if I run mupen64plus with no additional settings the freeze happens. 
So at this time I would like some feedback from the developers as to how I should continue to troubleshoot. Thanks for your time and help.

**Comment by bsmiles32** [comment]
As shown in your logs, the graphical ucode for WDC is not implemented. This means that unless you reverse engineer it and implement it (either un rsp-hle or one of the gfx plugin) you won't be able to play this game in HLE. You might be able to go a little bit further with rsp-cxd4 and an lle gfx plugin, but from what I remember there are still some bugs that prevents correct execution of both CPU and rsp. If you are not intimetly familiar with the inner workings of the n64 this might not be the easiest bug to fix.

**Comment by FeralBytes** [comment]
@bsmiles32 Can you please define a few things for me. HLE, rsp, cxd, lle. I understand that rsp and gfx are different view ports that output the emulation but not precisely what they are. I also gather that LLE is a sort of plug-in architecture to handle certain use cases such as uCode. I am familiar with disassembly; but not reverse engineering. I definitely am not familiar with the inner workings of the N64; but I really like this game and although it will likely take me months to understand enough to try to fix it; I am willing to invest my time; just need some helpful pointers in the right direction so that I am diving down the right rabbit holes. I assume that disassembly could help me to at-least figure out what the uCode is; or is there an easier way to get mupen to print out the exact value. Any or all of these assumptions may be incorrect please let me know how far off base I am.
Also something that I still find odd; is the older version of mupen64 from retropie threw the uCode error; but the new version of from github did not throw the error it just freezes; why is this?

**Comment by bsmiles32** [comment]
HLE is High Level Emulation, it means emulating a system without necessarily reproducing its internal working. It is opposed to LLE, Low Level Emulation, which is another approach where you repoduce the internal working of the system. In this context I was talking about the RSP, the processor used in the N64 to do various vectorial operations such as vertex processings or sound synthesis. The LLE approach for this processor would be to emulate each instructions of this processor, which is what the mupen64plus-rsp-cxd4 plugin does. On the other end, an HLE approach would be not to emulate each instructions, but recognizing what program (called a ucode) the RSP is executing and executing an equivalent reimplementation. This is what mupen64plus-rsp-hle does. In fact, this also applies to the emulation of the RDP, the N64 rasterizing processor, which is usually done with an HLE approach (mupen64plus-video-{rice,glid64,glide64mk2}). Some plugins however such as mupen64plus-video-z64 emulate the RDP with an LLE approach.

World Driver Championship (and Stunt Racer) uses a "customised" version of the "ZSort" ucode. This ucode basically takes z-sorted lists of triangles/rectangles and translates these into Display Lists suitable for the RDP. The problem is that no one has reverse engineereed this ucode, so HLE emulation of it is not possible, hence your error. But using both an LLE RSP and video plugins could avoid this. However, as I was saying there is a problem with how mupen64plus schedules RSP execution, which makes this game not playable with LLE.

Not to deter you from doing what you want but reverse engineering a ucode takes a LOT of time : I've spent almost 1 year to reverse engineer the "musyx" ucode (sound synthesis for few games) and I'm very familiar with how the RSP works and it was not my first reverse engineering project either. Sure you'll learn a lot in the process, but the sole fact that you ask these kind of questions makes me think that your time would be better spent on other part of the project (if that interest you of course).

If you still want to proceed, you first need to obtain a dump of the ucode. You can recompile the mupen64plus-rsp-hle plugins with ENABLE_TASK_DUMP flag to help you obtain such a dump. Once acquired you will need to disassemble it. You can use radare2 for that. You need to understand the structure of the ucode and data layouts, document it and then reimplement something equivalent in C. And that takes time and dedication because at this point your on your own...

**Comment by FeralBytes** [comment]
OK just 2 more questions and I will leave you alone. 1: How do I run muppen64plus using an LLE? 2: Is it OK if I gather my research and notes into this bug report or would you rather it all stay off-line?

I am trying to figure out the LLE portion on my own; but I see there are many; I am about to git clone z64, glide64, and rsp-cdx4 to test them; but I am just not sure of the standard way to launch the different plug-ins; documentation on mupen is a little rough (sorry). I assume all via the configuration script. Thanks for your descriptions and help. Also my preliminary research does show I have a uphill battle ahead of me, but I like learning and I learned a lot the first time I disassembled with radare2 so I look forward to using it again.

**Comment by bsmiles32** [comment]
1: provided that you have the LLE plugins installed, run mupen64plus --rsp mupen64plus-rsp-cxd4 --gfx mupen64plus-video-z64
You can also specify full paths for the plugins.
Alternatively, you can edit the mupen64plus configuration file.

2: I think you should gather your notes offline, and when you have a part ready you can post some progress here.

Also if you want to practice ucode reverse engineering you can take a look at other already implemented ucode such as JPEG ones or audio ones. Or for a less ambitious ucode not yet reverse engineereed you can look the pokemon stadium gbtower ucode (contains mostly non RSP specific opcodes) or maybe try to implement some missing commands in audio ucode.

**Comment by loganmc10** [comment]
> However, as I was saying there is a problem with how mupen64plus schedules RSP execution, which makes this game not playable with LLE.

Has any progress on this ever been made? It seems like an attempt was made a while back to fix this issue but it was unsuccessful. Solving this problem would make a number of games playable, and it's something that Project64 has it working.

Is there anything a layman like me can do to help out? Perhaps provide some debugging or try a number of different things? I'm not sure where the code is from the last attempt

**Comment by FeralBytes** [comment]
@Gillou68310 I see you closed it, is this because you fixed it? If so I will test and confirm the fix as I love this old game. Thanks.

**Comment by loganmc10** [comment]
This was never a problem with the emulator, but a function of the graphics plugin. This was solved in GLideN64 (https://github.com/gonetz/GLideN64)

You can compile GLideN64 yourself or try a pre-built version here: https://m64p.github.io
