### ISSUE TITLE
Compilation not producing executable

### ISSUE THREAD

**Issue by knuxyl** [mupen64plus/mupen64plus-core#224]
I compiled mupen64plus-core in Xubuntu 16.04.1 x86_64 and it only creates these files
/home/knuxyl/Desktop/mupen64plus-core-master/projects/unix/_obj
/home/knuxyl/Desktop/mupen64plus-core-master/projects/unix/libmupen64plus.so.2
/home/knuxyl/Desktop/mupen64plus-core-master/projects/unix/libmupen64plus.so.2.0.0
/home/knuxyl/Desktop/mupen64plus-core-master/projects/unix/Makefile

But when I run Mupen64Plus-Qt, in path settings it asks for mupen64plus executable path and it is pointing to usr/games/mupen64plus. I have not been able to compile this file anywhere. I have followed instructions using make all. 
Since this is the core, I'm assuming the executable is not being built. I did not receive any errors during make either. I have all dependencies installed (btw about libpng, I've had this problem with many other programs compiling but I'm guessing the newest one fixed it because I'm not getting problem with it, I didn't have to compile 1.14 from source.)

Also I already have 2.5 installed from Ubuntu repositories which is how I know I'm missing the mupen64plus executable file (2.5 is around 51.4kb)

**Comment by charlemagnelasse** [comment]
The mupen64plus executable is build by mupen64plus-ui-console and not mupen64plus-core.
