### ISSUE TITLE
Ability to set custom RDRAM size

### ISSUE THREAD

**Issue by cascardian** [mupen64plus/mupen64plus-core#225]
This is needed for certain ROM hacks (like [The Last Impact](https://www.youtube.com/watch?v=Ho0CHVAT4jM), e.g.) to be fully functional. A related discussion concerning defaults and methods of implementation can be found here for PJ64: https://github.com/project64/project64/issues/457

**Comment by richard42** [comment]
The DisableExtraMem parameter in the [Core] config section can be used for this.  If this is False, the RDRAM size is 8MB.  If True, it is 4MB.  Some games will use the extra memory, but some games won't run with 8MB.
