### ISSUE TITLE
Input Lag with GFX plugins that have framebuffer emulation (Mario 64)

### ISSUE THREAD

**Issue by loganmc10** [mupen64plus/mupen64plus-core#226]
Hopefully someone with knowledge of the emulator core can help me out with this.

I have received multiple reports of people experiencing input lag with GFX plugins that support framebuffer emulation (angrylion and GLideN64, also happens with ParaLLEl in RetroArch)

https://github.com/GLupeN64/GLupeN64/issues/55
https://github.com/GLupeN64/GLupeN64/issues/156
https://github.com/gonetz/GLideN64/issues/1124

It doesn't happen with less accurate plugins like Rice or Glide64.

These were some comments from gonetz in the GLideN64 issue:

>plugin renders to a buffer, which is not immediately shown. Usually game uses two color buffers - one for rendering, other one displayed on screen. Game swaps buffers when rendering finished. Some games use triple buffering: one buffer for rendering, one waits to be displayed and one displayed on screen. Triple buffering usually use games running at 60 fps.

> VI has address of buffer to show on screen. Thus, if new buffer rendering is finished, but VI commanded to show previous buffer, it will show previous buffer. You may check in debugger, does it happen for Mario 64.

> When fb emulation is off, color buffer address register ignored.

> As I know, problem of timings and synchronizations in emu core is very complex. Probably emulator updates VI origin register too late.

> The lag appears when graphics plugin uses VI origin register, which is updated by emu core.

**Comment by loganmc10** [comment]
You can test this in mupen64plus by using GLideN64 and using the frame advance feature. Pause the game, hold down "jump" in Mario 64, and then advance frames one by one.

With Framebuffer Emulation disabled, Mario is in the air on the 1st frame.

With Framebuffer Emulation enabled, Mario spends 2 frames looking around, and then he is in the air on the 3rd frame.

**Comment by loganmc10** [comment]
In doing some more testing this seems to be a Mario 64 specific problem. I tested Smash Bros and Zelda:OoT and the input delay was the same between Glide64 and GLideN64

**Comment by Tatsuya79** [comment]
It happens with Wave Race too. 5 frames to move that cursor on the title screen.
Same for Rally '99.

Games that use the framebuffer / some particular functions?

**Comment by Tatsuya79** [comment]
Same input lag with Project64 2.3.2.202 and GlideN64 2.0 on windows 7 x64.

Tested with Wave Race: the difference with or without Frame Buffer activated is evident on the title screen.

**Comment by fzurita** [comment]
Has anyone measured this in the real console?

**Comment by loganmc10** [comment]
I seem to recall somebody plugged their computer into a CRT and tested a real N64 on the same CRT, and said the difference was noticable, but I don't think any measurements have been done using any kind of instruments.

**Comment by loganmc10** [comment]
I'm going to close this until/unless someone can verify what the proper behavior on a console should be.

**Comment by loganmc10** [comment]
Somebody did get around to testing this on real hardware:

https://www.reddit.com/r/emulation/comments/68tgzq/i_just_measured_input_lag_of_a_real_snes_on_a_crt/dh1qurf/

Their testing confirms that the input lag was present on the real console, so this isn't an issue.

**Comment by wareya** [comment]
Take it with a grain of salt. The original system generally has 2.0 frames of added input lag, from three variables:

* The vscan time (the middle of the screen is updated ~0.5 frames in)
* The refresh rate (an update lasts for 1.0 frames, adding 0.5 frames of average latency)
* The frame time (the time between taking inputs and pushing them to the screen; generally, but not always, 1.0 frames on real hardware)

An ideal emulator knocks out points 1 and 3.

**Comment by loganmc10** [comment]
@wareya here we aren't talking about how long a frame takes to be drawn, but rather how many frames there are between receiving input, and the game reacting to the input. I guess we are talking about the "frame time".

And on the N64 the "frame time", it is definitely not consistently 1 frame, there are some games, especially in the menus, that will wait like 6 frames before reacting to input. Each game is different as well, with some games waiting longer between input and drawing than others.

**Comment by wareya** [comment]
Yes, that's right. A lot of games accidentally add unnecessary input lag to inputs. But if you see an increase in the number of frames between input and output when you change a certain emulation setting, there's a good chance that emulation setting is doing something funny somewhere, even if the more latent setting is closer to real hardware.

**Comment by Tasosgemah** [comment]
This isn't the same as the real console. I have a PAL Mario 64 and it _feels_ significantly faster than any core in RetroArch right now. The only core that was close to the real console was the original Mupen 64 core.
