### ISSUE TITLE
Saving sate cause retroarch to crash

### ISSUE THREAD

**Issue by medwatt** [mupen64plus/mupen64plus-core#244]
I'm using **Mupen64Plus OpenGL 2.5 938277a** in **RetroArch 1.4.1**. Games can be loaded and played normally. However, if I try to do 'Save State', Retroarch crashes. This does not happen with other cores.

**Comment by richard42** [comment]
It's a libretro bug; you need to file it with them.  Save states work fine in our console front-end application.
