### ISSUE TITLE
How to run in Fedora?

### ISSUE THREAD

**Issue by metaleap** [mupen64plus/mupen64plus-core#247]
I did "the usual procedure under non-Ubuntu Linux":

- extract tar archive
- `sudo mv mupen64plus-bundle-linux64-2.5 /opt/`
- `sudo ln -s /opt/mupen64plus-bundle-linux64-2.5/mupen64plus /usr/bin/mupen64`

Running `mupen64` I get:

    UI-Console Error: dlopen('/usr/local/lib/libmupen64plus.so.2') failed: /usr/local/lib/libmupen64plus.so.2: cannot open shared object file: No such file or directory
    UI-Console Error: dlopen('./libmupen64plus.so.2') failed: ./libmupen64plus.so.2: cannot open shared object file: No such file or directory
    UI-Console Error: AttachCoreLib() Error: failed to find Mupen64Plus Core library

Should I copy everything over to /usr/local/lib too? I'm on Fedora so the prebuilt Ubuntu package I gather won't work.. or is there some install.sh or such I haven't noticed?

The docs seem to go wild about "plugins" and "core params" and "frontends" and whatever all that is (I was imagining a simplistic "here's a .rom now run it in fullscreen and *done*" sorta app lol), but simply installing on non-Ubuntu unices I can't seem to figure out, any pointers appreciated!

**Comment by Jj0YzL5nvJ** [comment]
The install.sh script file don't do the trick? Is ldconfig installed?

If you want to compile yourself, [here are plenty of examples](https://github.com/mupen64plus/mupen64plus-core/tree/master/tools).

You can use these scripts as a template to create your own...

**Comment by metaleap** [comment]
Don't recall what I did but got it working by now =)
