### ISSUE TITLE
Missing textures and incorrect placement in Star Wars: Shadows of the Empire

### ISSUE THREAD

**Issue by pedrib** [mupen64plus/mupen64plus-core#248]
Star Wars: Shadows of the Empire runs relatively well with the default settings, but on level 4 it has some glaring errors.
First, the protagonist is cut from the knees below.
Second, it's not very visible in the screenshots but there are some missing textures on the sides of the railway.

Using the rice plugin makes the graphics somewhat better, but there is heavy flickering making it unplayable.

Using Debian testing amd64 with an i5-3320m and HD4000.
![default1](https://cloud.githubusercontent.com/assets/5311656/23484043/28891ce6-fecd-11e6-9dbc-cbf0bcb63aca.png)
![default2](https://cloud.githubusercontent.com/assets/5311656/23484042/28878052-fecd-11e6-91eb-23b7c6c22b2b.png)
![rice1](https://cloud.githubusercontent.com/assets/5311656/23484044/288a4bfc-fecd-11e6-97d9-241063c00652.png)
![rice2](https://cloud.githubusercontent.com/assets/5311656/23484045/288b9d36-fecd-11e6-8c6c-fee45eecfc75.png)

**Comment by pedrib** [comment]
First two screenshots are the default, third and fourth are using rice.

**Comment by loganmc10** [comment]
GLideN64 (https://github.com/gonetz/GLideN64) is probably the most accurate OpenGL video plugin available right now, you would have to compile it from source, I don't believe any Linux binaries are distributed:

https://github.com/gonetz/GLideN64/wiki/Build-From-Source-(Linux)#initial-setup

**Comment by pedrib** [comment]
@loganmc10 I've built libretro from source, isn't the plugin included automatically?

**Comment by loganmc10** [comment]
@pedrib this repository has nothing to do with libretro, if you're using libretro you'll need to file a bug report with them.

**Comment by pedrib** [comment]
@loganmc10 you are right, my bad. I mixed up both emulators. I see that you also created GLupeN64, I'm going to try that instead.
