### ISSUE TITLE
Compilation fix for SDL2 from homebrew on Mac for plugins

### ISSUE THREAD

**Issue by fprimex** [mupen64plus/mupen64plus-core#251]
Hopefully this issue is appropriate here as my question/patches apply to multiple plugins, but not all plugin repos have Github issues enabled.

As in my earlier ticket, I'm working on MacOS support. I decided to pull nasm and SDL2 from [homebrew](https://brew.sh), which supplied version 2.0.5 in a non-framework manner. During builds, I encountered the following error for `mupen64plus-audio-sdl`, `mupen64plus-input-sdl`, and `mupen64plus-ui-console`:

```
/usr/local/include/SDL2/SDL_platform.h:87:3: error: SDL for Mac OS X only supports deploying on 10.6 and above.
```

The solution is to bump `-mmacosx-version-min=10.5` to `-mmacosx-version-min=10.6` in the three plugins' `projects/unix/Makefile`s. I can supply PRs or you can grab patches from [here](https://github.com/m64p/mupen64plus-gui/issues/9#issuecomment-284752008) or you can just bump them manually; there are only a few.

I feel this is an OK solution, given the age of OSX 10.5. The latest, Sierra, is 10.12.

**Comment by Gillou68310** [comment]
I agree I think we can safely drop 10.5 compatibility. Don't hesitate to open a PR for this ;-)

**Comment by fprimex** [comment]
* [Done](https://github.com/mupen64plus/mupen64plus-audio-sdl/pull/14)
* [Done](https://github.com/mupen64plus/mupen64plus-input-sdl/pull/41)
* [And Done](https://github.com/mupen64plus/mupen64plus-ui-console/pull/28)
