### ISSUE TITLE
Compile fails on src Linux Armv7l

### ISSUE THREAD

**Issue by aperfeito** [mupen64plus/mupen64plus-core#252]
In file included from /usr/include/features.h:392:0,
                 from /usr/include/stdint.h:25,
                 from /usr/lib/gcc/armv7l-unknown-linux-gnueabihf/6.3.1/include/stdint.h:9,
                 from ../../src/ai/ai_controller.h:26,
                 from ../../src/ai/ai_controller.c:22:
/usr/include/gnu/stubs.h:7:29: fatal error: gnu/stubs-soft.h: No such file or directory
 # include <gnu/stubs-soft.h>
compilation terminated.
make: *** [Makefile:666: _obj/ai/ai_controller.o] Error 1
make: Leaving directory '/home/aperfeito/Downloads/mupen64plus-bundle-src-2.5/source/mupen64plus-core/projects/unix'

**Comment by loganmc10** [comment]
You need to compile like:

```make VFP_HARD=1 -j4 all```

**Comment by aperfeito** [comment]
Logan,


                When you use Mupen64plus-core compiled itself is ok with this like you said.


     But When you use the mupen64plus-bundle-src-2.5 in the script file m64p_build.sh in the line 51 I force EDIT MYSELF this:


              "$MAKE" -C source/mupen64plus-${component}/projects/unix VFP_HARD=1 -j4 all $@


                Because otherwise CRASH compiled .


       and even this  when comes to compile mupen64plus-video-glide64mk2 plugin see whats happend



************************************ Building video-glide64mk2 plugin
make: Entering directory '/home/aperfeito/Downloads/mupen64plus-bundle-src-2.5/source/mupen64plus-video-glide64mk2/projects/unix'
Makefile:117: Architecture "armv7l" not officially supported.'
rm -f -r _obj mupen64plus-video-glide64mk2.so
make: Leaving directory '/home/aperfeito/Downloads/mupen64plus-bundle-src-2.5/source/mupen64plus-video-glide64mk2/projects/unix'
make: Entering directory '/home/aperfeito/Downloads/mupen64plus-bundle-src-2.5/source/mupen64plus-video-glide64mk2/projects/unix'
Makefile:117: Architecture "armv7l" not officially supported.'
    CC  _obj/GlideHQ/tc-1.1+/fxt1.o
    CC  _obj/GlideHQ/tc-1.1+/wrapper.o
    CC  _obj/GlideHQ/tc-1.1+/texstore.o
    CC  _obj/Glide64/osal_dynamiclib_unix.o
    CXX _obj/Glide64/3dmath.o
    CXX _obj/Glide64/Combine.o
    CXX _obj/Glide64/Config.o
    CXX _obj/Glide64/CRC.o
    CXX _obj/Glide64/Debugger.o
../../src/Glide64/3dmath.cpp:43:23: fatal error: xmmintrin.h: No such file or directory
 #include <xmmintrin.h>
                       ^
compilation terminated.
make: *** [Makefile:482: _obj/Glide64/3dmath.o] Error 1
make: *** Waiting for unfinished jobs....
make: Leaving directory '/home/aperfeito/Downloads/mupen64plus-bundle-src-2.5/source/mupen64plus-video-glide64mk2/projects/unix'



    I compiled using : Linux alarm 3.10.18-18-ARCH #5 SMP Mon Feb 20 14:21:15 PST 2017 armv7l GNU/Linux


Still a Problem


   Best Regards

________________________________
De: Logan McNaughton <notifications@github.com>
Enviado: quinta-feira, 9 de março de 2017 22:52:52
Para: mupen64plus/mupen64plus-core
Cc: Alexander Nunes Perfeito; Author
Assunto: Re: [mupen64plus/mupen64plus-core] Compile fails on src Linux Armv7l (#252)


You need to compile like:

make VFP_HARD=1 -j4 all

**Comment by loganmc10** [comment]
A lot has changed since the 2.5 release, and this is also why it says:

```
Architecture "armv7l" not officially supported.'
```
