### ISSUE TITLE
Mupen 0.5 Save States (Discussion)

### ISSUE THREAD

**Issue by danebouchie** [mupen64plus/mupen64plus-core#254]
I was curious why there isn't direct support for save states with Mupen 0.5 (*.m64). Is this just a lack of need, or is it impossible to have the two be compatible? 

(I was potentially looking to add this feature since I have a need for it, but just wanted to hear some opinion first.)

**Comment by richard42** [comment]
I don't think it's impossible, but no-one has requested this or built it.

**Comment by Meriipu** [comment]
What are save states? Load a modified rom and it loads to a point rather than from the beginning?
