### ISSUE TITLE
Banjo-Kazooie intro puzzle effect not displaying correctly with Rice

### ISSUE THREAD

**Issue by Siilwyn** [mupen64plus/mupen64plus-core#265]
In the intro of Banjo-Kazooie the puzzle effect has a short flicker and the pieces are black instead of containing 'the graphics'. It looks like [this on the N64](https://youtu.be/zSgseX7Yyck?t=1m24s) and like [this on Mupen64Plus](https://gfycat.com/GentleExcitableJunco).

I also tried the EU version and several other versions of the game. This is the log:
```
Mupen64Plus Console User-Interface Version 2.5.0

UI-Console Error: dlopen('/usr/local/lib/libmupen64plus.so.2') failed: /usr/local/lib/libmupen64plus.so.2: cannot open shared object file: No such file or directory
UI-Console: attached to core library 'Mupen64Plus Core' version 2.5.0
UI-Console:             Includes support for Dynamic Recompiler.
Core: Goodname: Banjo-Kazooie (U) (V1.0) [!]
Core: Name: Banjo-Kazooie       
Core: MD5: B29599651A13F681C9923D69354BF4A3
Core: CRC: A4BF9306 BF0CDFD1
Core: Imagetype: .v64 (byteswapped)
Core: Rom size: 16777216 bytes (or 16 Mb or 128 Megabits)
Core: Version: 1448
Core: Manufacturer: Nintendo
Core: Country: USA
UI-Console Status: Cheat codes disabled.
UI-Console: using Video plugin: 'Mupen64Plus OpenGL Video Plugin by Rice' v2.5.0
UI-Console: using Audio plugin: 'Mupen64Plus SDL Audio Plugin' v2.5.0
UI-Console: using Input plugin: 'Mupen64Plus SDL Input Plugin' v2.5.0
UI-Console: using RSP plugin: 'Hacktarux/Azimer High-Level Emulation RSP Plugin' v2.5.0
Video: SSE processing enabled.
Video: Found ROM 'Banjo-Kazooie', CRC 0693bfa4d1df0cbf-45
Video: Initializing OpenGL Device Context.
Core: Setting 32-bit video mode: 640x480
Video Warning: Failed to set GL_BUFFER_SIZE to 32. (it's 24)
Video Warning: Failed to set GL_DEPTH_SIZE to 16. (it's 24)
Video: Using OpenGL: Intel Open Source Technology Center - Mesa DRI Intel(R) Haswell Mobile  : 3.0 Mesa 12.0.6
Audio: Initializing SDL audio subsystem...
Core: Starting R4300 emulator: Dynamic Recompiler
Core: R4300: starting 64-bit dynamic recompiler at: 0x7f2b33ee2bc0
```

**Comment by Meriipu** [comment]
I have reproduced the same issue

**Comment by fzurita** [comment]
iI'm not sure about Rice, but for Glide64mk2, you need fb_read_always = 1.

**Comment by Meriipu** [comment]
How is that set? I added fb_read_always = 1 to the bottom of my ~/.config/mupen64plus/mupen64plus.cfg-file and then launched BK with 
mupen64plus --configdir ~/.config/mupen64plus/mupen64plus.cfg BK.n64

the short black flash still happens

**Comment by fzurita** [comment]
Inside the [Glide64mk2] section.

**Comment by Meriipu** [comment]
It did not seem to change the black flash (though the actual puzzle transition was never broken itself, if that is what it was supposed to fix). There is just a short stutter of sorts before it starts.

**Comment by fzurita** [comment]
Ok, the config I mentioned was to fix the black puzzle pieces. I'm not sure about the flashing issue.

**Comment by Siilwyn** [comment]
Does not seem to work for me is is that because of 'rice'?

**Comment by fzurita** [comment]
I'm not sure how you can get that effect to work with the rice video plugin. The setting I mentioned was for the Glide64mk2 video plugin.

**Comment by Narann** [comment]
I don't think any framebuffer effect works with dolphin.
