### ISSUE TITLE
Question: RSP specific instructions and their interpretation

### ISSUE THREAD

**Issue by olivieryuyu** [mupen64plus/mupen64plus-core#267]
I am currently trying to reverse ucodes for HLE development (currently Rogue Squadron, not easy at all).

I have now a good knowledge of SU mips and easy VU mips inctructions but I am a bit confused with VU multiplication, division and so on.

I understand how the instructions works somehow but I am really struggling a lot to interpret that in a more "HLE" manner.

There is some specific format in the N64 programming manual as for instance S10.5. Is there a relationship between format and type of multiplication made in the RSP? Would u have an idea?

For instance I am working on a specific part of the vertex command of Rogue Squadron for fog.

![7487d73a-29f8-11e7-91b6-5449d7902222](https://cloud.githubusercontent.com/assets/8987490/25472023/c784bf7a-2b29-11e7-8b84-6e35b6b0f156.png)

For this case, I would understand that we would do a 32 bits addition.

And for this case:

![0ee25c1a-29f9-11e7-89e8-54133f39f3cd](https://cloud.githubusercontent.com/assets/8987490/25472028/cd613338-2b29-11e7-8b84-b7d0cc875dd6.png)

a 32 bits multiplication.

Do I stand correct? I guess not ... :(

@bsmiles32 & @Gillou68310: would be great to get your help here!

**Comment by bsmiles32** [comment]
Sorry for late reply.
For reverse engineering ucode into HLE you will indeed need a good understanding of each rsp instruction. You can look at other LLE implementations to get a grasp of what each instruction does. Especially all the multiply variants eg vmudX vs vmadX with X denoting what portion of the accumulator gets used and in which register it gets stored.

For analysis the RSP ucode you can use radare2 tools. I pushed some month ago a disassembler for the RSP. It can help visualizing code structure.

I hope to be able to get back to rsp ucode reverse engineering sometimes, but for now I'm still busy with other projects.

**Comment by olivieryuyu** [comment]
Thanks!

I have now quite an understanding of the multiplication instructions.

Do you have how works VRCP instructions by any chance?

I should get the reciprocal of the a short vector? I am not sure to understand how this should be calculated.
