### ISSUE TITLE
new dynarec ARM crash

### ISSUE THREAD

**Issue by fzurita** [mupen64plus/mupen64plus-core#268]
This was reported to me once. No idea of what game and I don't have a save state.

```
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 80000284
Stack frame     #00  pc 000a1074  ./libmupen64plus-core.so: Routine emit_movimm at ./mupen64plus-core/src/device/r4300/new_dynarec/arm/assem_arm.c:1200
```

This is the line for reference in case it shifts:
```
  }else if(genimm(~imm,&armval)) {
    assem_debug("mvn %s,#%d",regname[rt],imm);
    output_w32(0xe3e00000|rd_rn_rm(rt,0,0)|armval); <---- Crashing right here
  }else if(imm<65536) {
```

**Comment by Gillou68310** [comment]
We really need to do something about the crash reporting system on android, it's the second crash reported without enough information.

**Comment by fzurita** [comment]
I know, it makes life very difficult. It would be nice to get game name and md5 and last auto save.

This could be automated, but we would need a hosting service for the crash reports. I wonder if GitHub could do it through automated issue generation.

On another note, we shouldn't "exit" when we detect an issue in the new dynarec. It's better to "abort" since that generates a core dump and then we know about it.

**Comment by fzurita** [comment]
Those is impossible to diagnose without knowing the conditions. I'm closing it.
