### ISSUE TITLE
New Dynarec: WDC not working

### ISSUE THREAD

**Issue by loganmc10** [mupen64plus/mupen64plus-core#274]
Just posting this issue so it doesn't get forgotten.

World Driver Championship, and I assume Stunt Racer, don't work with the new dynarec. On Android, the "logo screen" appears, but then it crashes.

The game works with the Cached Interpreter and the "old dynarec".

Some relevant discussion here:

https://github.com/mupen64plus/mupen64plus-core/pull/257#issuecomment-296417290

**Comment by loganmc10** [comment]
Here is the assert from the x86 new dynarec:

```
mupen64plus: ../../src/device/r4300/new_dynarec/new_dynarec.c:5963: do_ccstub: Assertion `branch_regs[i].regmap[HOST_CCREG]==CCREG||branch_regs[i].regmap[HOST_CCREG]==-1' failed.
```

**Comment by Gillou68310** [comment]
@bsmiles32 could you also assign me to this issue? ;-)

**Comment by olivieryuyu** [comment]
is it feasible also to get this game running in HLE?

I mean not the ucode (I can work on doing the reverse engineering of it) but simply running.
