### ISSUE TITLE
BattleTanx - Global Assault (U) - Game restarts

### ISSUE THREAD

**Issue by loganmc10** [mupen64plus/mupen64plus-core#283]
This game has an intro sequence. It starts by saying something about how "a plague killed 99.9% of a women". If you try to skip the sequence by pressing Start, or A or something, the game just restarts. It's like it does a soft reset or something.

I tested some older versions of mupen64plus-core back to Sept 2016-ish and there is no difference.

I tested Android and x64, same result.

EDIT: I did find someone that mentioned this same issue with Project64 back in 2012, so I don't think I'm crazy: http://forum.pj64-emu.com/showpost.php?p=40383&postcount=3

**Comment by loganmc10** [comment]
I just tested Project64 and I had the exact same issue. I tried the E rom and it worked properly on both emulators (although it didn't work the first time?)

Is it possible I have a bad ROM? Can someone else test this out?

**Comment by bsmiles32** [comment]
I quickly tested both Europe and USA version and they were going in game.
My USA version has MD5 : 654557C316F901A2CA6F7F4B43343147
So maybe bad dump ?

**Comment by loganmc10** [comment]
My USA rom has the same MD5, so strange. I've tested this on multiple PC's and my Android device and I experience the same thing.

**Comment by bsmiles32** [comment]
However I was not using the master branch but the one from PR 268 (no_g_dev_in_interrupt).

**Comment by loganmc10** [comment]
I tried that branch too, no luck, this is just so baffling to me, I'll play around with it a bit more.

**Comment by loganmc10** [comment]
So it seems like it works sometimes, but most of the time it doesn't work. I am trying all kinds of different settings, and sometimes I think I found one that worked, then I try it again and it doesn't work.

The same thing happens in Project64. @bsmiles32 if you get a chance can you try your USA rom 1 or 2 more times? I just want to make sure I'm not crazy.

**Comment by bsmiles32** [comment]
You're not crazy ! After a new try on the U version, I got the behavior you describe : pressing buttons gets me back to 3DO intro screen.

**Comment by bsmiles32** [comment]
The Europe version seems fine however.

**Comment by loganmc10** [comment]
> You're not crazy !

Haha k I can finally tell my wife that someone agrees with me. I'm not really sure what to do with this, the exact same thing happens in Project64. I assume it is some kind of timing thing, since this game requires CountPerOp=3 to boot

**Comment by loganmc10** [comment]
I realized how to reproduce this on both the U and E version. If you don't press anything and let the opening cinematic play, then hit start during the opening cinematic, the game restarts. If you press start at the "press start" screen, you move on to the next screen.

It seems like odd behavior to me, but it's possible that the game just works this way. I'm going to close this until/unless someone can confirm that the game works differently on real hardware
