### ISSUE TITLE
CBFD freezes when entering other stages using a saved state

### ISSUE THREAD

**Issue by joxeankoret** [mupen64plus/mupen64plus-core#284]
Hi,

I have a save state for Conker's Bad Fur Day that seems to be unstable. When entering any new zone or when dying, the game seems to get stuck. The music continues normally but it never gets into the new zone or re-spawns after being killed.

I tried entering into almost any new zone that could possibly "fix" the problem as well as disabled/enabled cheats, and tried other things, but it seems I'm unable to continue the game.

I can provide the save state files if required. My setup is Windows 10 x64, latest mupen64plus (distributed binaries) for x64.

Any help would be appreciated!

PS: I'm a reverse engineer and programmer so I could debug myself the problem given some hint about what should I look into.

**Comment by joxeankoret** [comment]
It can also be reproduced, easily, by simply pressing the "Start" button.

**Comment by loganmc10** [comment]
If you provide the save state I can look into it a bit

**Comment by joxeankoret** [comment]
Sure. Here is it. Thanks in advance!

[Conker's Bad Fur Day (E) [!].zip](https://github.com/mupen64plus/mupen64plus-core/files/1016194/Conker.s.Bad.Fur.Day.E.zip)

**Comment by loganmc10** [comment]
Is it just the save state? Like if you load the game from a regular save file does it happen?

**Comment by joxeankoret** [comment]
Yes, just the saved state (but unfortunately the only one I have).

**Comment by loganmc10** [comment]
I haven't had much luck with this. Were you using cheats at all?

**Comment by joxeankoret** [comment]
Yes, so probably something was corrupted. I think I will debug it myself. How can I open the in-game debugger? Or do I need to build the source myself?

**Comment by loganmc10** [comment]
You need to compile mupen64plus with ```DEBUGGER=1``` set. I've never used it so I don't know how well it works or how to use it.

I've heard that cheats can mess with save states, so that is likely the cause.

**Comment by joxeankoret** [comment]
Ok then, thank you!
