### ISSUE TITLE
Banjo tooie crash after latest refactors

### ISSUE THREAD

**Issue by fzurita** [mupen64plus/mupen64plus-core#287]
@loganmc10 @Gillou68310 @bsmiles32 

It seems that something broke banjo tooie recently. I suspect it was the latest refactors, it was working fine before. Here is a savestate from @retrobenny

[grogged.zip](https://github.com/mupen64plus/mupen64plus-core/files/1024051/grogged.zip)

**Comment by loganmc10** [comment]
Just out of random curiosity, how did retroben experience this? The refactorings haven't been merged into mupen64plus-ae. Also, you mentioned CBFD, does it crash early? Or at some later point in-game?

**Comment by fzurita** [comment]
CBFD was a report from the google play store. I have not been able to reproduce the issue, so I'm omitting it for now. Also, I do notice that there is another open issue which mentions CBFD.

I have merged at least some of the refactorings to mupen64plus-ae, so retrobenny is playing with those. To reproduce the issue, just go in the building. There were issues in this game before when speculative recompilation was enabled, but it's disabled now as far as I can tell.

**Comment by loganmc10** [comment]
I just tested that save state with the x86 new dynarec, went into the building and played the 3 mini games. No crash or any issues. It must be some issue with the ARM dynarec.

**Comment by fzurita** [comment]
I'm going to try going to the latest core revision. Maybe something fixed it recently. Or it could be an issue with just the arm dynarec.

**Comment by fzurita** [comment]
That's not good. The latest core crashes immediately in Android. I'll try to figure out the issue tomorrow.

**Comment by retrobenny** [comment]
You are actually supposed to walk to the right near Jamjars and attempt to look at Groggy Bear the gassy overweight son of Boggy Bear.
The character is the trigger of the hang.

**Comment by loganmc10** [comment]
I went and talked to Groggy, no issues with the x86 new dynarec

**Comment by retrobenny** [comment]
Well this is most likely an ARM specific issue then.
How fortunate for those using x86 architecture not having it hang on them. 😁 
Too bad for me though on ARM with SATV. 🙁

**Comment by fzurita** [comment]
I'm not getting a good core dump out of the core. I guess I'll have to start dissecting to see which commit broke it.

**Comment by fzurita** [comment]
Ok, it seems this commit broke the core in Android:

c0cb7006e737ade650051ed32bf2b8d14e3f5119

**Comment by fzurita** [comment]
I can't get the game to crash on d15fcb847306bdeec0cc914eb8afc2ed06caea77

**Comment by bsmiles32** [comment]
Thanks for bissecting this. @Gillou68310 any idea why ARM dynarec broke with these changes ? If it causes too much trouble I will revert the offending commit which should be this one 936c00ccce032487494776bb4119c6501d03158c

**Comment by loganmc10** [comment]
Here is the backtrace from a Raspberry Pi if it's helpful. I'm not sure why all the values are "optimized out", I compiled with DEBUG=1 and made sure -O0 was set:

```
Thread 1 "mupen64plus" received signal SIGSEGV, Segmentation fault.
cvt_w_s.lto_priv.297 (fcr31=<optimized out>, source=<optimized out>, dest=<optimized out>, dest=<optimized out>, source=<optimized out>) at ../../src/device/r4300/fpu.h:171
171	    switch(*fcr31 & 3)
(gdb) backtrace
#0  cvt_w_s.lto_priv.297 (fcr31=<optimized out>, source=<optimized out>, dest=<optimized out>, dest=<optimized out>, source=<optimized out>)
    at ../../src/device/r4300/fpu.h:171
#1  0x6b6922b4 in g_dev () from ./libmupen64plus.so.2
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

**Comment by bsmiles32** [comment]
My guess is that because I use one extra "argument" register to pass fcr31 pointer to fpu functions, I need to update the reglist which states which registers gets saved/restored before/after calling these functions. But I'm not so sure of how to do it and if it is the root cause of the crash.

**Comment by bsmiles32** [comment]
I've reverted the offending commit in master. I shouldn't have committed it in the first place. Sorry for the regression.
Hope that @Gillou68310 can look into it

**Comment by fzurita** [comment]
Also, I think the Banjo Tooie issue that @retrobenny is having is due to GLideN64, not the core. Glide64 doesn't crash.

**Comment by bsmiles32** [comment]
@gizmo98 reported also a crash on his side. So I still believe something is wrong with this commit. Will open a PR to work on it.

**Comment by loganmc10** [comment]
@fzurita I tested Banjo Tooie with GLideN64 on x86, maybe it's one of the Neon optimizations in GLideN64 or something.

**Comment by fzurita** [comment]
Closing because all the core issues discussed here are fixed.

**Comment by gizmo98** [comment]
@bsmiles32 https://github.com/mupen64plus/mupen64plus-core/commit/87e8207cfe5339fce4e768b6ea01370c0071d185 fixes the reported crash.
