### ISSUE TITLE
Indiana Jones x86 new dynarec crash

### ISSUE THREAD

**Issue by loganmc10** [mupen64plus/mupen64plus-core#288]
Right after starting the first level:

```
../../src/device/r4300/new_dynarec/new_dynarec.c:4005: load_assemble: Assertion `th>=0' failed.
```

**Comment by loganmc10** [comment]
x64 old dynarec seems to be fine

**Comment by fzurita** [comment]
Happens with ARM as well.

**Comment by Gillou68310** [comment]
@bsmiles32 could you also assign me to this issue? ;-)

**Comment by Gillou68310** [comment]
https://github.com/mupen64plus/mupen64plus-core/pull/383

@loganmc10, @fzurita could you guys check my fix for regressions ;-)

**Comment by fzurita** [comment]
Sure! Probably some time tonight.
