### ISSUE TITLE
macho64 output format not recognized on El Capitan

### ISSUE THREAD

**Issue by lannocc** [mupen64plus/mupen64plus-core#291]
I am running OS X El Capitan but the latest mupen64plus-core no longer compiles. This problem appears to have been introduced on Feb 16 in commit *3e5bd0f848ca52510f4f20ae68a58cb12cffb90d*. Here is the relevant error:
```
    AS  _obj/device/r4300/x86_64/dyna_start.o
nasm: fatal: unrecognised output format `macho64' - use -hf for a list
type `nasm -h' for help
make: *** [_obj/device/r4300/x86_64/dyna_start.o] Error 1
```
Some more information about my system:

`$ uname -a`
```
Darwin LANNOCC-iMac 15.6.0 Darwin Kernel Version 15.6.0: Tue Apr 11 16:00:51 PDT 2017; root:xnu-3248.60.11.5.3~1/RELEASE_X86_64 x86_64
```
`$ nasm -v`
```
NASM version 0.98.40 (Apple Computer, Inc. build 11) compiled on Oct  5 2016
```
`$ nasm -hf`
```
valid output formats for -f are (`*' denotes default):
  * bin       flat-form binary files (e.g. DOS .COM, .SYS)
    aout      Linux a.out object files
    aoutb     NetBSD/FreeBSD a.out object files
    coff      COFF (i386) object files (e.g. DJGPP for DOS)
    elf       ELF32 (i386) object files (e.g. Linux)
    as86      Linux as86 (bin86 version 0.3) object files
    obj       MS-DOS 16-bit/32-bit OMF object files
    win32     Microsoft Win32 (i386) object files
    rdf       Relocatable Dynamic Object File Format v2.0
    ieee      IEEE-695 (LADsoft variant) object file format
    macho     NeXTstep/OpenStep/Rhapsody/Darwin/MacOS X object files
```

**Comment by bsmiles32** [comment]
To get the macho64 format you need to update nasm. See https://gist.github.com/FiloSottile/7125822 for instance

**Comment by lannocc** [comment]
Thank you for your quick response. I did not expect this compiled-7-months-ago NASM to already be out of date... but I appear to have be using the Apple-packaged NASM which is actually pretty old. So `brew install nasm` brought me to a much more recent version and that did the trick.

Now I'd like to go ahead and a version requirement note for OS X in the README in our fork (http://github.com/AlphaGriffin/mupen64plus-core) if I could just figure out which version of NASM added macho64 (somewhere between 0.98.40 and 2.13.01).

Thanks again!
