### ISSUE TITLE
Mupen64plus.cfg changes being overwritten automatically after game launch.

### ISSUE THREAD

**Issue by Twitch0815** [mupen64plus/mupen64plus-core#292]
Platform:  Retropie 4.2 fully updated mupen64plus from binary
Hardware: Raspberry pi 3
Games used for testing Super Mario 64
Texture pack used for testing: http://www.emulation64.com/files/info/950/ 
Plugins tested: Glide64 and Rice
Affecting: Special Input Configuration, Hi-Resolution Texture Packs

Support Threads with issue being discussed:  https://retropie.org.uk/forum/topic/4479/n64-mupen64plus-cfg-changes-keep-getting-overwritten     https://retropie.org.uk/forum/topic/8384/mupen64plus-cfg-overwrite/4      https://retropie.org.uk/forum/topic/10338/n64-hi-res-no-longer-working/4  

For replication or testing I  modified mupen64plus.cfg to enable the Hi-Resolution texture pack. Specifically # Use high-resolution texture packs if available.
txHiresEnable = True

Then I ran Retropie-Setup updated retropie setup, updated mupen64plus from binary

Launched a game, the texture pack I loaded did not load, and when going back to mupen 64plus.cfg to check if the variable had stayed as I had just configured it i get

cat mupen64plus.cfg | grep txHiresEnabletxHiresEnable = False
pi@retropie:/opt/retropie/configs/n64 $

Here is a time stamp after I just updated mupen64plus.cfg to enable
-rw-r--r-- 1 pi pi 15742 May 26 05:16 mupen64plus.cfg
cat mupen64plus.cfg | grep txHiresEnabletxHiresEnable = True

after I run and exit game with the option for GlideN64HiRes in runcommand

-rw-r--r-- 1 pi pi 15743 May 26 05:17 mupen64plus.cfg

and
recheck variable
cat mupen64plus.cfg | grep txHiresEnabletxHiresEnable = False

This has affected multiple other issues trying to enable hi-resolution texture packs as well as those trying to do input configuration changes.

**Comment by loganmc10** [comment]
This is a retropie thing, it isn't being done by mupen64plus
