### ISSUE TITLE
Save states are locking up the emulator

### ISSUE THREAD

**Issue by fzurita** [mupen64plus/mupen64plus-core#294]
Some times, on the latest commit as of right now, the save states being generated are locking up the emulator when loaded. I have tried different RSP and video plugins. This didn't happen before, so something broke this recently. I have also only tried the ARM new dynarec.

This is specially bad with Goldeneye, where it is happening about half the time.

**Comment by fzurita** [comment]
I have the feeling that we are not waiting for the correct interrupt when making a save state.

**Comment by loganmc10** [comment]
I tested this on the x64 "old" dynarec and x86 new dynarec. It seemed to work fine on the x64 dynarec. I got it to freeze on the x86 new dynarec, but it took a lot of tries, definitely not 1/2

Here is the bad save state, it freezes the emulator if you try and load it.

[GoldenEye.zip](https://github.com/mupen64plus/mupen64plus-core/files/1033933/GoldenEye.zip)

**Comment by fzurita** [comment]
Well, it's luck. Maybe I got unlucky and it froze for me more often. It seemed really bad in the intro of the game.

**Comment by bsmiles32** [comment]
Could it be related to changes in commit a21299985fb9752244174c5b5083624735faa858 where I reworked the first triggering of VI interrupt ?

**Comment by fzurita** [comment]
I can try reverting it and checking if it happens again.

**Comment by fzurita** [comment]
Ok, I was able to reproduce the issue after reverted https://github.com/mupen64plus/mupen64plus-core/commit/a21299985fb9752244174c5b5083624735faa858

I'm going to try reverting all recent commits that changed interrupt handling code and see if anything fixes it.

**Comment by fzurita** [comment]
Ok, this turns out that it's not a recent issue. I just wasn't looking for it before. I went back all the way to this commits before all the mayor refactors and it still happens:

https://github.com/mupen64plus/mupen64plus-core/commits/master?after=e8baea699fc6af8a4b91d8a038ee04ac92f78bbb+139

**Comment by bsmiles32** [comment]
Could this be related to TLB mappings not being saved/restored correctly in the new_dynarec ?

**Comment by loganmc10** [comment]
I managed to get GoldenEye to do this again with the x86 new dynarec. But it's really rare for me, we are talking maybe 1/100 save states (I just tap F5 and then F7 over and over again until it freezes). I couldn't get it to do it with the x64 dynarec, but I don't know for sure if it's not possible there, because like I said, it seems really rare.

**Comment by fzurita** [comment]
Try it with Android. You can map a controller to save and load state and go through a lot of iterations that way.

**Comment by loganmc10** [comment]
I did about 30-40 save states on Android during the intro and the Dam level. I couldn't get it to lock up

**Comment by fzurita** [comment]
Try doing the same but on this screen. It's about 25% chance of moving to for me right here:
![goldeneye-000](https://cloud.githubusercontent.com/assets/11581687/26536392/681aa574-4404-11e7-9143-9c1783ff8e5a.png)

**Comment by loganmc10** [comment]
I did about 15-20 on that screen and couldn't get it to lock up. It does seem to happen though, just seems really rare for me. I don't know, maybe somebody can look at that bad savestate I uploaded and figure out what is wrong with it and work backwards from that. It might be really hard to pinpoint the problem since it seems pretty hard to reproduce.

**Comment by fzurita** [comment]
Interesting, I have a very easy time reproducing it. Like 25% for me. I do do it slightly different than you though in mupen64plus-ae. I start up the game, then exit, then resume, then exit, then resume, etc... Maybe it has to do with that.

**Comment by loganmc10** [comment]
Yeah I'm just hitting save state/load state. Same on the desktop, just F5 and F7

**Comment by loganmc10** [comment]
@fzurita one thing I notice is that you should define -DUSE_SDL for mupen64plus-core. See the upstream Unix makefile. There is a SDL mutex that is used for save states if that is defined. (See inside savestates.c)

**Comment by fzurita** [comment]
Hmmm, you are right. As far as I can tell, we have never defined that. Good catch.

**Comment by fzurita** [comment]
Ok, good catch, but it wasn't the problem.

**Comment by fzurita** [comment]
I sent an abort signal to the process to get a core dump to tell me where it's stuck. This is the results:

```
#00 pc 000528f0  .libmupen64plus-core.so: Routine get_addr at ./mupen64plus-core/src/device/r4300/new_dynarec/new_dynarec.c:1964 (discriminator 1)
#01 pc 000af070  .libmupen64plus-core.so: Routine .E2 at linkage_arm.S:?

```

**Comment by fzurita** [comment]
I made this pull request: https://github.com/mupen64plus/mupen64plus-core/pull/302 It seems to fix the issue for me. I have no idea if it's the correct fix or if there could be any side effects of doing this. Any ideas?

**Comment by loganmc10** [comment]
So here is an interesting test. That save state I posted (GoldenEye.zip). I can't load it using the x86 new dynarec. It locks up. But, I can load it using the x64 old dynarec and the Cached Interpreter.

Probably a good test to determine if this issue is fixed is if the new dynarec can load that save state. I tried the changes in #302 and it couldn't load the that file

**Comment by fzurita** [comment]
It's not intended to fix the loading of save state. The change I made is intended to only generate save states that load correctly.

**Comment by loganmc10** [comment]
Yeah but is that the issue? Doesn't it lock up when you try to load the save state?

Maybe they are separate issues. But that save state I have was generated using the new dynarec, but it can't be loaded using the new dynarec, that is what was causing the lockup for me. If it could load that save state like the x64 dynarec or the Cached Interpreter, I would have never experienced any lockups.

**Comment by fzurita** [comment]
Right, I don't know the root cause. Although, it could be some kind of TLB issue like bsmiles32 was saying. All I can say at this point is that I have not been able to generate a save state that locks up the emulator using the change I made. It doesn't mean that we shouldn't try to find the root cause of the issue that is preventing the new dynarec from loading the save state.

**Comment by bsmiles32** [comment]
As far as I remember TLB isn't properly implemented. Pagemask isn't honored thus preventing usage of non 4k pages. Also we have a dirty isGoldenEye hack inside virtual_to_physical address translation. And new_dynarec also reimplements some TLB logic on its own. Not sure if this is the root issue, but proper TLB support is IMO worth looking into.

**Comment by fzurita** [comment]
I'm not sure what changed, but I haven't seen this in a long time. I'll keep it closed until I see it again.
