### ISSUE TITLE
No RPS available in Mupen64 0.51

### ISSUE THREAD

**Issue by Jeffrey123454** [mupen64plus/mupen64plus-core#303]
I have tried reinstalling a few times, searched around for the plugin found it, but it still doesn't work, no RPS config it's just blank (I have a screenshot, didntI edited with Paint...didn't turn out that well)

![rsp plugin missing](https://cloud.githubusercontent.com/assets/20335635/26595355/6167ccda-456b-11e7-8a72-a5a97885c4f1.png)

**Comment by loganmc10** [comment]
Mupen64 0.51 is very old, this is mupen64plus, which is a much updated fork of that project.

You can get the latest official release of mupen64plus here (although even this is a little old):

https://github.com/mupen64plus/mupen64plus-core/releases/tag/2.5

Personally I would recommend going here:

**Comment by Jeffrey123454** [comment]
Yes, I'm aware that Mupen64 0.5.1 is outdated, but, so far I have seen that Mupen64plus is all with command prompt, is there a version available with a manageable GUI instead of commands?

**Comment by loganmc10** [comment]
The link I provided you (https://m64p.github.io/) includes a GUI, the program is called "mupen64plus-gui.exe" (mupen64plus.exe is the command line version)

There is also m64py (http://m64py.sourceforge.net/) which is a GUI for mupen64plus
