### ISSUE TITLE
Pokemon Puzzle League New Dynarec assert

### ISSUE THREAD

**Issue by loganmc10** [mupen64plus/mupen64plus-core#304]
```
mupen64plus: ../../src/device/r4300/new_dynarec/new_dynarec.c:3335: alu_assemble: Assertion `s2h>=0' failed.
```

**Comment by loganmc10** [comment]
This was on a Raspberry Pi

**Comment by Gillou68310** [comment]
@bsmiles32 could you also assign me to this issue? ;-)

**Comment by loganmc10** [comment]
I just tested this on Android (arm) and x86 and couldn't reproduce it. I suppose it's possible that I was using a debug build on my Raspberry Pi, and that allowed the assert to be triggered, but I don't really use my Raspberry Pi anymore so I can't be sure. In any event, it seems to work fine in a release build

**Comment by Gillou68310** [comment]
I worked on this issue yesterday and there is really a bug here, so this should stay open!

**Comment by loganmc10** [comment]
Oh ok my bad, I guess an assert does get triggered, it must be arm specific then, I didn't run across it in x86 with asserts enabled

**Comment by Gillou68310** [comment]
Yep it's arm specific ;-)

**Comment by Gillou68310** [comment]
@fzurita @loganmc10 I can not reproduce this issue with latest master. Could you guys double check?

**Comment by fzurita** [comment]
Yep, not crashing any more. Unintended bug fix?

**Comment by Gillou68310** [comment]
lol yeah

**Comment by Gillou68310** [comment]
ok closing this
