### ISSUE TITLE
South park restarts (x86 fix not PIC complaint)

### ISSUE THREAD

**Issue by fzurita** [mupen64plus/mupen64plus-core#316]
I'm not sure when these issues were introduced but he are a couple:

South Park 64: Game randomly resets, easy to reproduce, just start the game and try to kill something. It sounds game timing related.

Turok 1: This issue was reported to me. Getting shot at and dying causes the game to get stuck in a black screen.

**Comment by loganmc10** [comment]
South Park: I could reproduce consistently with x86 new dynarec, but never with Cached Interpreter or x64 dynarec. So I'm assuming it's something to do with the new dynarec, I'll try and find the originating commit when I get time

Turok: Couldn't reproduce (used x86 new dynarec), I allowed myself to be shot and killed, I re-spawned and could keep playing, maybe a graphics plugin issue?

**Comment by fzurita** [comment]
Yeah, Turok issue could be.

**Comment by loganmc10** [comment]
The South Park issue can be hard for me to reproduce sometimes, it doesn't happen when I hit an enemy, it just happens sometime shortly after the game starts, but not always.

The earliest commit I could reproduce the issue on was c84be36e1f5a795d79e2883b2dd8010cde924a83, but it could be older than that.

**Comment by loganmc10** [comment]
Ok I'm fairly confident the South Path issue originated with ec41a85876067993c9493d00dae879c2118bfed6 (PR #269). That is the first commit that I can reproduce the issue with. But again, only with the new dynarec (seems to affect arm and x86)

**Comment by Gillou68310** [comment]
This should fix the issue:
https://github.com/Gillou68310/mupen64plus-core/commit/c0ace1d9716343ba09c149d7e0b047981093f6c8

**Comment by loganmc10** [comment]
Yep that seems to fix it (tested x86 new dynarec)

**Comment by fzurita** [comment]
Cool, that was fast.

**Comment by bsmiles32** [comment]
Merged the changes by @Gillou68310 given the positive feedback.
However I fail to understand the core issue this solves, and why it was necessary modify mips_interpreter.def and x86{,_64}/dynarec.c files which where apparently not affected by this random reset.
@Gillou68310 : Could you elaborate more on this please :) ?

**Comment by Gillou68310** [comment]
The main idea of my commit is to mask the address with 0xFFFFFFFC after tlb exception checks.
This way CP0_BADVADDR_REG will have the real address instead of the masked one in case of a tlb exception.
I'm actually surprised that it was only impacting the new dynarec!

**Comment by fzurita** [comment]
Interesting, why did that I've commit cause the issue to appear I wonder.

**Comment by fzurita** [comment]
Issue seems fixed. Closing.

**Comment by fzurita** [comment]
Reopening since this doesn't work correclty for Android x86. It doesn't compile currently and I think it's causing a core dump.

**Comment by fzurita** [comment]
@Gillou68310 I think I need some help. I think NDK15 broke the x86 new dynarec

**Comment by Gillou68310** [comment]
Your right my commit broke PIC support for linkage_x86, I'm currently reworking the tlb exception code so this issue will be fixed during the process.

> @Gillou68310 I think I need some help. I think NDK15 broke the x86 new dynarec

Does eveything works fine with older NDK

**Comment by fzurita** [comment]
Yeah

**Comment by Gillou68310** [comment]
Where is it crashing with NDK15?

**Comment by fzurita** [comment]
It's not, it's starting then immediately exiting.

**Comment by Gillou68310** [comment]
No exit or abort signal?

**Comment by fzurita** [comment]
Nope, all I see in the logs is this:

Starting R4300 emulator
R4300 emulator finished.

**Comment by Gillou68310** [comment]
Weird!

**Comment by Gillou68310** [comment]
Well the only solution is to debug with gdb (or the clang equivalent) to see what's happening.

**Comment by fzurita** [comment]
Right, I'm not that great at assembly, I'll have to figure something out.

**Comment by Gillou68310** [comment]
Could you send me the disassembly of the core, I think we can at least start with that!

**Comment by fzurita** [comment]
Yep, I think you should be able to reproduce this if you setup an x86 Android emulator

**Comment by fzurita** [comment]
I'm trying to setup NDK15 again....

**Comment by Gillou68310** [comment]
> Yep, I think you should be able to reproduce this if you setup an x86 Android emulator

Sure, I still hope to find something within the disassembly ;-)

**Comment by fzurita** [comment]
I'll send you the compiled core, I'm not quite sure how to generate a disassembly:

https://drive.google.com/file/d/0B57Ioy26LWegZ0N6ZEt5ajhsQms/view?usp=sharing

**Comment by Gillou68310** [comment]
I'll need to download ndk15 to disassemble. With gcc you can generate the disassembly using objdump -d. Not sure what is the clang equivalent.

**Comment by fzurita** [comment]
Gotcha, I'm reverting back to NDK14 for now.

**Comment by Gillou68310** [comment]
BTW did you try to build with gcc instead of clang? Is gcc still available in NDK15?

**Comment by fzurita** [comment]
It's there but not supported. I can build using clang just fine with NDK14 though.

**Comment by Gillou68310** [comment]
I guess the clang version changed between NDK15 and NDK14.

**Comment by Gillou68310** [comment]
Could you try with gcc I just want to make sure it's a compiler issue

**Comment by Gillou68310** [comment]
In NDK15

**Comment by fzurita** [comment]
Yeah, sure, I will try, just trying to get NDK14 working again.

**Comment by Gillou68310** [comment]
Ok

**Comment by Gillou68310** [comment]
> I'll send you the compiled core, I'm not quite sure how to generate a disassembly:
> 
> https://drive.google.com/file/d/0B57Ioy26LWegZ0N6ZEt5ajhsQms/view?usp=sharing

Could you send me mupen64plus-core.so also?

**Comment by fzurita** [comment]
Sure, trying to get NDK15 going again.

**Comment by fzurita** [comment]
Ok, I narrowed down the issue. It's related to asm_defines_nasm.h generation for x86. I took the one generated in NDK 14 and it make NDK15 work.

**Comment by fzurita** [comment]
@Gillou68310 I think I found the problem. I wasn't defining ```TARGET := -target i686-none-linux-android``` for x86 because I thought it wasn't needed. So I probably was compiling for who knows what target.

**Comment by Gillou68310** [comment]
Ok good to know this is fixed, I'll take care of the PIC issue.

**Comment by fzurita** [comment]
This seems to be affecting Turok 2 as well.

**Comment by loganmc10** [comment]
Couldn't reproduce on Linux, I ran through the intro on the x86 new dynarec 3 times, it didn't restart or anything.

**Comment by fzurita** [comment]
This is after I reverted @Gillou68310 change since it's not PIC complaint.

**Comment by loganmc10** [comment]
oh ok. On Linux/Windows the x86 build is built without PIC so it's not an issue there it seems.

**Comment by fzurita** [comment]
It seems fixed now unless @Gillou68310 says otherwise.
