### ISSUE TITLE
DisableExtraMem no longer working?

### ISSUE THREAD

**Issue by loganmc10** [mupen64plus/mupen64plus-core#325]
I am trying to get Iggy's Reckin' Balls to run.

My Googling suggest that I need to set "DisableExtraMem" to get it to boot. But I cannot get that to work.

I tried the downloadable version of m64py, and it works there (using DisableExtraMem)! This leads me to believe that sometime in the recent past, DisableExtraMem has become broken, I need to do some more testing though.

**Comment by loganmc10** [comment]
As a pretty good indicator that it's broken, if you launch a game like Indiana Jones (or any game that tells you if you have the Expansion Pak installed), it will say "N64 Expansion Pak enhanced" whether or not you have "DisableExtraMem" on

**Comment by loganmc10** [comment]
Sorry never mind, I realize that this is a problem with my frontend, it is because DisableExtraMem is read on CoreStartup, which I've already called before I try to change the settings

**Comment by bsmiles32** [comment]
I had to do it in CoreStartup because some gfx plugin access rdram early in RomOpen. If we can rework how plugins are called, this might be done like other parameters.

**Comment by loganmc10** [comment]
That seems to be true for g_rdram, but not g_rdram_size. g_rdram is always created with size RDRAM_MAX_SIZE, and g_rdram_size is never accessible by the plugins it seems

**Comment by bsmiles32** [comment]
8MB is indeed always allocated whatever the requested size is. This is to not break savestates. Rdram informations are passed during plugin initialisation. However rdram size is not part of the zilmar plugin spec. So some gfx plugin try to guess it (wrongly) by triggering invalid access outside of allocated rdram.
