### ISSUE TITLE
x86 new dynarec crashing

### ISSUE THREAD

**Issue by fzurita** [mupen64plus/mupen64plus-core#328]
I'm getting a ton of reported crashes at this location in the latest master but only when using the x86 new dynarec:

```
#00 pc 0000000000000000  <unknown>: Unable to open symbol file .\mupen64plus-ae\app\build\intermediates\ndkBuild\release\obj\local\x86/<unknown>. Error (22): Invalid argument
#01 pc 000000000000ba80  /data/app-lib/org.mupen64plusae.v3.fzurita-1/libmupen64plus-core.so: Routine run_device at ./mupen64plus-core/src/device/device.c:115
#02 pc 000000000000f14e  /data/app-lib/org.mupen64plusae.v3.fzurita-1/libmupen64plus-core.so: Routine main_run at ./mupen64plus-core/src/main/main.c:1138
#03 pc 0000000000008ed7  /data/app-lib/org.mupen64plusae.v3.fzurita-1/libmupen64plus-core.so: Routine CoreDoCommand at ./mupen64plus-core/src/api/frontend.c:231
#04 pc 0000000000006db0  /data/app-lib/org.mupen64plusae.v3.fzurita-1/libmupen64plus-ui-console.so: Routine SDL_main at ./mupen64plus-ui-console/src/main.c:798
#05 pc 0000000000001e2a  /data/app-lib/org.mupen64plusae.v3.fzurita-1/libae-exports.so: Routine Java_paulscode_android_mupen64plusae_jni_NativeExports_emuStart at ae-bridge/ae_exports.cpp:220
```

This works out to be this line of code:
```
void run_device(struct device* dev)
{
    /* device execution is driven by the r4300 */
    run_r4300(&dev->r4300); <---- Right here
}
```

It looks like ```dev``` is an invalid pointer.

**Comment by fzurita** [comment]
I'm able to reproduce the crash. It's also crashing when using interpreter.

**Comment by loganmc10** [comment]
I wonder if this has something to do with how the library is compiled or linked in Android? I've tested the x86 new dynarec on Windows and Linux in the past few days (Linux just now) and it works.

**Comment by fzurita** [comment]
Could be, I'm stepping through commits to determine what broke it.

**Comment by fzurita** [comment]
This could be my fault. It looks like I removed 
    ```LOCAL_ASMFLAGS = -d PIC``` from the Android makefile while making some updates

**Comment by fzurita** [comment]
Ok, once I added ```-d PIC``` to the assembler, I'm getting this error:

```
./mupen64plus-core/src/device/r4300/new_dynarec/x86/linkage_x86.asm:491: error: expected `]'
```

**Comment by fzurita** [comment]
@Gillou68310 
This commit breaks compilation in Android x86:
https://github.com/mupen64plus/mupen64plus-core/commit/c0ace1d9716343ba09c149d7e0b047981093f6c8#diff-e14129433463ebdbfc88325279006620

**Comment by fzurita** [comment]
Closing this one and re-opening https://github.com/mupen64plus/mupen64plus-core/issues/316
