### ISSUE TITLE
Indiana Jones freeze at end of level

### ISSUE THREAD

**Issue by loganmc10** [mupen64plus/mupen64plus-core#331]
Firstly, this game is very unstable unless CountPerOp=1 is set. It seems like there were some issues in the past with this, but I played through the first level twice with CountPerOp=1 and it worked well. With CountPerOp=2, it sometimes freezes right after you get control of Indy. There is also flickering that happens on CountPerOp=2.

The big issue though: At the end of the level, it goes to a black screen and freezes there. I tested with the x84 dynarec and Cached Interpreter.

Project64 has the same issue, but only with their CPU Re-compiler (not their Interpreter) https://github.com/project64/project64/issues/259.

Here is a save state during the ending cutscene of the first level if anyone wants to take a look: I would use the Cached Interpreter and set CountPerOp=1 if you're going to try it out

[Indiana Jones and the Infernal Machine (U) [!].zip](https://github.com/mupen64plus/mupen64plus-core/files/1122692/Indiana.Jones.and.the.Infernal.Machine.U.zip)

**Comment by loganmc10** [comment]
What a whacky game. If I load that save state with CountPerOp=2, then I can get to the Trading Post/end of level. But if I play the whole level through with CountPerOp=2, it doesn't load.

This game might be hard to emulate without cycle accuracy, there may be some magical combination of CountPerOp/CountPerScanline that works though

**Comment by AmbientMalice** [comment]
Also, the jeep physics are wrong without CF=1, and there are issue with the inflatable life-raft.

**Comment by loganmc10** [comment]
I'm going to revisit this if HLE graphics are ever accomplished for this game, see comment in #332
