### ISSUE TITLE
Compressed ROM support

### ISSUE THREAD

**Issue by tony971** [mupen64plus/mupen64plus-core#335]
@loganmc10 suggested in m64p/mupen64plus-gui#5 that supporting ROMs compressed into common types should fall under the jurisdiction of the core emulator, rather than GUIs.

**Comment by loganmc10** [comment]
This is just my opinion so I welcome other's thoughts on this, it just seemed redundant to implement compressed ROM support in every frontend instead of the core.

I've never cared much about compressed ROMs so I'm not too motivated to implement this either...

**Comment by richard42** [comment]
It should be pretty easy to implement support for gzipped ROMs. I'd rather not add a bunch of additional dependencies to support different archive formats though. It's better if the core is lean.

**Comment by Narann** [comment]
@loganmc10 I politely disagree. This subject has been discussed long time ago: Core goal is to avoid as much dependencies as possible. Historically, core has been leaned removing many things. It's actually what has make it able to compile on virtually every platform (most N64 mobile app are a clone of mupen64plus). I think, despite the bad words at that times, this was a very good decision.

The problem with "compressed rom" is that there is a lot of different formats to support (rar, 7z, etc.) and it imply some file management logic that, IMHO, core shouldn't put its nose in and let to the front-end job (rom management/cache).

If it was only me, core shouldn't even have rom endian swapping, letting the front end manage the collection and particularities of user's roms.

**Comment by loganmc10** [comment]
I know I eventually caved and implemented 7z and zip support in https://github.com/m64p/mupen64plus-gui, @tony971 this can probably be closed since m64py also supports compressed roms. I'm not sure about mupen64plus-ae but I think it does as well

**Comment by Narann** [comment]
Thanks @loganmc10.
