### ISSUE TITLE
Unable to map C buttons

### ISSUE THREAD

**Issue by n1ghttrap** [mupen64plus/mupen64plus-core#340]
The core seems to be limited to right stick mapping or the C button "mode".  This is not viable for fighting games or Mischief Makers.  Are there any plans to allow individual mapping to any key/button soon?   Any workarounds?

**Comment by loganmc10** [comment]
Are you using RetroArch?

**Comment by n1ghttrap** [comment]
Yes.  Made a proper issue for the libretro core.  Apologies.
