### ISSUE TITLE
Anisotropic Filtering Missing

### ISSUE THREAD

**Issue by shinra358** [mupen64plus/mupen64plus-core#346]
I see jaggies in the distance and then I realized there is no anisotropic filtering like the standalone. I would like to request that anisotropic filtering be added so that there is no jaggying of horizons. I also would like you to rename the AA setting to MSAA so ppl will know what type of AA they are dealing with.

**Comment by Papermanzero** [comment]
This is a graphic plugin issue.

**Comment by shinra358** [comment]
Doesn't seem to be a problem in the standalone.

**Comment by dankcushions** [comment]
this is standalone...

**Comment by shinra358** [comment]
huh? but the path says mupen64plus/mupen64plus-core at the top???
