### ISSUE TITLE
Crash GLXBadFBConfig

### ISSUE THREAD

**Issue by huvox** [mupen64plus/mupen64plus-core#349]
Mupen crashes on startup no matter which video plugin is used the log always looks the same.

Ubuntu 16.04 and 17.04 tested

Log:

>>   __  __                         __   _  _   ____  _             
> |  \/  |_   _ _ __   ___ _ __  / /_ | || | |  _ \| |_   _ ___ 
> | |\/| | | | | '_ \ / _ \ '_ \| '_ \| || |_| |_) | | | | / __|  
> | |  | | |_| | |_) |  __/ | | | (_) |__   _|  __/| | |_| \__ \  
> |_|  |_|\__,_| .__/ \___|_| |_|\___/   |_| |_|   |_|\__,_|___/  
>              |_|         http://code.google.com/p/mupen64plus/  
> Mupen64Plus Console User-Interface Version 2.5.0
> 
> UI-Console: attached to core library 'Mupen64Plus Core' version 2.5.0
> UI-Console:             Includes support for Dynamic Recompiler.
> UI-Console:             Includes support for MIPS r4300 Debugger.
> Core: Goodname: Super Mario 64 (U) [!]
> Core: Name: SUPER MARIO 64      
> Core: MD5: 20B854B239203BAF6C961B850A4A51A2
> Core: CRC: 635A2BFF 8B022326
> Core: Imagetype: .v64 (byteswapped)
> Core: Rom size: 8388608 bytes (or 8 Mb or 64 Megabits)
> Core: Version: 1444
> Core: Manufacturer: Nintendo
> Core: Country: USA
> UI-Console Status: Cheat codes disabled.
> UI-Console: using Video plugin: 'Mupen64Plus OpenGL Video Plugin by Rice' v2.5.0
> UI-Console: using Audio plugin: 'Mupen64Plus SDL Audio Plugin' v2.5.0
> UI-Console: using Input plugin: 'Mupen64Plus SDL Input Plugin' v2.5.0
> UI-Console: using RSP plugin: 'Hacktarux/Azimer High-Level Emulation RSP Plugin' v2.5.0
> Input: 0 SDL joysticks were found.
> Input: N64 Controller #1: Forcing default keyboard configuration
> Input: 1 controller(s) found, 1 plugged in and usable in the emulator
> Input Warning: Couldn't open rumble support for joystick #1
> Input Warning: Couldn't open rumble support for joystick #2
> Input Warning: Couldn't open rumble support for joystick #3
> Input Warning: Couldn't open rumble support for joystick #4
> Input: Mupen64Plus SDL Input Plugin version 2.5.0 initialized.
> Video: SSE processing enabled.
> Video: Found ROM 'SUPER MARIO 64', CRC ff2b5a632623028b-45
> Video: Initializing OpenGL Device Context.
> Core: Setting 32-bit video mode: 640x480
> Core Error: SDL_SetVideoMode failed: Could not create GL context: GLXBadFBConfig
> Video Error: Failed to set 32-bit video mode: 640x480
> Core Status: Rom closed.

glxinfo | grep OpenGL

> OpenGL vendor string: Intel Open Source Technology Center
> OpenGL renderer string: Mesa DRI Intel(R) Pineview M x86/MMX/SSE2
> OpenGL version string: 1.4 Mesa 12.0.6
> OpenGL extensions:
> OpenGL ES profile version string: OpenGL ES 2.0 Mesa 12.0.6
> OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.0.16
> OpenGL ES profile extensions:

**Comment by loganmc10** [comment]
Your computer only supports OpenGL 1.4. I believe you'll need at least OpenGL 2.1 to run the video plugin.

**Comment by huvox** [comment]
Found a solution for the OpenGL version [https://askubuntu.com/questions/19607/how-to-enable-opengl-2-0-and-webgl-on-gma-3150](url) but the problem is still the same

**Comment by loganmc10** [comment]
hm I'm not sure then, basically ```Could not create GL context: GLXBadFBConfig``` is telling you that it doesn't like your graphics drivers.

**Comment by huvox** [comment]
Thats a little bit strange. I am using the stock driver from the xserver-xorg-video-intel package.

> lspci -k | grep -EA3 "VGA|3D|Display"
> 00:02.0 VGA compatible controller: Intel Corporation Atom Processor D4xx/D5xx/N4xx/N5xx Integrated Graphics Controller
> 	Subsystem: ASUSTeK Computer Inc. Atom Processor D4xx/D5xx/N4xx/N5xx Integrated Graphics Controller
> 	Kernel driver in use: i915
> 	Kernel modules: i915
> 00:02.1 Display controller: Intel Corporation Atom Processor D4xx/D5xx/N4xx/N5xx Integrated Graphics Controller
> 	Subsystem: ASUSTeK Computer Inc. Atom Processor D4xx/D5xx/N4xx/N5xx Integrated Graphics Controller
> 
>

**Comment by loganmc10** [comment]
Sorry when I say graphics drivers I mean your GPU + graphics drivers, basically it can't provide all the OpenGL features the plugin is looking for. You could potentially try a different graphics plugin like glide64mk2 instead of rice.

**Comment by Jj0YzL5nvJ** [comment]
[Intel Goes Ahead & Drops i915 Driver From OpenGL 2.1 To 1.4 By Default](https://www.phoronix.com/scan.php?page=news_item&px=OpenGL-1.4-i915-Now-Default)

 I have 25 machines in the work with the same iGPU, Atom Processor of 1.8 GHz. None plugin gonna give you good performance.
 Games like [mari0](https://github.com/Stabyourself/mari0) push to the limit the capacity of that machine.

 If you want to check it out for yourself, you need compile the driver i915g from freedesktop.org or use padoka PPA / Oibaf PPA.
 Even so, i915g has been broken for a long time, that's why Intel dropped it. Modesetting driver does not even work, you need set UXA in AccelMethod to not broke OpenGL, etc.

 The best thing you can do is get yourself another machine, seriously.

i915:
```
GL_RENDERER   = Mesa DRI Intel(R) Pineview x86/MMX/SSE2
GL_VERSION    = 1.4 Mesa 11.2.0
GL_VENDOR     = Intel Open Source Technology Center
GL_EXTENSIONS = GL_ARB_multisample GL_EXT_abgr GL_EXT_bgra GL_EXT_blend_color GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_copy_texture GL_EXT_polygon_offset GL_EXT_subtexture GL_EXT_texture_object GL_EXT_vertex_array GL_EXT_compiled_vertex_array GL_EXT_texture GL_EXT_texture3D GL_IBM_rasterpos_clip GL_ARB_point_parameters GL_EXT_draw_range_elements GL_EXT_packed_pixels GL_EXT_point_parameters GL_EXT_rescale_normal GL_EXT_separate_specular_color GL_EXT_texture_edge_clamp GL_SGIS_generate_mipmap GL_SGIS_texture_border_clamp GL_SGIS_texture_edge_clamp GL_SGIS_texture_lod GL_ARB_multitexture GL_IBM_multimode_draw_arrays GL_IBM_texture_mirrored_repeat GL_3DFX_texture_compression_FXT1 GL_ARB_texture_cube_map GL_ARB_texture_env_add GL_ARB_transpose_matrix GL_EXT_blend_func_separate GL_EXT_fog_coord GL_EXT_multi_draw_arrays GL_EXT_secondary_color GL_EXT_texture_env_add GL_EXT_texture_filter_anisotropic GL_EXT_texture_lod_bias GL_INGR_blend_func_separate GL_NV_blend_square GL_NV_light_max_exponent GL_NV_texgen_reflection GL_NV_texture_env_combine4 GL_S3_s3tc GL_SUN_multi_draw_arrays GL_ARB_texture_border_clamp GL_ARB_texture_compression GL_EXT_framebuffer_object GL_EXT_texture_compression_s3tc GL_EXT_texture_env_combine GL_EXT_texture_env_dot3 GL_MESA_window_pos GL_NV_packed_depth_stencil GL_NV_texture_rectangle GL_ARB_depth_texture GL_ARB_shadow GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_mirrored_repeat GL_ARB_window_pos GL_EXT_stencil_two_side GL_EXT_texture_cube_map GL_APPLE_packed_pixels GL_APPLE_vertex_array_object GL_ARB_draw_buffers GL_ARB_fragment_program GL_ARB_fragment_shader GL_ARB_shader_objects GL_ARB_vertex_program GL_ARB_vertex_shader GL_ATI_draw_buffers GL_ATI_texture_env_combine3 GL_EXT_shadow_funcs GL_EXT_stencil_wrap GL_MESA_pack_invert GL_MESA_ycbcr_texture GL_ARB_half_float_pixel GL_ARB_point_sprite GL_ARB_shading_language_100 GL_ARB_sync GL_ARB_texture_non_power_of_two GL_ARB_vertex_buffer_object GL_ATI_blend_equation_separate GL_EXT_blend_equation_separate GL_OES_read_format GL_ARB_pixel_buffer_object GL_ARB_texture_rectangle GL_EXT_pixel_buffer_object GL_EXT_texture_compression_dxt1 GL_EXT_texture_rectangle GL_EXT_texture_sRGB GL_ARB_framebuffer_object GL_EXT_framebuffer_blit GL_EXT_packed_depth_stencil GL_APPLE_object_purgeable GL_ARB_vertex_array_object GL_ATI_separate_stencil GL_EXT_gpu_program_parameters GL_EXT_texture_sRGB_decode GL_OES_EGL_image GL_ARB_copy_buffer GL_ARB_map_buffer_range GL_ARB_ES2_compatibility GL_ARB_debug_output GL_ARB_draw_elements_base_vertex GL_ARB_explicit_attrib_location GL_ARB_provoking_vertex GL_ARB_sampler_objects GL_EXT_provoking_vertex GL_ARB_get_program_binary GL_ARB_robustness GL_ARB_separate_shader_objects GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_ARB_compressed_texture_pixel_storage GL_ARB_internalformat_query GL_ARB_map_buffer_alignment GL_ARB_texture_storage GL_AMD_shader_trinary_minmax GL_ARB_clear_buffer_object GL_ARB_explicit_uniform_location GL_ARB_invalidate_subdata GL_ARB_program_interface_query GL_ARB_vertex_attrib_binding GL_KHR_debug GL_ARB_multi_bind GL_ARB_get_texture_sub_image GL_KHR_context_flush_control
```

i915g:
```
GL_RENDERER   = Gallium 0.4 on i915 (chipset: Pineview G)
GL_VERSION    = 2.1 Mesa 13.1.0-devel - padoka PPA
GL_VENDOR     = Mesa Project
GL_EXTENSIONS = GL_ARB_multisample GL_EXT_abgr GL_EXT_bgra GL_EXT_blend_color GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_copy_texture GL_EXT_polygon_offset GL_EXT_subtexture GL_EXT_texture_object GL_EXT_vertex_array GL_EXT_compiled_vertex_array GL_EXT_texture GL_EXT_texture3D GL_IBM_rasterpos_clip GL_ARB_point_parameters GL_EXT_draw_range_elements GL_EXT_packed_pixels GL_EXT_point_parameters GL_EXT_rescale_normal GL_EXT_separate_specular_color GL_EXT_texture_edge_clamp GL_SGIS_generate_mipmap GL_SGIS_texture_border_clamp GL_SGIS_texture_edge_clamp GL_SGIS_texture_lod GL_ARB_multitexture GL_IBM_multimode_draw_arrays GL_IBM_texture_mirrored_repeat GL_ARB_texture_cube_map GL_ARB_texture_env_add GL_ARB_transpose_matrix GL_EXT_blend_func_separate GL_EXT_fog_coord GL_EXT_multi_draw_arrays GL_EXT_secondary_color GL_EXT_texture_env_add GL_EXT_texture_filter_anisotropic GL_EXT_texture_lod_bias GL_INGR_blend_func_separate GL_NV_blend_square GL_NV_light_max_exponent GL_NV_texgen_reflection GL_NV_texture_env_combine4 GL_S3_s3tc GL_SUN_multi_draw_arrays GL_ARB_texture_border_clamp GL_ARB_texture_compression GL_EXT_framebuffer_object GL_EXT_texture_compression_s3tc GL_EXT_texture_env_combine GL_EXT_texture_env_dot3 GL_MESA_window_pos GL_NV_packed_depth_stencil GL_NV_texture_rectangle GL_ARB_depth_texture GL_ARB_occlusion_query GL_ARB_shadow GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_mirrored_repeat GL_ARB_window_pos GL_ATI_fragment_shader GL_EXT_stencil_two_side GL_EXT_texture_cube_map GL_NV_fog_distance GL_APPLE_packed_pixels GL_APPLE_vertex_array_object GL_ARB_draw_buffers GL_ARB_fragment_program GL_ARB_fragment_shader GL_ARB_shader_objects GL_ARB_vertex_program GL_ARB_vertex_shader GL_ATI_draw_buffers GL_ATI_texture_env_combine3 GL_EXT_shadow_funcs GL_EXT_stencil_wrap GL_MESA_pack_invert GL_MESA_ycbcr_texture GL_NV_primitive_restart GL_ARB_fragment_program_shadow GL_ARB_half_float_pixel GL_ARB_occlusion_query2 GL_ARB_point_sprite GL_ARB_shading_language_100 GL_ARB_sync GL_ARB_texture_non_power_of_two GL_ARB_vertex_buffer_object GL_ATI_blend_equation_separate GL_EXT_blend_equation_separate GL_OES_read_format GL_ARB_pixel_buffer_object GL_ARB_texture_rectangle GL_EXT_pixel_buffer_object GL_EXT_texture_compression_dxt1 GL_EXT_texture_rectangle GL_EXT_texture_sRGB GL_ARB_framebuffer_object GL_EXT_framebuffer_blit GL_EXT_packed_depth_stencil GL_ARB_vertex_array_object GL_ATI_separate_stencil GL_EXT_draw_instanced GL_EXT_gpu_program_parameters GL_EXT_texture_sRGB_decode GL_OES_EGL_image GL_ARB_copy_buffer GL_ARB_draw_instanced GL_ARB_half_float_vertex GL_ARB_instanced_arrays GL_ARB_map_buffer_range GL_ARB_vertex_array_bgra GL_EXT_vertex_array_bgra GL_ARB_ES2_compatibility GL_ARB_debug_output GL_ARB_draw_elements_base_vertex GL_ARB_explicit_attrib_location GL_ARB_fragment_coord_conventions GL_ARB_provoking_vertex GL_ARB_sampler_objects GL_ARB_vertex_type_2_10_10_10_rev GL_EXT_provoking_vertex GL_ARB_get_program_binary GL_ARB_robustness GL_ARB_separate_shader_objects GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_ARB_compressed_texture_pixel_storage GL_ARB_internalformat_query GL_ARB_map_buffer_alignment GL_ARB_texture_storage GL_AMD_shader_trinary_minmax GL_ARB_clear_buffer_object GL_ARB_explicit_uniform_location GL_ARB_invalidate_subdata GL_ARB_program_interface_query GL_ARB_vertex_attrib_binding GL_KHR_debug GL_ARB_internalformat_query2 GL_ARB_multi_bind GL_ARB_vertex_type_10f_11f_11f_rev GL_ARB_get_texture_sub_image GL_KHR_context_flush_control
```

That's part of the logs when I tested i915g and it worked correctly (2016-07-19).

**Comment by ricrpi** [comment]
@huvox have you tried changing any configuration parameters? mupen64plus + video-rice segfaults on my laptop (that uses i915 driver) if the resolution in mupen64plus.cfg does not match the native display resolution.

mesa provides a software implementation of openGL so should work, assuming your machine has enough CPU power.

**Comment by huvox** [comment]
Sorry for the late response, with experimental drivers from the padoka ppa it rums quiet smooth but everything else crashes. I think i will try with other hardware, but thanks for the help.
