### ISSUE TITLE
[Website] HTTPS does not work

### ISSUE THREAD

**Issue by rlabrecque** [mupen64plus/mupen64plus-core#354]
https://mupen64plus.org/

This currently redirects to a hostgator page. This is the link that google is currently serving as one of the top results.

**Comment by richard42** [comment]
I did some research into this and found that HostGator will give me one free SSL cert with my hosting account, so I have requested one for the domain "mupen64plus.org". I think it should automatically start working as it propagates through DNS in the next 24 hours or so. However, I'm pretty sure that this will not also cover the domain "www.mupen64plus.org". I could order one for this domain as well but will have to pay for it. Do you think this is necessary, or is it sufficient to stick with the domain without the www prefix?

**Comment by bentley** [comment]
[Let’s Encrypt](https://letsencrypt.org/) certificates are totally free. I’ve had success using them for multiple domains that I own.

It would be good to have both mupen64plus and www.mupen64plus.org certs. I’ve seen search engines (Yahoo, and others like DuckDuckGo that then use Yahoo results) prioritize the wrong one, and happily show a certificate error to anyone who clicks the search result; getting Let’s Encrypt certs for both domains wound up being easier than convincing Yahoo to fix their search results.

**Comment by rlabrecque** [comment]
Seems like it's working fine now, and it works on both the bare domain and www!

Closing this.
