### ISSUE TITLE
Top Gear Rally freezing frames

### ISSUE THREAD

**Issue by Tasosgemah** [mupen64plus/mupen64plus-core#372]
The game works but it runs in a very weirs way, it's smooth for a fraction of a second but it freezes then repeat. It's like heavy frame skipping but it has moments when it runs smoothly between freezes.

**Comment by loganmc10** [comment]
Can you give details about what plugins you're using, where you got mupen64plus, etc?

I've tested this game a lot lately while working on audio and it's always run well for me

**Comment by Tasosgemah** [comment]
Hmmm, i thought mupen64puls-core is the libretro core for RetroArch. That's where the problem is, not the standalone.

**Comment by fzurita** [comment]
This should be checked again.

**Comment by Tasosgemah** [comment]
Yeah, this issue has been fixed for a while now so it can close.
