### ISSUE TITLE
Save paths not correct.

### ISSUE THREAD

**Issue by scottluker** [mupen64plus/mupen64plus-core#374]
So in the config file it says: `If this is blank, the default value of ${UserConfigPath}/save will be used`  but this isn't the case, if left blank mupen will use the appdata folder whether or not a config file directory is specified.

This was noticed in an [issue for m64p](https://github.com/m64p/mupen64plus-gui/issues/17) and seems to be related to: https://github.com/mupen64plus/mupen64plus-core/blob/5c386fd741e776a499b67a8d867fc4cdd8e927d3/src/main/main.c#L140-L146

**Comment by loganmc10** [comment]
Should be fixed now via https://github.com/mupen64plus/mupen64plus-core/pull/393 (as far as I'm aware, the description won't update unless mupen64plus.cfg is wiped though)

**Comment by Narann** [comment]
@scottluker could you test with lated version?

**Comment by scottluker** [comment]
This has been fixed with the latest changes.
