### ISSUE TITLE
Travis CI broken

### ISSUE THREAD

**Issue by loganmc10** [mupen64plus/mupen64plus-core#377]
@charlemagnelasse maybe you could take a look? It's complaining about some apt dependencies

**Comment by charlemagnelasse** [comment]
@loganmc10 did you try to restart the build for this pull request?
@richard42  or @bsmiles32  can you please restart the build using the https://travis-ci.org/mupen64plus/mupen64plus-core/builds/246039941

It is shown here how to do that: https://stackoverflow.com/questions/17606874/trigger-a-travis-ci-rebuild-without-pushing-a-commit#answer-17624403

**Comment by loganmc10** [comment]
I can restart them, the problem still exists

**Comment by charlemagnelasse** [comment]
Thanks for testing. It looks like their servers are still broken. You can try the workaround from #380. It replaces the apt-get calls with the apt travis ci addon. The installed packages are still the same.
