### ISSUE TITLE
Can't compile on Linux ARM (64 bit kernel, 32 bit user land)

### ISSUE THREAD

**Issue by rtissera** [mupen64plus/mupen64plus-core#378]
Hello,

Trying to get mupen64plus compiling on ROCK64 (RockChip RK3328) with an armhf Ubuntu Xenial image.

uname -m correctly reports it as aarch64, which is not detected as a valid CPU type, so it fails.
Some folks suggested using "dpkg --print-architecture" which correctly reports armhf but this is Debian/Ubuntu only.

I am aware the ARM dynarec is ARMv5 / ARMv7 only but it should be allowed to build on such systems provided we build 32-bit binaries.

**Comment by Gillou68310** [comment]
Hi, you can tell the makefile to build for a specific CPU by overriding the HOST_CPU variable before launching the make command:

```export HOST_CPU=armhf```

Also don't forget to set VFP_HARD=1 for armhf support.

**Comment by Gillou68310** [comment]
BTW I'm running mupen64plus with no issue on my ODROID C2 Ubuntu Xenial 64bit using chroot 32bit, so it should totally work on your ROCK64 ;-)

**Comment by Narann** [comment]
I take this as an opportunity to ask: Would it be an interesting idea to add a travis build for arm and raspberry pi? Should I open a ticket for this?

**Comment by loganmc10** [comment]
> Would it be an interesting idea to add a travis build for arm and raspberry pi? Should I open a ticket for this?

Travis only offers build environments based on x64 Ubuntu or Mac OS X. You can theoretically spin up a VM during the travis build and then run the build inside that VM, but I think there might be some timeouts that happen if a build runs for too long. It any event it would be fairly complicated and kind of hacky. There is a fairly large RetroPie and Android following, so ARM specific issues usually get reported fairly soon if there is an issue.

**Comment by loganmc10** [comment]
The only real good way to do it would be if someone had a Raspberry Pi that was always on and connected to the Internet, and we could have Travis SSH to it and run the build, but obviously we'd probably run into some reliability issues with that.

**Comment by Narann** [comment]
When I was trying to compile mupen64plus on rpi, my attempts where failing because of the lack of memory. My other option (which worked well) was to use cross platform compilation using gcc rpi.

The preparation script roughly looks like this:
```bash
# clone compiler
mkdir $HOME/code/rpi
git clone git://github.com/raspberrypi/tools.git

export RPI_TOOLS=$HOME/code/rpi/rpi-tools
export PATH=$RPI_TOOLS/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin:$PATH

# check version
arm-linux-gnueabihf-gcc -v

# copy rpi sd card lib folder in my rootfs folder
mkdir $HOME/code/rpi/rootfs
rsync -rl --delete-after --safe-links pi@bingo.Home:/{lib,usr} $HOME/rpi/rootfs

export RPI_TOOLS=/home/narann/code/rpi-tools
export RPI_ROOT=/mnt/rpi-root

export PATH=$RPI_TOOLS/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin:$PATH
export CC=arm-linux-gnueabihf-gcc
export CXX=arm-linux-gnueabihf-g++

# compile my program
arm-linux-gnueabihf-gcc hello_world.c -o hello_world
./hello_world
```

**Comment by loganmc10** [comment]
Oh yeah that's true I completely forgot about that! So then yes it would be possible to cross-compile a Raspberry Pi build on Travis. Probably not a bad idea, since it would be a good way to have Travis test the new dynarec as well and solve https://github.com/mupen64plus/mupen64plus-core/issues/96

**Comment by Narann** [comment]
Wow, I completely forgot this one !
