### ISSUE TITLE
Perfect Dark (Europe) is hanging/freezing at the Perfect Dark logo

### ISSUE THREAD

**Issue by SigmaVirus** [mupen64plus/mupen64plus-core#379]
Every time I try to load Perfect Dark (Europe) it hangs/freezes after the intro scenes at the Perfect Dark logo and I have to force quit mupen64plus (downloaded from [here](http://m64p.s3-website-us-east-1.amazonaws.com/201708/)) under the Task Manager.

Doesn't matter if I'm using the new experimental mupen64plus-video-angrylionplus plugin or the mupen64plus-video-GLideN64 plugin because output is always the same.

After the intro scenes and you press start the Joanna typing on the computer scene will follow where you can choose what to do but obviously this never happens.

**Comment by loganmc10** [comment]
PJ64 has the same issue:
https://github.com/project64/project64/issues/1022

It only happens in LLE, there is actually a PR pending with a fix for this:
https://github.com/mupen64plus/mupen64plus-core/commit/49f9d387ebd08e7f8306ab1dd58536a4246ef7b8
https://github.com/mupen64plus/mupen64plus-core/pull/371

**Comment by SigmaVirus** [comment]
I didn't know that it was an LLE issue, interesting really.

On Project64 it kinda works if you patiently wait for the intro screens to finish and then press start.

**Comment by loganmc10** [comment]
From reading the PJ64 thread it sounds like the PAL version works differently. I've only tested the U version, an it freezes in both emulators during the opening logo

**Comment by SigmaVirus** [comment]
I only own PAL versions in my N64 library, usually they work as intended but I think it's safe to say that PAL versions are known to be the more problematic ones in general.

Anyway glad to hear there's an pending fix to this problem!
