### ISSUE TITLE
Better COUNT emulation idea/enhancement

### ISSUE THREAD

**Issue by ricrpi** [mupen64plus/mupen64plus-core#384]
I have had this idea for a while but don't have the time to investigate/implement but others probably know the answer or may be interested in exploring:

Could we build a hybrid dynarec/interpreter mode where the dynarec primarily runs but when it detects the count register will underflow before reaching the next branch instruction then it jumps to a cycle/count accurate interpreter? 

After handling the interrupt, execution would return to the interpreter up to the next branch instruction before jumping back to the dynarec.

**Comment by loganmc10** [comment]
> when it detects the count register will underflow

I think "the devil is in the details" here. If we could detect that the COUNT register was drifting away from where it should be, there is probably a number of things we could do to try and correct that, but I don't know how you would detect that right now

**Comment by ricrpi** [comment]
so the idea would be that in the Dynamic Recompiler - Pass 8, the HOST_CCREG, aka COUNT in [new_dynarec.c](https://github.com/mupen64plus/mupen64plus-core/blob/42ae0f856d5cd78151cd9417908a316c97ae69e0/src/device/r4300/new_dynarec/new_dynarec.c#L5954-L5958) would be tested at the start of assembly of the ccstub.

if emit_addimm() is changed to 
`emit_cmpimm(HOST_CCREG, CLOCK_DIVIDER*stubs[n][3])`
then if the result becomes positive then we know to jump to the interpreter because the COUNT is going to overflow before the next branch/jump/return.

**Comment by Gillou68310** [comment]
The question is why do you want to jump to interpreter when the count overflow?

**Comment by ricrpi** [comment]
So that the interpreter could handle the count register accurately.

**Comment by Gillou68310** [comment]
Sorry but I don't understand your point, the count register will have the same value whether you're using dynamic recompiler or pure interpreter. The only reason why they won't have the same value is because of a bug in dynarec.

**Comment by Gillou68310** [comment]
Actually the new dynarec has a few bugs with the count register (mainly with idle loops), those need to be fixed. Maybe that's what you're referring to?

**Comment by ricrpi** [comment]
My point is that the dynarec executes a block of code and adjusts the count register with one hit at the end. However the count register may overflow at some point within the execution of the block so emulation of the interrupt is delayed. This could stop cycle-accurate-dependant games from working correctly within the dynarec.

If there aren't any games requiring cycle accuracy then this idea wouldn't bring any benefits.

**Comment by Gillou68310** [comment]
> My point is that the dynarec executes a block of code and adjusts the count register with one hit at the end.

That's not correct the count register is updated every time it's necessary not just at the end of the block.

I'll take the example for branches:
-The ```do_cc``` function will update the cycle count in HOST_CCREG (esi on x86) at every branches.
-If the cycle count overflows it will jump to the stub created by ```do_ccstub```.
-The stub will jump to ```cc_interrupt``` in order to process pending interrupts.
-The count register is updated at the beginning of ```cc_interrupt```

```mov     [find_local_data(g_dev_r4300_cp0_regs+36)],    esi    ;Count```

**Comment by ricrpi** [comment]
But the dynarec does not adjust and test the count register after every emulated mips instruction therefore there will be instances where count > 0 before gen_interrupt is called instead of at count == 0.

**Comment by Gillou68310** [comment]
That's correct but the same is true for interpreter!

**Comment by ricrpi** [comment]
ah ok, have to admit that I have not looked at the interpreter code properly

**Comment by Gillou68310** [comment]
No problem, that's the main point of having a discussion ;-)
Should we close this?

**Comment by ricrpi** [comment]
The question has to be asked whether there are games that would benefit from more accurate COUNT emulation, I hope not but I wish I had the time to experiment, maybe by implementing count adjustments on every instruction for the interpreter to confirm.

Feel free to close this issue as it will still be on record as a potential idea if someone has time :-)
