### ISSUE TITLE
Bomberman 64: black screen using arm/x86 new dynarec

### ISSUE THREAD

**Issue by loganmc10** [mupen64plus/mupen64plus-core#385]
This game just sits at a black screen after the initial logo appears. Only seems to happen with the x86 new dynarec. I tested on Android (ARM) and it works, also works in "old" dynarec.

@Gillou68310

**Comment by fzurita** [comment]
With somewhat recent changes, Bomberman 64 is freezing right after the first screen with the ARM new dynarec as well. It works fine in interpreter mode.

**Comment by fzurita** [comment]
We can also add Turok 2 to the list. It's not booting with the new dynarec, it boys in interpreter.

**Comment by Gillou68310** [comment]
@fzurita I think I now what's happening here, could you try to add invalidate_r4300_cached_code at the begining of write_rdram/d to see if it fixes the issue?

**Comment by fzurita** [comment]
Ok

**Comment by fzurita** [comment]
That seems to fix Bomberman 2. It didn't seem to fix the other listed games though.

**Comment by Gillou68310** [comment]
Ok thanks for testing. What's your rom md5 for turok2, I tested this game before merging and didn't notice any issue. You're testing on ARM only right?

**Comment by fzurita** [comment]
Yep, I'm only testing ARM. The Turok 2 md5 is Turok 2: FAD4DA8E17CE12F68CDF29180CDD4A90

**Comment by Gillou68310** [comment]
I have no issue with turok2 and shadow man on my odroid. I'm still on my tlb_exception_rework branch BTW. What version are you testing?

**Comment by Gillou68310** [comment]
Ok nevermind I can reproduce it on my tlb_exception_rework branch, the core library was not correctly installed for some reason.

**Comment by fzurita** [comment]
Add one more game, so a list of all the broken games right now with the ARM new dynarec:
* Turok 2
* Dance Dance revolution
* Bomberman 2
* Armorines

**Comment by Gillou68310** [comment]
@fzurita could you test if https://github.com/mupen64plus/mupen64plus-core/pull/450 fixes all listed issues

**Comment by fzurita** [comment]
Sure, I will be test.

**Comment by fzurita** [comment]
Add one more game, so a list of all the broken games right now with the ARM new dynarec:
* Turok 2 - Fixed
* Shadowman - Fixed
* Dance Dance revolution - Not fixed
* Bomberman 2 - Fixed
* Armorines - Fixed
* South Park 64 - Not fixed

**Comment by fzurita** [comment]
For Mario Artist Paint Studio and South Park, the core itself is exiting the game.

**Comment by Gillou68310** [comment]
Thanks I guess it's for investigation ;-)

**Comment by fzurita** [comment]
I'm not sure what is going on, but I'm unable to start any new games with the new dynarec with the last set of changes. I swore that I remember being able to start Turok 2 when I first tested your changes.

**Comment by Gillou68310** [comment]
Yep I double checked on my odroid and Banjo Kazooie and Southpark work fine for me too. Ok so I still need to fix DDR, it's broken on x86 too so it's not an ARM specific issue.

**Comment by Gillou68310** [comment]
BTW I don't get notifications when you edit a post, you should better post a new comment ;-)

**Comment by fzurita** [comment]
Yeah, I guess I don't like overloading people with too many notifications.
