### ISSUE TITLE
OSD=0 causes game to hang after one has been played

### ISSUE THREAD

**Issue by loganmc10** [mupen64plus/mupen64plus-core#389]
If I compile mupen64plus-core with OSD=0, when I play a game with https://github.com/m64p/mupen64plus-gui, the first game will work fine, but if I stop that game and try to launch a 2nd game, it'll freeze.

For some reason I couldn't reproduce it on Linux, just Windows. I'm not sure exactly what is going on.

**Comment by Narann** [comment]
I had a such problem in the past, not sure it's related but it can be a config problem: At first start, config is not set, at second start, config is read and information are bad.
The other tricky problem I had was a unitialized variable in rice which was ok at first execution but always bad after. https://github.com/mupen64plus/mupen64plus-video-rice/commit/e82afa7cf70616c9c96ff3ffc8aaf55e3007b3df

Not sure it's related though.

**Comment by loganmc10** [comment]
This is some kind of perfect storm. It only happens on Windows (only tested MinGW), and only when using GLideN64, so I'm going to close this, I assume it might not be anything related to the core.
