### ISSUE TITLE
Yakouchuu II - Satsujin Kouro does not go to menu

### ISSUE THREAD

**Issue by olivieryuyu** [mupen64plus/mupen64plus-core#392]
a weird in nearly all emulator

I think you need as for Pokemon Snap to delay the DP interrupt to get it solved

**Comment by loganmc10** [comment]
I think it just needs CountPerOp=1 set, do you know how to change that in mupen64plus? If you can confirm that fixes it i'll update the INI file

**Comment by bsmiles32** [comment]
@loganmc10 Setting CountPerOp=1 indeed allows to go in-menu.
But then I get a crash inside GlideN64...

See backtrace:
0x00007ffff122b1ec in gSPBranchLessZ(unsigned int, unsigned int, unsigned int) () from /usr/lib/mupen64plus/mupen64plus-video-GLideN64.so
(gdb) bt
#0  0x00007ffff122b1ec in gSPBranchLessZ(unsigned int, unsigned int, unsigned int) () from /usr/lib/mupen64plus/mupen64plus-video-GLideN64.so
#1  0x00007ffff12325f2 in RSP_ProcessDList() () from /usr/lib/mupen64plus/mupen64plus-video-GLideN64.so
#2  0x00007ffff0db1bbd in HleProcessDlistList (UNUSED_user_defined=<optimized out>) at ../../src/plugin.c:101
#3  forward_gfx_task () at ../../src/hle.c:172
#4  normal_task_dispatching (hle=<optimized out>) at ../../src/hle.c:301
#5  hle_execute (hle=0x7ffff0fb80e0 <g_hle>) at ../../src/hle.c:125
#6  DoRspCycles (Cycles=4294967295) at ../../src/plugin.c:182
#7  0x00007ffff60cf0ac in do_SP_Task (sp=0x7ffff73fc728 <g_dev+17834408>) at ../../src/device/rsp/rsp_core.c:284
#8  0x00007ffff60d7c7b in update_sp_status (sp=0x7ffff73fc728 <g_dev+17834408>, w=<optimized out>) at ../../src/device/rsp/rsp_core.c:151
#9  write_rsp_regs.constprop.72 (address=<optimized out>, value=<optimized out>, mask=<optimized out>, opaque=0x7ffff73fc728 <g_dev+17834408>) at ../../src/device/rsp/rsp_core.c:219
#10 0x00007ffff60bb6f6 in SW (op=<optimized out>, r4300=0x7ffff62fa580 <g_dev>) at ../../src/device/r4300/mips_instructions.def:412
#11 InterpretOpcode.lto_priv.636 (r4300=r4300@entry=0x7ffff62fa580 <g_dev>) at ../../src/device/r4300/pure_interp.c:688
#12 0x00007ffff60bc49e in JR (op=<optimized out>, r4300=0x7ffff62fa580 <g_dev>) at ../../src/device/r4300/mips_instructions.def:1031
#13 InterpretOpcode.lto_priv.636 (r4300=0x7ffff62fa580 <g_dev>) at ../../src/device/r4300/pure_interp.c:204
#14 0x00007ffff60d19c3 in run_pure_interpreter (r4300=<optimized out>) at ../../src/device/r4300/pure_interp.c:737
#15 run_r4300 (r4300=<optimized out>) at ../../src/device/r4300/r4300_core.c:153
#16 run_device (dev=<optimized out>) at ../../src/device/device.c:114
#17 main_run () at ../../src/main/main.c:1133
#18 0x00007ffff6091320 in CoreDoCommand (Command=<optimized out>, ParamInt=<optimized out>, ParamPtr=<optimized out>, ParamPtr=<optimized out>, ParamInt=<optimized out>, 
    Command=<optimized out>) at ../../src/api/frontend.c:225
#19 0x0000000000402c8d in ?? ()
#20 0x00007ffff7823f6a in __libc_start_main () from /usr/lib/libc.so.6
#21 0x00000000004037ea in ?? ()

**Comment by loganmc10** [comment]
I assume that's why @olivieryuyu wanted to test out this game. I know Project64 disables HLE for this game, I think it has some issues https://github.com/project64/project64/pull/968

You could potentially try CXD4's RSP in HLE video mode. I think it potentially has the same thing going on as Resident Evil 2, where there are some RSP tasks that need to be handled in LLE

**Comment by loganmc10** [comment]
Yeah when I try with cxd4-rsp HLE video, it doesn't crash, but the screen is blank (I can hear the audio). It needs to be in LLE mode to see the video at the beginning of the game.

**Comment by olivieryuyu** [comment]
i dunno how to change CountPerOp=1 but fine. 

This game uses a specific ucode for movies, hence it does not work in HLE (yet).
