### ISSUE TITLE
Vigilante 8: Second Offense Screenshots/Save States don't work.

### ISSUE THREAD

**Issue by AmbientMalice** [mupen64plus/mupen64plus-core#398]
Basically, when I try to take a screenshot of the game, I get an empty file named "v8". The first game works fine. This is with Angrylion's, BTW, since other plugins tend to crash or not work at all.

Additionally, save states don't seem to work for this game.

**Comment by loganmc10** [comment]
I had no issues with savestates, but I could reproduce the issue with the screenshots. I assume it's because there is a ```:``` in the internal name, Turok 3 has the same issue for instance
