### ISSUE TITLE
Custom Robo V2 freeze

### ISSUE THREAD

**Issue by loganmc10** [mupen64plus/mupen64plus-core#402]
First reported here:

https://github.com/gonetz/GLideN64/issues/1583

After you start a game, the screen stays blank and the music loops.

It seems to possibly be related to EEPROM saving? The save screen acts differently in Project64. In mupen64plus, it seems to think that you already have 3 save files (with blank names), if you click on one, it acts like there is an existing save game (it doesn't ask you to name it). If you choose "overwrite" (the 2nd option), when you pick a name, it'll copy that name over all 3 saves.

Project64 starts with 3 empty saves, if you click on one, it'll ask you to name it, and that name will only apply to the save you chose.

Mupen64 0.5.1 has a similar issue, although it behaves slightly differently. When you first start, it has no saves (good), and you can name one, but the game will still lock up. If you close and go back into the game, you'll see that it copied the name of your save over all 3 saves.

**Comment by loganmc10** [comment]
Oh easy fix, just needed to correct the save size! https://github.com/mupen64plus/mupen64plus-core/pull/403 @AmbientMalice

**Comment by AmbientMalice** [comment]
Good job.
