### ISSUE TITLE
Cant use emulation?

### ISSUE THREAD

**Issue by sillyname396** [mupen64plus/mupen64plus-core#408]
Every time I open the emulator, a console appears and immediately crashes after. Can anyone help?

**Comment by loganmc10** [comment]
Can you provide more details? Where did you get the emulator from? What OS are you using?

Can you try the build at: https://m64p.github.io

**Comment by richard42** [comment]
I assume you are using Windows? the default front-end application that we ship is command-line only, so you need to run it from the terminal.
