### ISSUE TITLE
Mischief Makers - Framerate halved

### ISSUE THREAD

**Issue by Krusher97** [mupen64plus/mupen64plus-core#409]
Windows 64-bit build download from here : https://m64p.github.io/
In Mischief Makers the framerate drops from 60FPS to 30FPS in level 2-3. This happens in both Angrylion and GlideN64. The GlideN64 OSD even shows that the game is running at 100% speed. This causes a very visible slowdown which is not present on the actual console.
Speedrun of the level : https://youtu.be/RSAqQB5mlH4?t=6m56s
Random lets play of the level on a real N64 : https://youtu.be/aYK4XdfErHs?t=10m1s
Video of the game running on the emulator : https://my.mixtape.moe/xktdrg.webm
Recording of a console : https://my.mixtape.moe/fqlijm.mp4

**Comment by loganmc10** [comment]
Can you post a save state?

This is an old, old issue, there is a bug report from 2008 saying the same thing:

https://github.com/mupen64plus/mupen64plus-user-issues/issues/71#issuecomment-130953267

Does it happen in Project64?

**Comment by AmbientMalice** [comment]
I just tested with Project 64. Setting Counter Factor to 1 appears to eliminate the slowdown, but I'm unsure whether it could potentially have negative side effects elsewhere. (Timers, for example.)

**Comment by loganmc10** [comment]
@Krusher97 do you know how to modify the CountPerOp setting in mupen64plus? It's in the core settings.

In mupen64plus-gui, you go to Settings->Core and Plugin Settings. In the "Core" tab, scroll down near the bottom and change "CountPerOp" from 0 to 1. Can you let me know if that solves the issue?

**Comment by Krusher97** [comment]
That seems to have eliminated the slowdown. Couldn't find any issue with the timer either.

**Comment by loganmc10** [comment]
Ok I created https://github.com/mupen64plus/mupen64plus-core/pull/410 to make CountPerOp=1 the default for that game
