### ISSUE TITLE
Interpreter fails CP1ROUND test

### ISSUE THREAD

**Issue by loganmc10** [mupen64plus/mupen64plus-core#416]
There is a GitHub repo with a number of tests for the N64 (they work on a real N64)

https://github.com/peterlemon/n64

Both the pure and cached interpreter fail the CP1ROUND test. The x64 dynarec passes

![cpu_test_cp1_round-000](https://user-images.githubusercontent.com/848146/31059103-4ca8404c-a6bc-11e7-9f24-5096b7e3abb2.png)

You see that it fails when the number contains .5. I believe we need to apply this fix:

https://github.com/project64/project64/commit/c3d89e8fc159c712a8383bb97c031bc84754ff38#diff-a3fced380b590e285b58bafe8a066149

**Comment by Narann** [comment]
krom's roms are awesome. Interesting.
