### ISSUE TITLE
UI-Console Error: LoadLibrary('mupen64plus.dll') error: The specified module could not be found. 

### ISSUE THREAD

**Issue by Danfun64** [mupen64plus/mupen64plus-core#429]
It's probably a matter of a missing dll. When I compile things with msys2 I have to copy the required dlls by hand from the msys2 directories. http://paste.debian.net/989663/

Here is what is in my mupen64plus folder:

.\ini\GLideN64.custom.ini
.\ini\GLideN64.ini
.\mupen64plus.exe
.\libfreetype-6.dll
.\libsamplerate-0.dll
.\mupen64plus.dll
.\mupen64plus-audio-sdl.dll
.\mupen64plus-input-sdl.dll
.\mupen64plus-rsp-cxd4-sse2.dll
.\mupen64plus-rsp-hle.dll
.\mupen64plus-video-GLideN64.dll
.\mupen64plus-video-z64.dll
.\SDL2.dll
.\InputAutoCfg.ini
.\mupen64plus.ini
.\mupencheat.txt
.\font.ttf

**Comment by loganmc10** [comment]
It looks like you're probably missing libpng. If it works in the msys2 shell but not in CMD then you know you're missing a DLL. Doing an ldd inside msys2 should tell you all the DLLs it depends on, all the ones inside the /mingw64/ folder need to be copied

**Comment by loganmc10** [comment]
You probably need a few others like libgcc_s_seh-1.dll as well

**Comment by Danfun64** [comment]
I passed all the LDD requirements for mupen64plus.exe http://paste.debian.net/989676/
LDD'ing mupen64plus.dll however... http://paste.debian.net/989678/

**Comment by loganmc10** [comment]
Yeah so all the stuff with the /mingw64/bin/ prefix needs to be copied over

**Comment by loganmc10** [comment]
Alternatively, if you're just doing this for yourself, you can probably just add the full/actual path to /mingw64/bin/ so the Windows environment variable that controls the library path (whatever the Windows equivalent to LD_LIBRARY_PATH is)

**Comment by Danfun64** [comment]
That solved the loading issue... but one last thing worth noting. "Core Warning: ROM Database: Unknown property on line 3127" The line says "Transferpak=Yes" and it's the only time that line exists in the .ini

Thought it was worth noting

**Comment by bsmiles32** [comment]
The transferpak warning will go away after the si refactoring is merged.
