### ISSUE TITLE
Bomberman 64 is freezing as of latest

### ISSUE THREAD

**Issue by fzurita** [mupen64plus/mupen64plus-core#432]
@Gillou68310 With somewhat recent changes, Bomberman 64 is freezing right after the first screen with the ARM new dynarec. It works fine in interpreter mode.

**Comment by loganmc10** [comment]
Probably related to https://github.com/mupen64plus/mupen64plus-core/issues/385

**Comment by fzurita** [comment]
Ok, I'll close this one.
