### ISSUE TITLE
MRC - Multi Racing Championship missing ground with new dynarec

### ISSUE THREAD

**Issue by fzurita** [mupen64plus/mupen64plus-core#433]
Once a race is entered, there are big sections on the ground that are missing. The issue is very easy to see, just start a race.

It works fine in interpreter mode.

**Comment by fzurita** [comment]
To gear hyper bike seems to have the same issue with the ground.

**Comment by Gillou68310** [comment]
@fzurita is this still an issue with https://github.com/mupen64plus/mupen64plus-core/pull/871?

**Comment by fzurita** [comment]
This is fixed with #871.
