### ISSUE TITLE
Should mupen64plus switch to big-endian format for raw saves?

### ISSUE THREAD

**Issue by Mastergatto** [mupen64plus/mupen64plus-core#434]
Hi to everyone, I don't know if this this has already been discussed here and I didn't find anything, but currently mupen64plus seems to use little endian format for the **raw** save files. This way, any save file that have been imported from original cartridges won't work on mupen64plus and vice versa, as I have painfully discovered this few minutes ago. 

IMHO, this is just wrong and I believe mupen64plus should switch to the native format so that it matches the N64 (big endian). Thoughts?

**Comment by loganmc10** [comment]
I think it would be worthwhile automatically dealing with big endian saves, but we certainly can't just switch the default format. If we did that, our saves would be incompatible with every other N64 emulator, whereas now they can be used universally.

But certainly it wouldn't hurt to automatically detect a big endian save and flip it to little endian before using it, then flipping it back when saving

**Comment by bsmiles32** [comment]
I'm not sure how we could detect the endianness of the saves automatically since it can have (as far as I know) arbitrary content. Do you have something in mind for that ? Is there any "header" or any kind of structure in these files that could be used for endianness detection ? Otherwise the problem becomes non-trivial and might require some heuristics or some machine learning.

**Comment by loganmc10** [comment]
Yeah I'm not sure how it would be accomplished, might not be possible. Might be helpful if a tool existed in the tools/ at least, but I think some of the dumping tools already swap the endianess, which is probably how n64 ended up with byte swapped ROMs and save files in the first place

**Comment by Mastergatto** [comment]
> If we did that, our saves would be incompatible with every other N64 emulator, whereas now they can be used universally.
Yeah, that would be very inconvenient, unfortunately :/ However, there's CEN64 that accepts ROMs and raw saves only in the big endian format, so not all emulators behave in this way.

If there's no way to detect and swap the order reliably, may I suggest that there should be an option, to be enabled manually, that changes the way a save file should be read by the emulator?

**Comment by loganmc10** [comment]
Yeah I think that'd be a decent solution

**Comment by AmbientMalice** [comment]
Why not use little endian unless the save file is given a .big extension? That way people wanting to import saves from other emulators could simply rename the file. I mean, they already have to do that because different emulators use different naming conventions.

**Comment by richard42** [comment]
I would recommend leaving the core alone but providing a tool to swap endianness in the tools folder. I agree in principle that the files should be in big endian format, but it's not worth the complexity of supporting both ways at this point.
