### ISSUE TITLE
Mario 64 Star Revenge New dynarec game freezes

### ISSUE THREAD

**Issue by fzurita** [mupen64plus/mupen64plus-core#438]
When using the new dynarec, Mario 64 Star revenge freezes when going into pipes. It works fine while using interpreter, so it's probably a bug with the new dynarec. Here is a save state, just go into the pipe:
[STAR REVENGE 1.5 (unknown rom).st0.zip](https://github.com/mupen64plus/mupen64plus-core/files/1385179/STAR.REVENGE.1.5.unknown.rom.st0.zip)

**Comment by fzurita** [comment]
@retrobenny Can you check if this still happening?

**Comment by retrobenny** [comment]
Which exact version of Star Revenge 1.5 is it?
I can't find a particular version because its also called redone 2.1 and there is an update to it from 1 month ago.

**Comment by fzurita** [comment]
Actually, I have no idea, I was going you would know since you originally reported the issue.

**Comment by retrobenny** [comment]
I tested the updated version for a while and didn't run into any freezes on pipes for course 1 and 2 but I don't know about any of the other pipes besides the ones inside levels like the course 2 secret that leads to the wing cap because I have yet to reach another pipe that is really high up.

**Comment by fzurita** [comment]
Cool, I'll assume fixed until found otherwise.

**Comment by retrobenny** [comment]
I got a single freeze after switching to Rice when playing the Rainbow Road themed level but the freeze is really inconsistent because I can't recreate the freeze.
I am at a total of 113 stars out of a possible 125 in that sm64 "mod" .

**Comment by retrobenny** [comment]
Stupid changes to github broke editing! >:(

I got a single run of a freeze after switching to Rice via entering the pipe when playing the Rainbow Road themed level (though I used a save state load to enter the pipe in different angles to avoid the freeze) but the freeze is really inconsistent because I can't recreate it after then.
I am at a total of 113 stars out of a possible 125 in that sm64 "mod" .

**Comment by fzurita** [comment]
Ok, interesting. That would seem almost like a deferent problem.

**Comment by retrobenny** [comment]
Finished it will all 125 stars with no further freezing.
