### ISSUE TITLE
Banjo-Tooie freeze

### ISSUE THREAD

**Issue by loganmc10** [mupen64plus/mupen64plus-core#441]
This was reported to me by a user on Discord. Here is a save state to reproduce the issue:

[Banjo-Tooie (U) [!].zip](https://github.com/mupen64plus/mupen64plus-core/files/1391663/Banjo-Tooie.U.zip)

If you keep walking back and forth through the door (you can just hold "down" on the analog stick), eventually it'll freeze (can take a number of tries). I tested with the x64 dynarec and cached interpreter. I also tested an Aug 19 build (before some of the timing changes and PIF re-write), still happens.

In my Googling it seems that Tooie freezing has been a persistent issue in PJ64 over the years, and mupen64plus has run into a few issues in the past (https://github.com/mupen64plus/mupen64plus-user-issues/issues/101) (however I tried an older build with DelaySI disabled and it still froze)

In some of my reading people seem to blame not-quite-accurate emulation of CIC-6105, I did notice that ```process_cic_challenge()``` executes every time you go through the door, so that may be something

EDIT: I should clarify when I say "freeze" I mean that the emulator gets stuck in some kind of endless loop, and just sits at a black screen, you can still hear the music playing

**Comment by AmbientMalice** [comment]
Wasn't the anti-piracy tech on Tooie properly reverse engineered a few years ago? What happened with that?

**Comment by Krusher97** [comment]
Creating a save state and loading it while its frozen seems to unfreeze it.

**Comment by loganmc10** [comment]
> Wasn't the anti-piracy tech on Tooie properly reverse engineered a few years ago? What happened with that?

Yeah it was reversed around 2011 I think, it's included in mupen64plus (https://github.com/mupen64plus/mupen64plus-core/blob/master/src/device/si/n64_cic_nus_6105.c), I'm not sure that the CIC is the issue, it's just a theory I see brought up by a few people I found on Google

**Comment by Krusher97** [comment]
Couldn't replicate this in PJ64 after 10 minutes of transitioning through the door at 500% speed.

**Comment by loganmc10** [comment]
I've messed around with this a bit but I haven't found any real solution. I can confirm that hitting F5/F7 to create/load a save state will allow you to "break free" of the lockup. I wonder if there is potentially something wrong with the interrupt system, given that a save state allows you to get around the issue

**Comment by Alkaris** [comment]
I've been having this issue with Banjo-Tooie and the log throws these messages when it happens.

```
Frontend: INFO: using Input plugin: 'Mupen64Plus SDL Input Plugin' v2.5.0
Frontend: INFO: using RSP plugin: 'Hacktarux/Azimer High-Level Emulation RSP Plugin' v2.5.0
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 315, in 'calling callback function'
  File "/usr/local/lib/python2.7/dist-packages/m64py-0.2.5-py2.7.egg/m64py/core/vidext.py", line 139, in gl_set_attr
    set_attr = attr_map[attr]
KeyError: 13
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 315, in 'calling callback function'
  File "/usr/local/lib/python2.7/dist-packages/m64py-0.2.5-py2.7.egg/m64py/core/vidext.py", line 139, in gl_set_attr
    set_attr = attr_map[attr]
KeyError: 11
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 315, in 'calling callback function'
  File "/usr/local/lib/python2.7/dist-packages/m64py-0.2.5-py2.7.egg/m64py/core/vidext.py", line 139, in gl_set_attr
    set_attr = attr_map[attr]
KeyError: 12
```

using M64Plus Core v2.5.0

**Comment by dword-design** [comment]
Why is the issue closed? Have the same.

**Comment by ScarfKat** [comment]
This issue is closed despite it not being fixed. I would like to request it be re-opened.

I've been playing Tooie with the exact same issue lately. It happens very often in Glitter Gulch Mine, or when walking from Spiral Mountain to Jinjo Village after defeating Klungo in that first boss battle cave.
