### ISSUE TITLE
No longer supporting Raspberry Pi?

### ISSUE THREAD

**Issue by cxbrettbaker** [mupen64plus/mupen64plus-core#442]
Older commits of this development used to work on the raspberry pi, but since the jump to newer SDL, none of the updates have worked. Are future commits of this emulator not going to include support for the Pi and other such devices?

**Comment by loganmc10** [comment]
Do you have any specifics? It works on Android (arm), it should work on a Pi. What doesn't work?

**Comment by cxbrettbaker** [comment]
Ah never mind, the error was on my behalf. Thank you for your help logan, and thank you for your amazing work in the community.
