### ISSUE TITLE
Turok: Dinosaur Hunter not responding to inputs.

### ISSUE THREAD

**Issue by AmbientMalice** [mupen64plus/mupen64plus-core#452]
Basically nothing works. Can't skip intro, can't move in menus. Controller pak menu on boot seems to work, though.

**Comment by loganmc10** [comment]
I'll bisect this in a bit, I see this printed over and over in the log:

```
Core Warning: Unexpected command format 00 00 ff
```

So it may be related to the PIF refactorings. It may also be related to the recent changes I made to the SI flags. Anyway I'll bisect it in a bit.
