### ISSUE TITLE
Waialae Country Club won't save

### ISSUE THREAD

**Issue by Enker** [mupen64plus/mupen64plus-core#456]
This game needs Sram forced in the settings, but M64P seems to ignore it and use auto-detection instead.
It will show a Controller Pak screen if it has the wrong save type, but this game doesn't actually support the Controller Pak. PJ64 needs Sram forced for this game as well.

**Comment by loganmc10** [comment]
Yeah I see what we're doing wrong here, I'll submit a PR in the next day or so

**Comment by Enker** [comment]
I found another odd thing with this game. If the .sra file is zero-filled, then the game options will all be OFF by default.

Filling the file with any non-zero data makes it behave normally. You can also select Setup Data/Initialize Data to fix the options.

**Comment by loganmc10** [comment]
Is it the same in Project64? I've wondered about this kind of thing actually. I mean it's feasible that the manufacturer could have shipped the game with the SRAM pre-populated with some data, the ROM file wouldn't contain that information

**Comment by Enker** [comment]
I tested with PJ64. I assume it's the same with M64P.

**Comment by loganmc10** [comment]
Yeah it's the same in M64P. I don't really know much about sram/flashram. I know for the mempaks we do initialize it with non-zero data:

https://github.com/mupen64plus/mupen64plus-core/blob/master/src/device/controllers/paks/mempak.c#L35-L54

But I have no idea where that information came from, I assume somebody figured it out by reading the data off a fresh mempak.

Like I said, as far I understand, the manufacturer could have shipped this game with the SRAM pre-populated with some data, there is really no way for us to know. Even if we found somebody with a cartridge, it's not going to be a "fresh" cartridge, so I don't know how we'd ever figure this one out

**Comment by loganmc10** [comment]
Actually now that I look, both the eeprom and flashram are actually initialized with all 1's, but the sram is given all 0's.

Initializing the sram to all 1's like is done with eeprom/flashram fixed the issue. I'll need to test the other sram games to make sure there are no issues there

**Comment by Enker** [comment]
Cool. I'm not sure what data the real carts have. In order to check it, we'd need a backup from a game that doesn't use the entire 32KB of Sram.
