### ISSUE TITLE
FlashRam saving fails in Derby Stallion 64

### ISSUE THREAD

**Issue by Enker** [mupen64plus/mupen64plus-core#458]
Just keep pressing A to test the saving. PJ64 fixed this issue by changing the "flash status" bytes. They also have a RDB setting to make the (Beta) rom boot.

According to the cartridge reader tool made by sanni, there are three different flash chips used by N64 games. https://github.com/sanni/cartreader

Can these be detected by M64P? They each have a slightly different flash status, so it might help other games as well.

**Comment by bsmiles32** [comment]
Fixed with PR #460
