### ISSUE TITLE
Ide Yousuke no Mahjong Juku - black screen

### ISSUE THREAD

**Issue by Enker** [mupen64plus/mupen64plus-core#462]
You can hear the title screen audio, but after pressing Start, it won't respond to any button. Changing the CPU/Count settings didn't help. This seems to be an old bug, v2.5 also has it.

**Comment by loganmc10** [comment]
What graphics plugin are you using?

**Comment by Enker** [comment]
I tried angrylion-plus and GLideN64.

**Comment by loganmc10** [comment]
I found a custom RDB for Project64 that had this cheat for this game:

```
Cheat0=8100363C 2400
```

I confirmed that using that cheat code allows the video to appear. As some point between 2010/2011 and now, Project64 fixed the root issue and no longer needs this cheat.

So either we need to bisect how PJ64 fixed the issue, or figure out what that cheat code does and work backwards from that

**Comment by Enker** [comment]
Great! I'm glad it wasn't too difficult to track down how PJ64 fixed it.
