### ISSUE TITLE
Audio cracks in Banjo Kazooie

### ISSUE THREAD

**Issue by Papermanzero** [mupen64plus/mupen64plus-core#463]
I am using the 32bit build together with M64Py.
The audio plugin from this build is working without any issues:
https://bitbucket.org/ecsv/mupen64plus-mxe-daily/get/2017-10-02.zip
But with the newest plugin from the recent build the audio cracks in some games (e.g. Banjo Kazooie)
https://bitbucket.org/ecsv/mupen64plus-mxe-daily/get/2017-10-28.zip

Only start Banjo Kazooie. The opening with the walking N64 Logo has already audio cracks.
After downgrading the audio plugin the cracks were gone.

**Comment by loganmc10** [comment]
So you've narrowed this down to the aduio plugin? You left everything else as current and downgraded only the audio plugin and that fixed the issue correct?

**Comment by Papermanzero** [comment]
Correct

**Comment by loganmc10** [comment]
I was able to reproduce this. I believe it started in this commit: https://github.com/mupen64plus/mupen64plus-audio-sdl/commit/b94cbf656ff69dabcee88eee0bbb7e8134546337 @bsmiles32 

hopefully someone can confirm that since my ears aren't always great at hearing minor audio issues

**Comment by bsmiles32** [comment]
Looks like my ears are even worse than yours as I can't really reproduce this regression...
And just by looking at the incriminated commit I can't see anything wrong with it.

Could you provide your audio configuration so I can use the same on my end ? Maybe that would help.
(resampler, primary buffer size, target, secondary buffer size, audio_sync, ...)

Thanks

**Comment by Papermanzero** [comment]
Please find attached a video, which shows the issue
https://youtu.be/5f3UBHLtSyA

You can clearly hear the difference.

**Comment by bsmiles32** [comment]
Thanks for replying. Will look into it.

**Comment by bsmiles32** [comment]
I can indeed reproduce the issue now that I use the same resampler than you (src-sinc-best-quality).
I bisected this regression to commit b94cbf656ff69dabcee88eee0bbb7e8134546337 "Extract sdl_backend data".
Now I'm trying to find where it broke...

**Comment by bsmiles32** [comment]
See PR https://github.com/mupen64plus/mupen64plus-audio-sdl/pull/21

**Comment by bsmiles32** [comment]
Closing this as PR has been merged. You can re-open it if you encounter again this issue.

**Comment by Papermanzero** [comment]
No it is not fixed. 
Tried the newest build.

**Comment by loganmc10** [comment]
@Papermanzero where do you get the build from?

**Comment by Papermanzero** [comment]
From bitbucket as usual. It mirrors the github source

**Comment by Papermanzero** [comment]
Sorry this was my fault. I updated the graphic driver (nvidia) and the driver activated the energy saving setting. Therefore I lost frame which resulted in audio drops. 
However after fixing my driver issue (deactivating energy savings) the audio cracks are gone.
So the changes in the plugin fixed the issue.
