### ISSUE TITLE
Some devices are failing CoreStartup with M64ERR_NO_MEMORY

### ISSUE THREAD

**Issue by fzurita** [mupen64plus/mupen64plus-core#467]
@bsmiles32 It seems like recent change is breaking many Android devices. Specifically this commit:

https://github.com/mupen64plus/mupen64plus-core/commit/143cfa7139faf757c7d0e508291e34c24a1fecbc#diff-fa9734f1550e974c80b15a8a6fed3ad7

A lot of devices are failing with ```M64ERR_NO_MEMORY``` on CoreStartup.

Is there any way to fallback to the old behavior if we are unable to allocate that much RAM?

So far this error has been limited to Samsung devices.

**Comment by bsmiles32** [comment]
I think the problem here is that either for their device overcommitting is disabled or that their malloc implementation doesn't use an anonymous mmap internally. I think replacing the malloc/free with mmap/munmap (VirtualAlloc/VirtualFree for Win32) will fix this. Will do a PR when I get back home.

**Comment by fzurita** [comment]
The above didn't work for them, it instead crashed when accessing the memory. I'm having them try your pull request next.

**Comment by bsmiles32** [comment]
@fzurita Can you try this : https://github.com/mupen64plus/mupen64plus-core/pull/474

**Comment by bsmiles32** [comment]
@fzurita Can you try this : https://github.com/mupen64plus/mupen64plus-core/pull/474

**Comment by bsmiles32** [comment]
@fzurita Can you try this : https://github.com/mupen64plus/mupen64plus-core/pull/474

**Comment by fzurita** [comment]
Ok, I'll let you know when I can.
