### ISSUE TITLE
mupen64plus save/screenshot/config folder change on macOS

### ISSUE THREAD

**Issue by StenApp** [mupen64plus/mupen64plus-core#484]
Wanted to open an issue since macOS uses different folders than Win or Linux:

https://developer.apple.com/library/content/documentation/CoreFoundation/Conceptual/CFBundles/Introduction/Introduction.html#//apple_ref/doc/uid/10000123i

the "bin" file goes in the app bundle under `Mupen64Plus.app/Contents/macOS`
mupen64plus-core.dylib and plugins should be in `Mupen64Plus.app/Contents/Frameworks`
mupen64plus should save saves, logs and configs to `~/Library/Application Support/<app-identifier>`
There is a info.plist file needed under `Mupen64Plus.app/Contents` to set an icon for the bundle or the version

**Comment by StenApp** [comment]
where can I change the fixed paths? in the osal files?

**Comment by richard42** [comment]
The place to modify this behavior is in the "osal_get_user_configpath" function inside of:

src/osal/files_unix.c

**Comment by StenApp** [comment]
Thank you for the info.
What I want to do is, if I compile for macOS then,

use `~/Library/Application Support/mupen64plus`
and place files there, saves, config, etc

I guess I need to change the functions
```
osal_get_shared_filepath
osal_get_user_configpath 
osal_get_user_datapath

```
and set the datasearchpath too.

No need for folders:

.local/share/mupen64plus/
.cache/mupen64plus/

or the search paths
```
/usr/local/share/mupen64plus 
/usr/share/mupen64plus
./
```

**Comment by richard42** [comment]
The data searchpath should really be in the bundle. We're probably not packaging this stuff correctly for macos right now, but I guess the dylibs should go in Frameworks, and the data/ini files in Resources? There is a script somewhere (maybe in Tools?) for generating a macos bundle, but it may be out of date now.

osal_get_shared_filepath already has a special case for macos, but we should also add special cases for osal_get_user_configpath, osal_get_user_datapath, and osal_get_user_cachepath.

**Comment by StenApp** [comment]
I made a build.sh correction, that it builts correctly:
https://github.com/m64p/mupen64plus-GLideN64/pull/37

**Comment by StenApp** [comment]
Fixes for the paths

https://github.com/mupen64plus/mupen64plus-core/pull/495

**Comment by StenApp** [comment]
Update on paths...https://github.com/mupen64plus/mupen64plus-core/pull/495

**Comment by StenApp** [comment]
@richard42 please look over my code, is it right with the char things I added?

**Comment by StenApp** [comment]
Take it or leave it, I'm out of it, for my MacBook Pro retina its broken64plus, graphics doesn't work.

**Comment by richard42** [comment]
I have the first gen macbook pro retina (2012) and both rice and glide64mk2 work on this machine. Do you want me to send you the bundle for testing?
