### ISSUE TITLE
International super star soccer 2000 keeps stalling

### ISSUE THREAD

**Issue by fzurita** [mupen64plus/mupen64plus-core#486]
This game acts very strange. I have tried switching video plugin, RSP,  dynarec/interpreter, and it hasn't fixed the issue. So the problem is probably in the core. The game seems to have random pauses. The problem is easy to see, just start a match.

**Comment by loganmc10** [comment]
I just played a couple minutes on my PC (2 different matches), I didn't see any issues:

```
Core: Goodname: International Superstar Soccer 2000 (U) (M2) [!]
Core: Name: I.S.S.2000          
Core: MD5: 23A4ED8D79882594206173B1D476F0E9
Core: CRC: 8E835437 CD5748B4
```

perhaps the CPU on your device can't keep up? However I looked at the CPU usage in the task manager and it doesn't seem to be too demanding of a game.

**Comment by fzurita** [comment]
Strange issue. I have a fairly fatty device. Maybe it had to do with the frame limiter. I'll investigate some more.

**Comment by fzurita** [comment]
Ok, I think my CPU was throttling or something. I restarted my phone and the issue went away. Closing.
