### ISSUE TITLE
FBInfo missing some data with dynarec

### ISSUE THREAD

**Issue by loganmc10** [mupen64plus/mupen64plus-core#493]
To reproduce: Use the latest master of both mupen64plus-core and GLideN64. Launch Super Mario 64 with the dynarec, the head is missing:

![super_mario_64-000](https://user-images.githubusercontent.com/848146/33468844-60037190-d61c-11e7-92f6-3b7af8927e97.png)

It appears when using the Interpreter, therefore the dynarec must be missing some of the reads/writes that FBInfo should be intercepting

**Comment by bsmiles32** [comment]
Uncommenting INTERPRET_LWC1 in x86_64/interpret.h makes Mario Face appear again.
