### ISSUE TITLE
No 64 bit ARM library support with new dynarec

### ISSUE THREAD

**Issue by fzurita** [mupen64plus/mupen64plus-core#504]
Having no 64 bit ARM library support with the new dynarec will be troublesome in the future. Google will require 64 bit binaries as of August 2019. See this link:

http://android-developers.googleblog.com/2017/12/improving-app-security-and-performance.html

@Gillou68310 made significant progress in this branch:

https://github.com/Gillou68310/mupen64plus-core/tree/new_dynarec/wip/arm64_optim

Was it pretty close to the same level of support as the 32 bit new dynarec?

Also, has any work been done for the x86-64 new dynarec? I guess we could always fall back to the 64 bit old dynarec for x86.

**Comment by loganmc10** [comment]
I mean technically you could just not include the dynarec for the ARM64 version. It wouldn't really be useful but it would prevent the app from being de-listed or whatever they might do. Although I'm guessing ARM64 devices would be forced to use that dynarec-less binary

**Comment by fzurita** [comment]
Yeah, that would be the case. That would make it very slow unfortunately though for 64 bit devices...

**Comment by loganmc10** [comment]
It gets to be alot of maintenance, this is why Dolphin is 64bit only. We have 2 different dynarec systems which makes it even more complicated

**Comment by fzurita** [comment]
I'm not too familiar with the back story. Does anyone know if the new dynarec was fine just for ARM compatibility?
