### ISSUE TITLE
Building with LTO enabled makes loading save states crash

### ISSUE THREAD

**Issue by fzurita** [mupen64plus/mupen64plus-core#522]
When building with LTO enabled, and loading save states, the app crashes 100% of the time with majora's mask and conker.

I'm building for ARM, new dynarec, and for Android. I'm also using the clang compiler.

**Comment by fzurita** [comment]
Interpreter also crashes.

**Comment by loganmc10** [comment]
LTO has been the default on Linux for a long time. I assume this has something to do with how it's compiled on Android (wrong flags or something), or perhaps a compiler issue.

It's pretty "tried and true" on Linux. I'll try it using clang though

**Comment by fzurita** [comment]
I really doubt that compiler flags could cause a crash when loading save states and not when not loading a save state.

**Comment by loganmc10** [comment]
I just tested using clang, I tested Majora's Mask and Conkers, no issues saving or loading save states. This was on Fedora Linux. Tested the x64 dynarec and cached interpreter

**Comment by fzurita** [comment]
Hmmm, maybe there is a bug in the clang compiler that Android studio is using. I'll try to get a back trace.

**Comment by fzurita** [comment]
@loganmc10 did you ever test the x86 new dynarec?

**Comment by loganmc10** [comment]
I just tested Majora's Mask and Conkers on a 32-bit version of Ubuntu (in a VM) using the new dynarec, no issues with save states. I tested with GCC

I used to distribute the 32-bit Windows version of m64p with the new dynarec as well and never encountered any issues.

I thought the LTO flag didn't work in Android yet? Something with the NDK?

**Comment by fzurita** [comment]
The problems with the LTO flag and the NDK seem to be windows only. So building should work in Linux.

**Comment by fzurita** [comment]
Finally got back to this, here is the crash with LTO enabled:

```
********** Crash dump: **********
Build fingerprint: 'razer/cheryl/cheryl:7.1.1/NMF26X-RZR-180118/3005:user/release-keys'
pid: 14847, tid: 14876, name: ServiceStartArg  >>> paulscode.android.mupen64plusae.GameActivity <<<
signal 7 (SIGBUS), code 1 (BUS_ADRALN), fault addr 0xc877c9e6
#00 pc 0001dd30  ./libmupen64plus-core.so: Routine savestates_load_m64p at ./src/main/savestates.c:539
#01 pc 000ba054  ./libmupen64plus-core.so: Routine .E1 at linkage_arm.S:?
```

**Comment by loganmc10** [comment]
And it happens with interpreter too? Does it happen when loading a save state created by the interpreter?

**Comment by fzurita** [comment]
Actually, it seems related to this https://github.com/mupen64plus/mupen64plus-core/issues/536

**Comment by fzurita** [comment]
The performance improvement is not significant it seems anyways. I can also still compile everything else with LTO enabled.
