### ISSUE TITLE
GLP license text has outdated address

### ISSUE THREAD

**Issue by wberrier** [mupen64plus/mupen64plus-core#527]
The gpl license files have outdated FSF addresses.

This was caught by rpmlint during a fedora package review:

https://bugzilla.redhat.com/show_bug.cgi?id=1535549

The license with the correct address is located here:

http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt

This was found from the 2.5 release in several files, so I imagine several of the broken out subprojects also have the issue.

**Comment by richard42** [comment]
okay, fixed.
