### ISSUE TITLE
Log spam when loading save states: Unexpected command format 01 c4 01  

### ISSUE THREAD

**Issue by fzurita** [mupen64plus/mupen64plus-core#528]
Upon loading a save state with super mario 64, I'm getting massive core log spam with this text:
```
Unexpected command format 01 c4 01 
```

Here is the save state producing the issue. I have no idea what caused it.

[mario64_log_spam.zip](https://github.com/mupen64plus/mupen64plus-core/files/1692313/mario64_log_spam.zip)

**Comment by loganmc10** [comment]
I tested my own save state and the one you provided. I couldn't reproduce the issue, I didn't get any of those messages. Does it only happen with the new dynarec?

**Comment by fzurita** [comment]
Yep, you are right, it's only happening with the new dynarec.

**Comment by fzurita** [comment]
I think I have isolated this to having 4 controllers present.

**Comment by fzurita** [comment]
I think we need need a new label specifically for the new dynarec, there is a large collection of new dynarec issues.

**Comment by bsmiles32** [comment]
By just reading the issue description, this indeed sounds like the savestate being made with a different number of plugged controllers than when loaded. Maybe combined with a savestate made before the PIF refactoring (in which case there we can only do a "best effort" to reload PIF state). This is unfortunate, but as a workaround, just hex editing the saved pif ram could do the trick.

**Comment by fzurita** [comment]
Gotcha, I can tell you for sure that the save state was created after the PIF refactoring.

I can also tell you that it's true, the save state was created using one controller present, but when loaded, the number of controllers was set to 4.

**Comment by bsmiles32** [comment]
Quick question, can you test https://github.com/mupen64plus/mupen64plus-core/pull/535 against this issue ?

**Comment by fzurita** [comment]
Yep, will do

**Comment by fzurita** [comment]
Yep, your changes in #535 fixed this issue.

**Comment by bsmiles32** [comment]
Good !
