### ISSUE TITLE
Major League Baseball with Ken Griffey Jr. (Messed Up Splash Screens and Start Screen)

### ISSUE THREAD

**Issue by pdrome** [mupen64plus/mupen64plus-core#530]
Upon starting the game the splash screens tear/flash, and the start screen is incomplete.  The symptoms appear using angrylion or gliden64, when using cdx4 or hle rsp, and when using the dynarec, cached interpreter, and pure interpreter.

I'm using the February 5th 2018 release of m64p on Linux Mint 18.3, but the problem is the same in the mupen64plus core in retroarch.  parallel n64 in retroarch does not appear to have the issue.

I'm unsure how I can troubleshoot further. I'd be willing to dig deeper though with a few pointers.

**Comment by pdrome** [comment]
Video showing issue for reference.  Compares gliden64 and angrylion with mupen64plus. Parallel n64 is included as a reference as it appears to represent the console behavior well in this case.

[![Video showing issue](https://img.youtube.com/vi/DRhHEgIFscw/0.jpg)](https://www.youtube.com/watch?v=DRhHEgIFscw "Video showing issue")

**Comment by pdrome** [comment]
Brief video showing issue. Mupen64plus with both gliden64 and angrylion are compared against parallel n64, which appears to emulate the startup correctly in this case.

[![Video showing issue](https://img.youtube.com/vi/DRhHEgIFscw/0.jpg)](https://www.youtube.com/watch?v=DRhHEgIFscw "Video showing issue")

**Comment by loganmc10** [comment]
Project64 has the same behavior with both GLideN64 and Angrylion Plus, it seems to be a graphics plugin issue, not related to the emulator core.

**Comment by pdrome** [comment]
Interesting, my mistake.  I'm unable to run Project64 in Linux.  Maybe I can setup a VM next time.  Sorry about that.

So should post in angrylion plus and gliden64?

**Comment by loganmc10** [comment]
GLideN64 already has an issue about this:https://github.com/gonetz/GLideN64/issues/1664

Your video is helpful though and you could add it to that issue. I don't think angrylion plus has an open issue about this

**Comment by pdrome** [comment]
Crap, totally missed that.  I need to do a better job searching.  Thanks!
