### ISSUE TITLE
Bus error when loading savestate on odroid c2 (armhf)

### ISSUE THREAD

**Issue by Gillou68310** [mupen64plus/mupen64plus-core#536]
```
Thread 1 "mupen64plus" received signal SIGBUS, Bus error.
0xf3f1483c in savestates_load_m64p (dev=0xf43a5000 <g_dev>, filepath=0x12c308 "wdc.st0")
    at mupen64plus-armhf-prebuilt/src/mupen64plus-core/src/main/savestates.c:518
518             dev->cart.af_rtc.now = (time_t)GETDATA(curr, int64_t);
```

This is an alignement issue.
64bits values are loaded using the LDRD instruction, and the address has to be aligned to 4 bytes.

I would say that this is up to the compiler to not use LDRD with a potentially unaligned address but it seems to fail in this case.

@bsmiles32 I suggest keeping the ```curr``` pointer 4 bytes aligned using padding in order avoid such issues.

**Comment by bsmiles32** [comment]
Indeed keeping the fields aligned would be best, but this would require breaking existing format (not that it matters much to me, but this was reported several times recently). Another option would be to read this field byte-by-byte then build the full value with shifting (safer, but slower).

Also, shouldn't int64_t be 8-byte aligned (instead of just 4) ?

**Comment by Gillou68310** [comment]
> Also, shouldn't int64_t be 8-byte aligned (instead of just 4) ?

On 64bits arch yes but on 32bits LDRD is probably 2 LDR being atomic.

**Comment by Gillou68310** [comment]
But I agree when building for 64bits it would be safer to read/write two 32bits instead of one 64bits.

Since most values are 32bits I don't think the byte-by-byte solution is really necessary.

I know the format changed quite a few times recently but the sooner the better ;-)

**Comment by fzurita** [comment]
There is no need to break save state format. Save state format version can be incremented, if old version is detected when loading, use the old format.

That may mean cluttering up the code with loading functions for all the older formats, but the old formats could be kept in separate files.

**Comment by fzurita** [comment]
Related I think:
https://github.com/mupen64plus/mupen64plus-core/issues/522

**Comment by Gillou68310** [comment]
Yep most likely the same issue! I'm buiding with LTO

**Comment by fzurita** [comment]
Should this be closed?

**Comment by bsmiles32** [comment]
Closing as #545 should have fixed that. Please reopen if needed.
