### ISSUE TITLE
Is not longer possible to play using the keyboard

### ISSUE THREAD

**Issue by Jj0YzL5nvJ** [mupen64plus/mupen64plus-core#539]
Related to the new hot-plugging function, I guess...

P.S: I using PS/2 port.

**Comment by fzurita** [comment]
It sounds like an issues with mupen64plus-input-sdl.

**Comment by fzurita** [comment]
Here is the pull request:

https://github.com/mupen64plus/mupen64plus-input-sdl/pull/66/files

It seems to be marking a controller only as present if there is a joystick for that controller.... whoops.

**Comment by loganmc10** [comment]
@bsmiles32 I can confirm that keyboard input no longer worked, regression is from https://github.com/mupen64plus/mupen64plus-input-sdl/pull/66

**Comment by bsmiles32** [comment]
Made a PR [1] to revert breaking behavior until I can find some time to work on a proper solution.

[1] https://github.com/mupen64plus/mupen64plus-input-sdl/pull/67
