### ISSUE TITLE
Translucent textures in Zelda OOT

### ISSUE THREAD

**Issue by quicksilver7837** [mupen64plus/mupen64plus-core#540]
Using RPI3, just updated mupen64 plus from source. Playing Zelda oot using glide plugin. The pause screen menu delay seems to be fixed now, but now some textures seem translucent or out of place. Can be seen in Hyrule field. Link appears to be walking underneath of the path.

**Comment by loganmc10** [comment]
This is an issue with the graphics plugin, not mupen64plus specifically. You should file this issue with the RetroPie people

**Comment by mudlord** [comment]
Which will never get fixed.

**Comment by quicksilver7837** [comment]
Closed this issue as it's a RPI issue not mupen64plus
