### ISSUE TITLE
Speed limiter is slowing down way too much

### ISSUE THREAD

**Issue by loganmc10** [mupen64plus/mupen64plus-core#543]
The speed limiter is really slowing my game down, here is a screenshot with speed limiter off (FPS on bottom of the screen):

![screenshot_20180309-103117](https://user-images.githubusercontent.com/848146/37221592-c27fef66-2387-11e8-8d17-e2d92923a4d1.png)

And the exact same spot with the speed limiter on:

![screenshot_20180309-103124](https://user-images.githubusercontent.com/848146/37221630-dfd3dcda-2387-11e8-8c95-f2daeeea933e.png)

This was tested with the latest master of mupen64plus-ae. I tested "sync audio to video" on or off, same problem (I believe the use the same speed limiting logic).

We probably need to re-think our FPS limiter, there are lots of examples out there on the Internet, I'm going to try a few, but I thought I'd just put this out there for others to think about.

**Comment by fzurita** [comment]
Strange,  I don't have this problem. What speed limiter value are you using when this happens?

**Comment by loganmc10** [comment]
I just toggle between 100% and 250%

**Comment by fzurita** [comment]
is it only that part of the game? I'm at the dam level and 250% speeds the game up, not slow the game down.

**Comment by loganmc10** [comment]
Well that part of the level slows down, the other parts can maintain a proper refresh rate. 250 does speed it up, I get around 30FPS (full speed), with it set to 250, and 5-10 FPS with it set to 100

**Comment by fzurita** [comment]
It sounds like your phone has strange behavior with sleeps going on. Ideally, we should be able to trigger of the Vsync in the screen. Android allows you to do this, but mupen64plus doesn't have any way to hook into it because of the "main loop".

It would be nice to take the retro arch approach here and allow the front end to trigger the next iteration instead of the core doing the sleeping. Something like an "ExecuteVI" call.

**Comment by loganmc10** [comment]
Rogue Squadron is another one with this issue. With speed limiter set to 250%, I get around 50-60 FPS (the game runs at 30), but with speed limiter on I get around 20FPS, so the game is capable of running at full speed, but it's limiting it below that for some reason.

**Comment by loganmc10** [comment]
> Ideally, we should be able to trigger of the Vsync in the screen. Android allows you to do this, but mupen64plus doesn't have any way to hook into it because of the "main loop".

I don't think vsync is a viable solution, for one, PAL games run at 50FPS, and also, some Android phones actually have a refresh rate of 55-58, not 60.

**Comment by fzurita** [comment]
What if you set count per op to 1 in Golden Eye?

**Comment by fzurita** [comment]
Ok, this is interesting. I set Count per op to 1 for Rogue squadon and it runs at 30fps. If I leave it to default, it runs at 20fps.

**Comment by loganmc10** [comment]
It definitely performs a lot better, more like 20FPS with the limiter on instead of 5-10, and it goes 50-60 with the limiter off instead of around 30. So the performance is a lot better with CountPerOp=1, something to look into for that game, but the root issue with the speed limiter is still there.

**Comment by fzurita** [comment]
Are you sure it's not the game that is slowing down? Goldeneye has a variable FPS.

**Comment by fzurita** [comment]
Can you try it in PC and see if it behaves similarly with the "Swap frame buffers" option  set to "on buffer update"?

**Comment by Gillou68310** [comment]
This reminds me this issue https://github.com/gonetz/GLideN64/issues/592

**Comment by fzurita** [comment]
In @loganmc10's case, swapping buffers every VI update seems to make it faster instead of slower.

**Comment by loganmc10** [comment]
> Can you try it in PC and see if it behaves similarly with the "Swap frame buffers" option set to "on buffer update"?

Huh you are right, the game is actually limiting the FPS, on PC the VI/s is 60, but the FPS is like 15-17 in that spot in GoldenEye. I was testing this with the audio off on my phone, but with the audio on, I realize that the audio is smooth, it's just the video that is choppy, and yes, it's the game that is doing it, and yes, setting CountPerOp=1 fixes the issue/makes it alot better.

So yeah, the games are obviously limiting the FPS because they think the "N64" can't keep up, setting CountPerOp=1 is sort of like overclocking the CPU, so it doesn't do the limiting. This makes sense now, I remember noticing that when setting CountPerOp=3 in Conker's Bad Fur Day, it would start skipping frames.

@fzurita settings every VI update didn't actually make it faster, it did show maintaining 60 FPS (which makes sense), but it was faster because I still had CountPerOp=1 set, I forgot about that, the issue is the CountPerOp setting

**Comment by loganmc10** [comment]
We should probably look at setting CountPerOp=1 for some of these games (GoldenEye, Rogue Squadron, maybe Perfect Dark?)

**Comment by fzurita** [comment]
In Mupen64plus-AE I allow the user to change the CountPerOp setting. Making it 1 by default for this game scares me a little since it will make the game take more CPU, so it would slow down on slower devices.

**Comment by loganmc10** [comment]
True, at least now I know the issue

**Comment by fzurita** [comment]
I wonder how that area of the game behaves on a real N64. Did the FPS really go down to 5?

**Comment by loganmc10** [comment]
No probably not, CountPerOp=2 is probably not accurately reflecting the clock speed of the N64. It's probably a little slow. But it might have slowed down a bit, I can't remember.

That whole CountPerOp thing is terrible, but I don't know of a better way, if we had a better way to emulate that register, it would fix so many issues.

**Comment by fzurita** [comment]
I may be oversimplifying it or be completely off base, but wouldn't it be simple to fix for interpreter? Each instruction can increment the count register by the right amount. Is that what that register is keeping track of?

**Comment by loganmc10** [comment]
Basically yeah

>  It increments at a constant rate based on the clock cycle. On R4300ii, it will increment at one-half the PClock speed

The N64's "PClock" speed is 93.75 MHz, so that means this COUNT register should increment 46875000 every second.

The problem is, what if you're halfway through a second? What should the COUNT register be? Well it should be 46875000/2, but how do we tell when we are halfway through an "emulated second"?

So the idea with CountPerOp=2 I guess is that we are guessing that each operation takes 1 clock cycle (since COUNT increments 1/2 the clock cycle). So basically the COUNT register is counting the clock cycles, and each 2 clock cycles means the COUNT register should go up by 1.

If we can figure out, or have a decent guess, on how long each instruction took on average, then yes, we could probably use that, per instruction, instead of the generalized "2". 

I believe I got all that right, that's based on my understanding anyway

**Comment by fzurita** [comment]
I thought the R4300i was pretty well documented. So we should know how many clock cycles each instruction takes from some doc somewhere.

**Comment by loganmc10** [comment]
Maybe, I'm not sure, I know that one of PeterLemon's test ROM's is a timing one:

https://github.com/PeterLemon/N64/tree/master/CPUTest/CPU/TIMINGNTSC

PJ64 and mupen64plus fail every item on that test, I'm not sure where he got his timing values from @PeterLemon, do you have any information on how you created the TIMINGNTSC test ROM?

**Comment by pdrome** [comment]
@loganmc10 

It's very likely the timing is derived from RHW.  Checkout the readme:

https://github.com/PeterLemon/N64/blob/master/README.md

**Comment by pdrome** [comment]
I've been looking into this a bit more. To get similar results for each of the timing tests the CountPerOp setting needs to be set between (3 and 10) depending on the test being run. I'm not sure if this result makes sense just yet, but it is interesting.  CountPerOp = 3 to 10 seems like it would be really slow and buggy in many games.

Here's my data showing the range of timing results with each test. There are some weird results:

CPUTIMINGNTSC Timing Range: 00003EEC -> 0000DB1F
CountPerOp=1  :   000268CC -> 0004E3AC
CountPerOp=2  :   000271D6 (same for all tests)
CountPerOp=3  :   0000CD99 -> 0001A139
CountPerOp=4  :   00009A33 -> 000138EB
CountPerOp=5  :   00007B5C (same for all tests)
CountPerOp=10:   00003DAE (same for all tests)

CP1TIMINGNTSC Timing Range: 0000C340 -> 0000DB1F
CountPerOp=1  :   000268CD -> 0004E3AC
CountPerOp=2  :   000271D6 (same for all tests)
CountPerOp=3  :   0000CD99 -> 0000CD9A
CountPerOp=4  :   00009A33 -> 000138EB
CountPerOp=5  :   00007B5C (same for all tests)
CountPerOp=10:   00003DAE (same for all tests)

Given that we assign a constant counter to each instruction, shouldn't we get be getting the same answer for every test regardless of which CountPerOp setting we use?  Granted, the answer would be changed by the CountPerOp, but I think each test should return the same answer. This is particularly noticeable with CountPerOp = 1, 3, and 4. Each test loop within the assembly seems to do the same number of instructions every time if I'm reading it correctly.

I'm still trying to make some sense out of the numbers.  Any help is appreciated.

Between the CPUTIMINGNTSC and CP1TIMINGNTSC ROMs we are testing 82 instructions, but if I'm reading the r4300 src correctly there are around 212 total instructions. So this would be an incomplete subset if it comes from RHW. Perhaps some of those other instructions would time out correctly with CounterPerOp < 3.

Finally, I got the exact same results using the interpreter and dynarec.  I don't know anything about the dynarec, but that might imply we can define operation specific counts with it similarly to the interpreter.
