### ISSUE TITLE
Pokemon Puzzle League FMV not dealt with by RSP-HLE

### ISSUE THREAD

**Issue by loganmc10** [mupen64plus/mupen64plus-core#546]
This is not actually an issue with the core, but RSP-HLE doesn't have an issue tracker.

This is similar to the FMV in Resident Evil 2. The ucode isn't passed to the GFX plugin, it ends up here:

https://github.com/mupen64plus/mupen64plus-rsp-hle/blob/master/src/hle.c#L288

It works with rsp-cxd4 in hle mode because rsp-cxd4 handles it in LLE, not passing it to the GFX plugin:

https://github.com/mupen64plus/mupen64plus-rsp-cxd4/blob/master/module.c#L346

@Gillou68310 maybe a fun project for you?? ;)

**Comment by loganmc10** [comment]
Related:

https://github.com/gonetz/GLideN64/issues/663

**Comment by olivieryuyu** [comment]
I started to work on the hvqm ucode.

**Comment by Gillou68310** [comment]
Lol I started working on it too

**Comment by loganmc10** [comment]
Get on discord and chat with each other!

Or perhaps this is time for a friendly wager...

**Comment by olivieryuyu** [comment]
Ok I need to finish battle of naboo crazy commands first. Would u pick up this one Gilles? Ucode is not big (compared to Indy for instance)

After Naboo I would like to work on S2DEX issues. Hvqm ucode is not a priority for me.

**Comment by Gillou68310** [comment]
Yep no problem I already did half the job anyway ;-)

**Comment by olivieryuyu** [comment]
Cool thx! There is 2 versions of this ucode. One CPU and one RSP. Pokémon uses one version of the ucode and the Japanese game the other one. Gliden64 can display Pokémon but not Yakouchuu 2.

**Comment by Gillou68310** [comment]
Here's my work so far:
https://github.com/Gillou68310/mupen64plus-rsp-hle/commits/hvqm

N64 logo is rendering correctly, the rest of the video is using a part of the ucode which is not implemented yet (see SUBROUTINE3 in hvqm2sp1.txt)

[hvqm2sp1.txt](https://github.com/mupen64plus/mupen64plus-core/files/1819639/hvqm2sp1.txt)

**Comment by olivieryuyu** [comment]
Nice :)

Now one question which is still unclear to me:

is it the RSP or the graphic plugin to manage this task?

How in the HLE specs this should be defined?

Seems jpeg and video decoding is RSP in HLE. Not sure why though as it is part of the RSP if it is for displaying graphic.

**Comment by Gillou68310** [comment]
RSP tasks are filtered by its task type. Here's a list of RSP task type taken from rsp-cxd4

```
typedef enum {
    M_GFXTASK   = 1,
    M_AUDTASK   = 2,
    M_VIDTASK   = 3,
    M_NJPEGTASK = 4,
    M_NULTASK   = 5,
    M_HVQTASK   = 6,
    M_HVQMTASK  = 7
} OSTask_type;
```

Only gfx tasks should be forwarded to the video plugin, everything else should be processed by the rsp-plugin.

We also have the possibility of forwarding audio tasks to the audio plugin but this is not used in m64p

RE2 is a special case because the ```resize_bilinear_task``` is referenced as a gfx task but we are using a hack in order to process it in the rsp plugin.

**Comment by mudlord** [comment]
@Gillou68310 

Thats funny, never pictured you as anyone's martyr.

**Comment by Gillou68310** [comment]
I don't mind being someone's martyr if it serves my own good ;-)

**Comment by mudlord** [comment]
Harhar.

Very funny. :rage:

**Comment by olivieryuyu** [comment]
@Gillou68310 

Another question please

How the plugin can display the movie graphics if the RSP deals with the related ucode?

**Comment by Gillou68310** [comment]
The RSP plugin is writing the decoded video frame to a specific RDRAM address, this address will then be passed to the VI_ORIGIN register. The video plugin is using this information in order to draw the framebuffer.

**Comment by olivieryuyu** [comment]
I more or less understand, thanks!

**Comment by loganmc10** [comment]
@olivieryuyu someone can correct me if I'm wrong, but this task is a little different from a regular display list

Project64:
https://github.com/project64/project64/blob/f20dca31fdc43e71fd50c4c0888352e4c78a36c2/Source/RSP/Cpu.c#L240-L243

mupen64plus:
https://github.com/Gillou68310/mupen64plus-rsp-hle/blob/master/src/hle.c#L288-L290

So the code that actually gets executed for Pokemon is the "ShowCFB" function in the GFX plugin. For GLideN64 it should be this function:

https://github.com/gonetz/GLideN64/blob/9fb63e0460bea5ca54b9df082cc722fec41cf9d4/src/common/CommonAPIImpl_common.cpp#L211-L214

Hopefully that makes sense. @Gillou68310's plan was to bypass that function and implement the solution directly in the RSP plugin

**Comment by olivieryuyu** [comment]
I am about at 80% of the deciphering now. If needed Gillou can implement the ucode on the base of GlideN64 implementation.

**Comment by bsmiles32** [comment]
I would also strongly suggest implementing this ucode in the rsp-hle plugin as it will benefit all video plugins at once and it is more "logical" in the sense that it makes rsp-hle/rsp-cxd4 interchangeable.
I haven't looked at the details of this ucode, but it seems to decode frames and write them to RDRAM, so there should be no problem having it inside the rsp plugin as @Gillou68310 wip shows.
The way we currently handle task type 7 in the rsp plugin is very likely just a minimal stub inherited from  old times as @loganmc10 comment suggests.

**Comment by olivieryuyu** [comment]
@bsmiles32 @loganmc10 @Gillou68310 

I agree that it should be done in the RSp.

Now the issue is that Yakouchuu II - Satsujun Kouru does not work with any HLE plugin. It seems that the ucode is sent to the gfx plugin.

So either the RSP plugin (PJ64 one, cxd4 or mupen one) get fixed and game becomes playable with GlideN64 or the ucode e have to implement in GlideN64.

Can you please fix the RSP plugin (may be not Mupen as it does work in HLE) to avoid having to implement the ucode in GlideN64?

Fact is that it is the last game where HLE does not work as LLE and I really really want to close the HLE topic. Gilles seems to have stop working on this ucode and the matter is not fixed in any RSP as from the beginning of the N64 emulation.

I will finish the deciphering, it is not too hard fortunately. Depending on the RSP fix, it will get implemented in GlideN64 or I will share my deciphering to you guys for implementation in Mupen RSP.

Thanks!

**Comment by olivieryuyu** [comment]
@bsmiles32 @loganmc10 @Gillou68310

Is any of you can change the RSP plugin PJ64 one or cxd4 to get the movies dealt by the RSP and not by the gfx plugin?

We are trying to implement HVQM in the gfx plugin but at the end wonder if it makes sense.

**Comment by Gillou68310** [comment]
@olivieryuyu CXD4 plugin is already processing HQVM via the RSP.

**Comment by olivieryuyu** [comment]
@Gillou68310 

It works for Pokemon Snap indeed but not for Yakouchuu II - Satsujun Kouru.

This game sends the "displayslist" to the graphic plugin. The gfx plugin can dealt with it if we do implement the data processing in it but as written it does not make so much sense.

I checked whether they are differences between Pokemon Snap and Yakouchuu II - Satsujun Kouru and ucode is the same. Actually Pokemon Snap uses more the RSP than Yakouchuu II - Satsujun Kouru.

**Comment by Gillou68310** [comment]
Ok I understand now, do you know the value of the task type when the ucode is called?

**Comment by Gillou68310** [comment]
Nevermind just saw this:
> This game sends the "displayslist" to the graphic plugin for Yakouchuu II - Satsujun Kouru

Means task type is 1 (GFXTASK)

**Comment by olivieryuyu** [comment]
yes RPS send the displaylist to the gfx plugin when in HLE mode.

I believe it should not be the case (but I am not that sure). I have also zero idea of the difference between both games. 

HVQM as RE2 movies should be dealt by RSP only.

So there is a mystery or a bug somewhere... 

We can implement in GlideN64 the ucode/data processing but is it necessary for a gfx plugin when it looks a RSP task bug?

**Comment by Gillou68310** [comment]
Yeah task type was not always used correctly by devs. We can use the ucode CRC to force the ucode to be dealt by the RSP but it's definitely a hack.

**Comment by olivieryuyu** [comment]
@Gillou68310 

so how should we proceed in this case?

1) RSP hack in CDX4 and/or PJ64 (potentially Mupenplus RSP later on)?
2)  implementation in GlideN64 (make no sense but can be done)

If 1), can you please fix the RSP for this?

**Comment by Gillou68310** [comment]
Definitely 1. I'll try to find some time to add the hack to cxd4.

**Comment by olivieryuyu** [comment]
Thanks!

Hopefully that should not take too much time.

If GlideN64 works with CXD4, then I can share with you my workings on the ucode so you can finish your implemenation in Mupenplus if you wish.

**Comment by Gillou68310** [comment]
@olivieryuyu I don't understand videos are working with mupen+cxd4. We agree that the boat is a video right?

**Comment by Gillou68310** [comment]
Sorry I forgot to set DisplayListToGraphicsPlugin to True ;-)

**Comment by Gillou68310** [comment]
https://github.com/Gillou68310/mupen64plus-rsp-cxd4/tree/yakouchuu

**Comment by olivieryuyu** [comment]
Yes Mupen is fine :)

**Comment by Gillou68310** [comment]
[mupen64plus-rsp-cxd4.zip](https://github.com/mupen64plus/mupen64plus-core/files/2773756/mupen64plus-rsp-cxd4.zip)

**Comment by olivieryuyu** [comment]
works like charm thanks

**Comment by olivieryuyu** [comment]
Pokemon Snap however does not work anymore.

**Comment by olivieryuyu** [comment]
I mean Pokemon Puzzle :)

**Comment by Gillou68310** [comment]
Weird Puzzle works for me! It doesn't use the hack btw since the task type is correct (7) for this game.

**Comment by olivieryuyu** [comment]
I have this error:

![image](https://user-images.githubusercontent.com/8987490/51424235-63e87300-1bcb-11e9-9d98-1c60d1f5da1b.png)

**Comment by Gillou68310** [comment]
That's unrelated to my hack. Maybe a config file issue, I can't really help I'm not using a gui. Launching everything from cmd line;-)

**Comment by olivieryuyu** [comment]
Solve it: I changed the name of the hacked RSP to mupen64plus-rsp-cxd4-sse2

**Comment by olivieryuyu** [comment]
Ok so I believe that the hack works perfectly. Can it be implemented by default in CXD4 plugin? :)

**Comment by Gillou68310** [comment]
This question should be asked upstream. Right now I'm computing the sum before sending dlist to video plugin for every game. This is a waste of time for every game except Yakouchuu. Maybe there a faster way to detect HQVM ucode!

**Comment by olivieryuyu** [comment]
Can't you use simply the ucode crc as for GlideN64? :)

**Comment by Gillou68310** [comment]
Yeah that's already what I do, computing the sum instead of crc .What I mean is that it's useless for every other game.

**Comment by olivieryuyu** [comment]
ROM have a header with a name in it. You only activate your code for this game when detecting the game in question. That is pretty much the only option. 

Or ucode has to be implemented in GlideN64 (back to square 1)

**Comment by Gillou68310** [comment]
ROM header is a possibility. We were using it in rsp-hle do detect Indiana Jones and Battle for Naboo in order to fallback to LLE back when hle gfx ucode was unimplemented ;-)

**Comment by Gillou68310** [comment]
However header is not passed to the rsp-plugin via the API. M64P has a core command (M64CMD_ROM_GET_HEADER) to retrieve the information. I don't know if PJ64 has a similar command.
@cxd4 @project64

**Comment by loganmc10** [comment]
@Gillou68310 are you planning on finishing your work on this ucode in rsp-hle? And then the plan is to add a hack to redirect the Yakouchuu task to that same implementation?

**Comment by olivieryuyu** [comment]
I sent my notes to Gilles. Potentially it can help him.

**Comment by Gillou68310** [comment]
@loganmc10 Right now I'm spending all my free time on the new_dynarec. So yes I'd like to finish my work on the ucode but it's not my top priority right now.

I wonder if @bsmiles32 is interested in this task?

> And then the plan is to add a hack to redirect the Yakouchuu task to that same implementation?

Correct!

**Comment by StenApp** [comment]
I think it's not implemented yet is it?

**Comment by Narann** [comment]
Can we close this one?
@loganmc10 ?

**Comment by loganmc10** [comment]
Yes :)
