### ISSUE TITLE
perfect dark flickers quite a bit.

### ISSUE THREAD

**Issue by FrostKnight** [mupen64plus/mupen64plus-core#551]
For some reason, it is buggy and the screen looks kind of funky, I cannot get past the menu without not being able to see properly what it is doing. I tried two different controllers and well, It looks blurry also.

Is there, something I can do to fix this?

My version is 2.5-7 my operating system is a linux distrobution 

Here is more info:

UI-Console Status: Cheat codes disabled.
UI-Console: using Video plugin: 'Mupen64Plus OpenGL Video Plugin by Rice' v2.5.0
UI-Console: using Audio plugin: 'Mupen64Plus SDL Audio Plugin' v2.5.0
UI-Console: using Input plugin: 'Mupen64Plus SDL Input Plugin' v2.5.0
UI-Console: using RSP plugin: 'Hacktarux/Azimer High-Level Emulation RSP Plugin' v2.5.0
Input: 0 SDL joysticks were found.
Input: N64 Controller #1: Forcing default keyboard configuration
Input: 1 controller(s) found, 1 plugged in and usable in the emulator
Input: Mupen64Plus SDL Input Plugin version 2.5.0 initialized.
Video: SSE processing enabled.
Video: ROM (CRC 0780b0e433ff02a6-50) not found in INI file
Video: Initializing OpenGL Device Context.
Core: Setting 32-bit video mode: 640x480
Video Warning: Failed to set GL_BUFFER_SIZE to 32. (it's 24)
Video: Using OpenGL: Intel Open Source Technology Center - Mesa DRI Mobile Intel�� GM45 Express Chipset  : 2.1 Mesa 17.0.5
Audio: Initializing SDL audio subsystem...
Core: Starting R4300 emulator: Dynamic Recompiler
Core: R4300: starting 64-bit dynamic recompiler at: 0x7f20ca8849d0

**Comment by bsmiles32** [comment]
Since you're using the Rice Video plugin, I would try changing the ScreenUpdateSetting = 2 in mupen64plus configuration file under [Video-Rice] section.
Otherwise you can try better supported plugin such as GLideN64: https://github.com/gonetz/GLideN64

**Comment by FrostKnight** [comment]
Sorry for not paying attention to this, but yeah glide64 works.  I have no idea why I didn't close this sooner. Thanks!

Only one thing remains, unrelated though as it has to do with some cheats breaking saves.  So I close this!

**Comment by mw-cyrano** [comment]
I had quite some flickering during actual gaming left and switched to

```
ScreenUpdateSetting = 4
```

which feels like native gameplay.

Platform Intel Corporation TigerLake-LP GT2 [Iris Xe Graphics] (rev 01) with Kernel 6.5.0-17-generic

**Comment by MPW1412** [comment]
I had quite some flickering during actual gaming left and switched to

```
ScreenUpdateSetting = 4
```

which feels like native gameplay.

Platform Intel Corporation TigerLake-LP GT2 [Iris Xe Graphics] (rev 01) with Kernel 6.5.0-17-generic
