### ISSUE TITLE
Tonic trouble (u) new dynarec crash

### ISSUE THREAD

**Issue by fzurita** [mupen64plus/mupen64plus-core#552]
@Gillou68310 

Tonic trouble is crashing with the arm new dynarec. It doesn't crash with interpreter. Here is a save state, all you have to do to reproduce the crash is step on the square:
[crash1.Tonic Trouble (U) (V1.1) [!].zip](https://github.com/mupen64plus/mupen64plus-core/files/1853281/crash1.Tonic.Trouble.U.V1.1.zip)

**Comment by fzurita** [comment]
Also, this text shows up: ```oops, branch at end of block with no delay slot```

**Comment by Gillou68310** [comment]
Thanks I will take a look when I find some time

**Comment by Gillou68310** [comment]
I still have to finish the hvqm ucode first

**Comment by Gillou68310** [comment]
Fixed by https://github.com/mupen64plus/mupen64plus-core/commit/5d92dcbbb2b34b0ad94c6fb5fefbcdfc43ecbddf

**Comment by fzurita** [comment]
Nice! Seems like you fixed a lot of stuff.

**Comment by Gillou68310** [comment]
BTW this was not happening with DisableSpecRecomp = False

**Comment by fzurita** [comment]
Is that something we should have off by default? Is speculative recompilation a significant performance boost?

**Comment by fzurita** [comment]
It's not too late, it can still be done and the save state version can be bumped.

**Comment by Gillou68310** [comment]
Could you do it? :-)

**Comment by fzurita** [comment]
Lol, yeah, sure. I have some time tonight or tomorrow.

**Comment by Gillou68310** [comment]
Thanks I'm focused on the new dynarec right now, I'd like to get rid of those old issues ;-)

**Comment by fzurita** [comment]
No problem!
