### ISSUE TITLE
VI_CURRENT_REG not calculated properly if CP0_COUNT_REG changed by software

### ISSUE THREAD

**Issue by pdrome** [mupen64plus/mupen64plus-core#554]
I'm building an N64 test ROM where I occasionally reset CP0_COUNT_REG to zero. This register is writable and such a scenario is possible on real hardware. After doing this, mupen will then take a very long period of time before it reaches the next VI.

I believe this is because the VI_CURRENT_REG isn't properly calculated when I change the CP0_COUNT_REG value.

https://github.com/mupen64plus/mupen64plus-core/blob/5fb51e8d268a1a666244506d97574665d56901c2/src/device/rcp/vi/vi_controller.c#L90

I'm not sure if this behavior affects any games, but if anything out there is modifying CP0_COUNT_REG it could cause timing issues.  Here is a test ROM that resets CP0_COUNT_REG to zero and demonstrates the issue:

https://github.com/pdrome/n64-asm-timing/blob/master/TIMING_R0/CPUTIMING_COUNT.N64

Here is the same test ROM but without the lines which reset CP0_COUNT_REG:

https://github.com/pdrome/n64-asm-timing/blob/master/TIMING_R0/CPUTIMING_COUNT_NO_MTC0.N64

**Comment by Gillou68310** [comment]
Thanks for testing! Could you test the following branch to see if it makes any difference?
https://github.com/Gillou68310/mupen64plus-core/tree/int
It's a wip refactoring to get rid of the special interrupt used to deal with the count register overflow.

**Comment by pdrome** [comment]
I'm out and about today, but I can test this evening

If you want to test in the meantime, the main way to see the problem will be that the first ROM (CPUTIMING_COUNT.N64) will run slowly and the second ROM (CPUTIMING_COUNT_NO_MTC0.N64) will run significantly faster. This is for CountPerOp>=2.

Additionally,, if you set CountPerOp==1 then the first ROM will show blank screen before everything pops in at once while the second ROM will incrementally fill the screen (like with CountPerOp>=2).

**Comment by pdrome** [comment]
@Gillou68310 

I tried the WIP code and it does not appear to affect the issue.

**Comment by pdrome** [comment]
Check that last comment.  I realized today that I didn't have the latest commit from the WIP version.  git clone gave me an old version so I had to download the zip instead.

It still didn't fix the problem, but it did change it.  Instead of running slowly for CountPerOp >=2 and the screen popping in for CountPerOp ==1, it seems as though the ROM freezes and never displays anything to the screen regardless of CountPerOp setting.

It doesn't crash, just displays a blank screen.

**Comment by pdrome** [comment]
I was able to get the WIP version to output to the screen.  The behavior is the same, but it runs more more slowly.

**Comment by pdrome** [comment]
I made another ROM to try to understand what may be going on.  It is located here:

https://github.com/pdrome/n64-asm-timing/blob/master/VI_CURRENT_REG_TEST_R0/VI_CURRENT_REG_TEST.N64

This ROM outputs the state of CP0_COUNT_REG and VI_V_CURRENT_LINE at several points before and after modifying CP0_COUNT_REG with MTC0.  Here are the 7 outputs:

1. INITIAL VALS: Whatever state the values happen to be before modifying CP0_COUNT_REG.
2. MTC0 RUN: State immediately after setting CP0_COUNT_REG==0 with MTC0
3. +~2000 OPS: State about 2000 ops after setting CP0_COUNT_REG==0 (hoping to get to next scanline regardless of countperop setting)
4. +~4000 OPS: State about 4000 ops after setting CP0_COUNT_REG==0 (hoping to get yet another scanline regardless of countperop setting)
5. +~850,000 OPS: State about 850,000 ops after setting CP0_COUNT_REG==0 (hoping to get a new field entirely)
6. +~1,700,000 OPS: State about 1,7000,000 ops after setting CP0_COUNT_REG==0 (hoping to get yet another new field)
7. OLD CP0_CNT: State when reset CP0_COUNT_REG to the value it was before setting it equal to zero with MTC0.

Here is the output using COUNTPEROP==3, but the trends are the same regardless of all the settings I've tried:

![cp0_cnt_reg_test](https://user-images.githubusercontent.com/10876467/38230582-9d132c8a-36dc-11e8-88e8-1e4c2545ec10.png)

It seems as though VI_V_CURRENT_LINE is not being evaluated correctly when CP0_COUNT_REGISTER is reset by MTC0.  CP0_COUNT_REGISTER has to return to the original value for mupen to start outputting new values of VI_V_CURRENT_LINE. This could potentially have the effect described in the original ROM and is what I suspect is happening.

I didn't fully follow Gillou68310's WIP build, but it has logic to throw an interrupt when MTC0 is called to change CP0_COUNT_REGISTER. However, I don't think that interrupt was being triggered by either of these ROMs.  Is that interrupt meant to address this very issue?

**Comment by bsmiles32** [comment]
@pdrome Thank you very much for tackling this ! I can run your test roms on hardware, and I did try them, but my setup is PAL, so none of your test roms pass on my system :( I cannot read properly the small timing numbers from my TV screen because fonts are too small to read (+ analog blurring). I'll try to find back my capture card so I can upload some captures for you to see.

**Comment by pdrome** [comment]
@bsmiles32 ,

Sorry about the small fonts.  I only recently realized myself that they are tough to read when running on an N64 through a TV.  I'll see if I can alleviate that on my side by changing the frame buffer. I can also put together a PAL version for you to see if that helps.

As for the timing values, they don't pass on an NTSC N64 either at this point.  :-)

That's my fault though. The test numbers are based on work PeterLemon's did and I've modified the ROM such that the timing has changed. I plan on fixing that in the near future (hopefully) once I have some time to complete the ROM and get started on the timing study.

**Comment by bsmiles32** [comment]
Increasing the font size (maybe using vi_{x,y}_scale_reg) would help a lot, because for now I can't really read anything on real tv.
If you can hack a PAL version, I would also appreciate.

**Comment by pdrome** [comment]
@bsmiles32 

I made the font larger and compiled PAL versions of all the ROMs discussed in this issue. I don't have a PAL N64, so I can't verify that they work, but mupen seemed to display them correctly in a readable manner.

https://github.com/pdrome/n64-asm-timing/blob/master/TIMING_R0_PAL/CPUTIMING_COUNT.N64

https://github.com/pdrome/n64-asm-timing/blob/master/TIMING_R0_PAL/CPUTIMING_COUNT_NO_MTC0.N64

https://github.com/pdrome/n64-asm-timing/blob/master/VI_CURRENT_REG_TEST_R0_PAL/VI_CURRENT_REG_TEST.N64

The first 2 ROMs were truncated a bit because I needed to save some screen space, but the issue is still clear. Let me know if you have any issues.

**Comment by bsmiles32** [comment]
Here are some results running on my PAL console and captured with Terratec Grabby AV->USB converter.

PAL CPU TIMING COUNT
![pal_cpu_timing_count](https://user-images.githubusercontent.com/6403903/39067297-71f1aa5e-44d8-11e8-9954-301e8d6499b0.png)

PAL CPU TIMING COUNT NO MTC0
![pal_cpu_timing_count_no_mtc0](https://user-images.githubusercontent.com/6403903/39067298-7210b9f8-44d8-11e8-8e48-26478a564731.png)

PAL VI CURRENT REG (first run)
![pal_vi_current_reg](https://user-images.githubusercontent.com/6403903/39067300-72283524-44d8-11e8-9c21-28db4a2261f9.png)


Note that timing results can change a little bit between different runs for instance:
PAL VI CURRENT REG (second run)
![pal_vi_current_reg_2](https://user-images.githubusercontent.com/6403903/39067301-7243e81e-44d8-11e8-8ef2-e5c9b61176a3.png)

**Comment by pdrome** [comment]
Wow, that's some pretty significant variability.  I need to look into that.  Thanks!

**Comment by loganmc10** [comment]
hi @pdrome , I believe this issue would be sorted out in this change: https://github.com/mupen64plus/mupen64plus-core/pull/701

branch: https://github.com/loganmc10/mupen64plus-core/tree/special

your assumption was correct that next_vi isn't properly re-calculated when CP0_COUNT_REG is modified. I don't know of a commercial game that writes to CP0_COUNT_REG during gameplay, which is probably why this has never been noticed before.

As part of that PR, I added an item to properly reset next_vi when COUNT_REG is modified:

https://github.com/loganmc10/mupen64plus-core/blob/special/src/device/r4300/interrupt.c#L264

**Comment by Narann** [comment]
Merging auto closed the issue, can anyone confirm it's fixed?
