### ISSUE TITLE
Audio is not working in Windows

### ISSUE THREAD

**Issue by Papermanzero** [mupen64plus/mupen64plus-core#555]
Since the release from the 2017-11-06, Audio is mute on windows.
https://bitbucket.org/ecsv/mupen64plus-mxe-daily/commits/38410b647b1d
The only version which is working is the 2017-11-02 release.
I am using the default settings. I also completely setup mupen64plus from scratch, with the same result.

**Comment by loganmc10** [comment]
What audio plugin are you using? mupen64plus-audio-sdl is incompatible with SDL 2.0.5+ on Windows, it's a big with mupen64plus-audio-sdl, not the core

**Comment by Papermanzero** [comment]
I am using the plugins which are in the linked package.
I am not sure which one is affected. I first exchanged the plugin to the old version (which did not work) then I also exchanged the core with the old version and in this case audio was working.

**Comment by Papermanzero** [comment]
Checked again. It is core related.
I only exchanged the audio plugin with the newest release. The emulator/core itself stayed on an older version (version from November). The audio is working without any issues.

**Comment by richard42** [comment]
Sorry, but I'm not going to support the MXE build. I tested this tonight, and by building the latest source from git using visual studio, audio works fine. This is building against SDL1. I also tested Sven's pre-built MXE package, and unfortunately the 2017-11-06 tag didn't even run (windosw 7, 64-bit); it segfaulted at startup.  The 11-02 build did the same.
