### ISSUE TITLE
Donkey Kong 64 back to level beginning on vines

### ISSUE THREAD

**Issue by YalithKBK** [mupen64plus/mupen64plus-core#558]
I haven't been able to find anyone even describing this issue let alone someone mentioning a solution.  
Whenever I swing on vines/ropes in the game, there is a random chance it triggers the game to take me back to the beginning of the level. I get the "DK" spinup and then I am back at the beginning like I just entered from the lobby. My progress in the level is not affected.  
This has happened with both Donkey and Diddy on Jungle Japes and Angry Aztec. It is not always the same vine that triggers it.  
I am using version 2.0 on Linux Mint 17.3. (EDIT: I thought I was running 2.5, but I guess I had an older version hanging around. Going to try this with 2.5 and see if that fixes anything.)  
UPDATE: Switching to 2.5 seemed to have fixed the problem, but it just happened again.

**Comment by rlabrecque** [comment]
This has been fixed for a while, grab a more modern version like https://m64p.github.io/

We really need to get on this: https://github.com/mupen64plus/mupen64plus-core/issues/353

**Comment by YalithKBK** [comment]
I'm a bit confused. The link above takes me to a page where I downloaded the "Linux64" zip file. Upon extracting, I didn't see any of the core files. Do I need something else with these? Sorry, I'm still trying to figure out how to use this program.
