### ISSUE TITLE
Is "frame advance" working?

### ISSUE THREAD

**Issue by fzurita** [mupen64plus/mupen64plus-core#568]
I'm getting reports that the feature doesn't work. Is it known to be working? I'm trying to figure out if it's an Android problem or a core problem.

**Comment by richard42** [comment]
Last I tested it, this feature was working. I think sometimes you may only get a new frame for every 2 advances, because the game is really only running at 30fps and it's showing each field twice.

**Comment by loganmc10** [comment]
Yeah I just tested it on my PC with the latest master and it seems to be working fine

**Comment by fzurita** [comment]
Ok, sounds like an Android only issue. Thanks for testing.
