### ISSUE TITLE
Battle of Naboo: wrong gfx in level selection (core bug)

### ISSUE THREAD

**Issue by olivieryuyu** [mupen64plus/mupen64plus-core#570]
use password LEC&FIVE to access all levels

When selecting the level, the gfx are messing up.

Occurs in HLE, LLE, any plugin.

Work Ok with PJ64

![bugggg](https://user-images.githubusercontent.com/8987490/40749199-7a4896cc-6463-11e8-87a4-b90945b312b3.jpg)

**Comment by loganmc10** [comment]
Just tested with the lastest GLideN64, looks ok to me:

![battle_for_naboo-000](https://user-images.githubusercontent.com/848146/40749951-f310ea0a-6422-11e8-8154-31a2da9abcf4.png)

Are you using 32-bit or 64-bit?

**Comment by loganmc10** [comment]
Oh nevermind, different pictures were messed up for me, but they are messed up

**Comment by loganmc10** [comment]
Setting CountPerOp=1 seems to fix the problem for me

**Comment by fzurita** [comment]
Does cen64 have more accurate count register emulation?

**Comment by loganmc10** [comment]
Yes it should, it is supposed to be cycle accurate, so it should emulate each cycle and properly increment the count register each cycle

**Comment by olivieryuyu** [comment]
CountPerOp=1 seems to fix the issue
