### ISSUE TITLE
banjo tooie tip-toe using keyboard (move banjo analog 5% to 10% range)

### ISSUE THREAD

**Issue by fastrizwaan** [mupen64plus/mupen64plus-core#576]
There are many levels in Banjo-Tooie where we have to tip-toe to get Jiggies. How do we set the range to 10% or -90% in mupen64plus? We can get upto -75% using both "Right ctrl + right Shift" keys.

![screenshot from 2018-06-20 14-29-55](https://user-images.githubusercontent.com/1161682/41648409-6e211cf0-7496-11e8-879f-ee521f2c9995.png)

Please see this video:
https://youtu.be/-5ZtgNFC8KQ

project64 allows 10% range
![project64_tip_toe](https://user-images.githubusercontent.com/1161682/41648373-51760192-7496-11e8-8b32-d8df1ee9a312.png)
taken from:
https://www.youtube.com/watch?v=woX1iwTwfqA

**Comment by fastrizwaan** [comment]
Yay! got it working! by adding backspace key to mupen64plus-input-sdl to plugin.c with 

     if (keystate[SDL_SCANCODE_BACKSLASH])
	axis_max_val -= 66;

Please see that I'm able to get the jiggy from the snake:
https://www.youtube.com/watch?v=C3cERIA8S0E&feature=youtu.be

Kindly add axis_max_val =-66 to mupen64 sdl. so that games which requires such slow movement can be playable with mupen64plus. thanks.

**Comment by Jj0YzL5nvJ** [comment]
> When using the keyboard, the analog stick is normally moved by its full range when you press an arrow key. Sometimes you may need to make smaller moves. In this case, you can move the analog stick more gently by holding down the Right Control key (for -50%) or Right Shift key (-25%), or both (-75%).

http://www.mupen64plus.org/wiki/index.php?title=KeyboardSetup

**Comment by fastrizwaan** [comment]
only after seeing the rshift and rctrl settings as both can't do tip-toe (10% movement), i created one more which can do proper tiptoe.

**Comment by Jj0YzL5nvJ** [comment]
Sorry, I read your comments on different days and I forgot part of the content of the first one, the PJ64 input part drowned out my attention =P

 I think a control similar to that of web browsers for zoom would be much better.

**Comment by richard42** [comment]
https://github.com/mupen64plus/mupen64plus-input-sdl/pull/97 has been merged to fix this issue.
