### ISSUE TITLE
New dynarec CBFD is freezing

### ISSUE THREAD

**Issue by fzurita** [mupen64plus/mupen64plus-core#587]
CBFD is freezing with the new dynarec. This may be a recent regression because I don't remember this happening before. Here is a save state right before the freeze happens. It doesn't freeze with interpreter.

[Conker's Bad Fur Day (U) [!].crash.zip](https://github.com/mupen64plus/mupen64plus-core/files/2343400/Conker.s.Bad.Fur.Day.U.crash.zip)

**Comment by Gillou68310** [comment]
@fzurita Better late than never, this doesn't seems to happen anymore. Could you double check?

**Comment by fzurita** [comment]
Yep

**Comment by fzurita** [comment]
Nice, no freeze with the 64 bit new dynarec. Was it TLB issues?

**Comment by Gillou68310** [comment]
No idea ;-) I fixed a bunch a things so...
