### ISSUE TITLE
Troubles extracting rom MD5 from save state

### ISSUE THREAD

**Issue by sklink** [mupen64plus/mupen64plus-core#591]
I've been able to find where it's being read from: https://github.com/mupen64plus/mupen64plus-core/blob/master/src/main/savestates.c#L243

However, when I run it through zlib gunzip in Node.js it throws a `incorrect header check`. I've tried a few things but my understanding of zlib is limited.

Are there custom headers m64p uses that would cause the library to fail to recognize it?

Any suggestions on pulling that information out?

**Comment by Jj0YzL5nvJ** [comment]
The savestates are compressed, uncompress it with 7-Zip (p7zip) and open the resulting file with a text editor or hexadecimal viewer.
The MD5 is very close to the header...

**Comment by sklink** [comment]
That did it, thanks!
