### ISSUE TITLE
Debugger is broken

### ISSUE THREAD

**Issue by clbr** [mupen64plus/mupen64plus-core#595]
Building everything with today's git, SDL plugins for input and audio, z64 for rsp and video, if the core is built with DEBUGGER=1, mupen64plus pops up an empty window and hangs. gdb reports all threads waiting for a semaphore or a cond var.

When I build the core without the debugger, mupen64plus works fine.

**Comment by richard42** [comment]
OK, I just pushed fixes for this in the core and the ui-console. It should only start up in the 'paused' mode if you give the "--debug" option on the command line.
