### ISSUE TITLE
Combined joystick actions not working on Windows 10

### ISSUE THREAD

**Issue by helviojr** [mupen64plus/mupen64plus-core#601]
Using the 2.5 version on Windows 10 and it is all working as expected, but the core events does not accept combined actions hotkeys (separated by "/" character). For example, for a Xbox one controller, the following mupen64plus.cfg: 
```
[CoreEvents]
Joy Mapping Stop = "J0B7/B6"
Joy Mapping Pause = "J0B6/B2"
Joy Mapping Increase Volume = "J0B6/A3-"
Joy Mapping Decrease Volume = "J0B6/A3+"
```

Not only will not work as expected (only when both buttons are pressed), but will act as only the first action was valid, as it would in:
```
Joy Mapping Stop = "J0B7"
Joy Mapping Pause = "J0B6"
Joy Mapping Increase Volume = "J0B6/A3-"
Joy Mapping Decrease Volume = "J0B6/A3+"
```

Yes, pressing button #6 will pause and also show volume (will not increase nor decrease because it will try to do both simultaneously.

Maybe a totally different issue, but I couldn't also map two different actions to the same N64 action:
```
[Input-SDL-Control1]
Z Trig = "axis(2+) axis(2-)"
```

Only the first action is honored, as it was:
```
Z Trig = "axis(2+)"
```

**Comment by helviojr** [comment]
Just compiled the source and tested. 32-bit version crashes always, but I didn't check motive. So I built a 64-bit and the emulator is OK. Unfortunately, the same symptom still occurs (can't set a two-button action), neither use * wildcard for joystick number.

**Comment by richard42** [comment]
correct, a 2.6 release will be coming soon, and that will support these new joystick configuration features
