### ISSUE TITLE
New dynarec not working on x64

### ISSUE THREAD

**Issue by loganmc10** [mupen64plus/mupen64plus-core#603]
The following is from Mario 64 but other games are affected as well:
```
Core Error: Unknown MTC0 write: 64
Core Error: Unknown MTC0 write: 68
Core Error: Unknown MTC0 write: 72
```

Tested on Windows, compiled with MSYS2. 32-bit version is working normally
@Gillou68310

**Comment by Gillou68310** [comment]
Probably MSVC macro not defined see assem_x64.h
