### ISSUE TITLE
Minizip header build failure

### ISSUE THREAD

**Issue by bentley** [mupen64plus/mupen64plus-core#608]
On OpenBSD, core fails to build if libzip has been installed from packages.

This is because libzip installs its own zip.h header in /usr/local/include which gets picked up in preference to the minizip zip.h located in the mupen64plus source.

OpenBSD’s compilers (clang or gcc) don’t look in /usr/local/include by default, but the pkg-config output of libpng adds it in. Since /usr/local/include from libpng shows up in CFLAGS before the include path of the embedded minizip, /usr/local/include/zip.h is what gets picked up.

My workaround is to move the minizip bits in the Makefile above the PNG bits, so minizip’s -I flags show up first. This also necessitates moving the SOURCE= assignment upward (otherwise it overwrites the SOURCE += assignment in minizip and the resulting module doesn't link minizip in).

Ideally references to the minizip header would change from “zip.h” to “minizip/zip.h” to prevent this ambiguity. But upstream doesn’t seem to think so; their pkg-config file lists -I${prefix}/include/minizip, suggesting that the canonical include is <zip.h> and not <minizip/zip.h>. Sigh…

**Comment by richard42** [comment]
I just pushed a potential fix for this problem; can you please get the latest from git and re-test?
