### ISSUE TITLE
Kirby 64 texture stretching

### ISSUE THREAD

**Issue by HarryTheTurtle** [mupen64plus/mupen64plus-core#622]
There is texture stretching in Kirby 64 on almost every level on 1.7.6 Mupen64Plus OpenGL 2.5 b via RetroArch core. I have supplied some save states near some stretched textures. Some textures will continuously stretch and become clear depending on where the player is standing. Switching from HLE to LLE will fix this but results in weird outlines. Is there a way to fix this on HLE?

[Kirby 64 - The Crystal Shards (USA).zip](https://github.com/mupen64plus/mupen64plus-core/files/2848057/Kirby.64.-.The.Crystal.Shards.USA.zip)

The level this save state is on is a good example of texture stretching. Continuing to the right will display more stretched textures.

**Comment by m4xw** [comment]
Uhm. Why would you create a Issue here?
The Mupen64Plus Core in RA is end-of-life and no longer supported and uses a several years out of date mupen64plus core.
Please at the very least confirm it with the Mupen Next core, https://github.com/libretro/mupen64plus-libretro-nx <- that one uses up2date mupen64plus-core.

**Comment by HarryTheTurtle** [comment]
Sorry just got back into emulation after a couple years and am not aware of the new branches of old emulators. I can confirm the texture stretching with Mupen Next core and but now the issue persists when using LLE with same settings.

**Comment by m4xw** [comment]
LLE is not implemented in mupen next.
It will just use HLE, also show us your core options.

**Comment by m4xw** [comment]
Also you should provide us with a few images.
Also you should confirm it with standalone mupen and updated gliden.

**Comment by HarryTheTurtle** [comment]
Are you talking about the Mupen64Plus v2.5 for standalone or is there another build?

**Comment by HarryTheTurtle** [comment]
Here are the stretched textures.

![kirby 64 - the crystal shards usa -190209-141851](https://user-images.githubusercontent.com/47069190/52525933-e61e0180-2c76-11e9-924b-aac59d38146c.png)

Here are the corrected textures. (Corrects itself in certain locations)

![kirby 64 - the crystal shards usa -190209-141858](https://user-images.githubusercontent.com/47069190/52525942-0483fd00-2c77-11e9-8841-b1d00af66020.png)

Here are more stretched textures that never correct in any position.

![kirby 64 - the crystal shards usa -190209-141933](https://user-images.githubusercontent.com/47069190/52525948-19f92700-2c77-11e9-8ed0-7c273e5e65d3.png)

Settings in RA using Mupen64Plus Next (Current Build)

![settings](https://user-images.githubusercontent.com/47069190/52525954-2d0bf700-2c77-11e9-9550-a6f43ce09749.jpg)

**Comment by m4xw** [comment]
Go video settings, what is aspect ratio set to?

**Comment by HarryTheTurtle** [comment]
Core Provided
