### ISSUE TITLE
2.5.9: Print of size_t has to use z modifier

### ISSUE THREAD

**Issue by charlemagnelasse** [mupen64plus/mupen64plus-core#628]
The print of size_t variables has to be done using %zd and not %d (similar for %u, %i and so on). The output on amd64 is otherwise wrong. Here some examples from 2.5.9 release:

    ../../src/device/dd/dd_controller.c: In function ‘read_C2’:
    ../../src/device/dd/dd_controller.c:191:51: warning: format ‘%x’ expects argument of type ‘unsigned int’, but argument 3 has type ‘size_t’ {aka ‘long unsigned int’} [-Wformat=]
         DebugMessage(M64MSG_INFO, "read C2: length=%08x, offset=%08x",
                                                    ~~~^
                                                    %08lx
                 length, offset);
                 ~~~~~~                                 
    
    
    ../../src/device/dd/dd_controller.c:191:64: warning: format ‘%x’ expects argument of type ‘unsigned int’, but argument 4 has type ‘size_t’ {aka ‘long unsigned int’} [-Wformat=]
         DebugMessage(M64MSG_INFO, "read C2: length=%08x, offset=%08x",
                                                                 ~~~^
                                                                 %08lx
                 length, offset);
                         ~~~~~~                                      
    
    
    ../../src/device/gb/gb_cart.c: In function ‘init_gb_cart’:
    ../../src/device/gb/gb_cart.c:1010:31: warning: too many arguments for format [-Wformat-extra-args]
         DebugMessage(M64MSG_INFO, "GB cart type (%02x) %s%s%s%s%s%s",
                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    
    
    ../../src/device/gb/gb_cart.c:1049:65: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘size_t’ {aka ‘long unsigned int’} [-Wformat=]
                     DebugMessage(M64MSG_ERROR, "Cannot get GB RAM (%d bytes)", ram_size);
                                                                    ~^          ~~~~~~~~
                                                                    %ld
    
    
    ../../src/device/gb/gb_cart.c:1053:49: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘size_t’ {aka ‘long unsigned int’} [-Wformat=]
                 DebugMessage(M64MSG_INFO, "Using a %d bytes GB RAM", ram_size);
                                                    ~^                ~~~~~~~~
                                                    %ld
    
    
    ../../src/device/rdram/rdram.c: In function ‘poweron_rdram’:
    ../../src/device/rdram/rdram.c:143:46: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 3 has type ‘size_t’ {aka ‘long unsigned int’} [-Wformat=]
         DebugMessage(M64MSG_INFO, "Initializing %u RDRAM modules for a total of %u MB",
                                                 ~^
                                                 %lu
             modules, rdram->dram_size / (1024*1024));
             ~~~~~~~                               
    
    
    ../../src/device/rdram/rdram.c:143:78: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 4 has type ‘size_t’ {aka ‘long unsigned int’} [-Wformat=]
         DebugMessage(M64MSG_INFO, "Initializing %u RDRAM modules for a total of %u MB",
                                                                                 ~^
                                                                                 %lu
             modules, rdram->dram_size / (1024*1024));
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                               
    
    
    ../../src/device/rdram/rdram.c: In function ‘write_rdram_regs’:
    ../../src/device/rdram/rdram.c:209:56: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 3 has type ‘size_t’ {aka ‘long unsigned int’} [-Wformat=]
                 DebugMessage(M64MSG_ERROR, "IPL3 detected %u MB of RDRAM != %u MB",
                                                           ~^
                                                           %lu
                     ipl3_rdram_size / (1024*1024), rdram->dram_size / (1024*1024));
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~           
    
    
    ../../src/device/rdram/rdram.c:209:74: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 4 has type ‘size_t’ {aka ‘long unsigned int’} [-Wformat=]
                 DebugMessage(M64MSG_ERROR, "IPL3 detected %u MB of RDRAM != %u MB",
                                                                             ~^
                                                                             %lu
                     ipl3_rdram_size / (1024*1024), rdram->dram_size / (1024*1024));
                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    
    
    ../../src/main/main.c: In function ‘load_dd_disk’:
    ../../src/main/main.c:1108:59: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 3 has type ‘size_t’ {aka ‘long unsigned int’} [-Wformat=]
             DebugMessage(M64MSG_ERROR, "Invalid DD Disk size %u.", dd_disk->size);
                                                              ~^    ~~~~~~~~~~~~~
                                                              %lu
    
    
    ../../src/main/main.c: In function ‘main_run’:
    ../../src/main/main.c:1515:61: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 3 has type ‘size_t’ {aka ‘long unsigned int’} [-Wformat=]
                     DebugMessage(M64MSG_INFO, "Game controller %u (%s) has a %s plugged in",
                                                                ~^
                                                                %lu
                         i, cont_flavor->name, l_ipaks[l_paks_idx[i]]->name);
                         ~                                        
    
    
    ../../src/main/main.c:1518:61: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 3 has type ‘size_t’ {aka ‘long unsigned int’} [-Wformat=]
                     DebugMessage(M64MSG_INFO, "Game controller %u (%s) has nothing plugged in",
                                                                ~^
                                                                %lu
                         i, cont_flavor->name);
                         ~

**Comment by charlemagnelasse** [comment]
To better see this problems, please add something like this:

    --- a/src/api/callbacks.h
    +++ b/src/api/callbacks.h
    @@ -29,10 +29,16 @@
     #include "m64p_frontend.h"
     #include "m64p_types.h"
     
    +#if defined(__GNUC__)
    +#define ATTR_FMT(fmtpos, attrpos) __attribute__ ((format (printf, fmtpos, attrpos)))
    +#else
    +#define ATTR_FMT(fmtpos, attrpos)
    +#endif
    +
     /* Functions for use by the Core, to send information back to the front-end app */
     extern m64p_error SetDebugCallback(ptr_DebugCallback pFunc, void *Context);
     extern m64p_error SetStateCallback(ptr_StateCallback pFunc, void *Context);
    -extern void       DebugMessage(int level, const char *message, ...);
    +extern void       DebugMessage(int level, const char *message, ...) ATTR_FMT(2, 3);
     extern void       StateChanged(m64p_core_param param_type, int new_value);
     
     #endif /* API_CALLBACKS_H */
    

to

* mupen64plus-core: DebugMessage, main_message, osd_new_message, osd_update_message, db_printf
* mupen64plus-ui-console: DebugMessage
* mupen64plus-video-glide64: output, FRDP, FRDP_E, WriteLog, display_warning, LOG
* mupen64plus-video-z64: rdp_log, LOG, gglPrintf
* every other repo with similar functions

And run the build with:

    cd projects/unix
    CFLAGS="-Wmissing-format-attribute -Wformat=2" make all

**Comment by richard42** [comment]
ok, this should be fixed now.
