### ISSUE TITLE
2.5.9: Missing INPUT_API_VERSION change (2.5 Input plugin not working with 2.5.9 core)

### ISSUE THREAD

**Issue by charlemagnelasse** [mupen64plus/mupen64plus-core#630]
I started to upgrade parts of mupen64plus and hadn't updated mupen64plus-input-sdl yet. It was noticed that the window was not reacting anymore to inputs (press of esc or other hotkeys) and also the normal keyboard input keys didn't work.

It worked again after the upgrade to mupen64plus-input-sdl 2.5.9. I would have expected that there is some input API change documented which is now required in mupen64plus-core/mupen64plus-input-sdl from 2.5.9. But nothing like this could be found. And mupen64plus-input-sdl 2.5.9 also seems to work with mupen64plus-core 2.5

Maybe it was forgotten to be documented and to add the required version bump for INPUT_API_VERSION. The input plugin still uses:

    src/version.h:#define INPUT_PLUGIN_API_VERSION 0x020000
    src/version.h:#define CONFIG_API_VERSION       0x020100

The problem was introduced with 87b1946868472d739a58eca69261634970e8537a which disabled SDL_PumpEvents in the core. Please make sure that this is reflected as major input API change to avoid mixing of incompatible plugins;

**Comment by richard42** [comment]
thanks for catching this problem. this should be fixed now.
