### ISSUE TITLE
arm dynarec crash with stop_after_jal=0

### ISSUE THREAD

**Issue by fzurita** [mupen64plus/mupen64plus-core#631]
@Gillou68310 We have a crash that didn't exist before, as of this commit 1749e1542e05d700b45e3d7efa64e6854d34ff95. Here is a backtrace:
```
********** Crash dump: **********
Build fingerprint: 'razer/cheryl/cheryl:8.1.0/OPM1.171019.011-RZR-180803/6033:user/release-keys'
#00 0x00000000000808e0 /lib/arm64/libmupen64plus-core.so (offset 0x30000)
        set_jump_target
        ./src/device/r4300/new_dynarec/arm64/assem_arm64.c:300:7
        pagespan_assemble
        ./src/device/r4300/new_dynarec/new_dynarec.c:7322:0
        new_recompile_block
        ./src/device/r4300/new_dynarec/new_dynarec.c:10698:0
#01 0x00000000000870f0 /lib/arm64/libmupen64plus-core.so (offset 0x30000)
        get_addr_32
        ./src/device/r4300/new_dynarec/new_dynarec.c:2149:9
#02 0x00000000000ae458 /lib/arm64/libmupen64plus-core.so (offset 0x30000)
        jump_eret
        ./src/device/r4300/new_dynarec/arm64/linkage_arm64.S:337:0
Crash dump is completed
```

This happens in Indiana Jones (U) when firing a gun. Here is a save state, just press B:
[crash.Indiana Jones and the Infernal Machine (U) [!].zip](https://github.com/mupen64plus/mupen64plus-core/files/2880223/crash.Indiana.Jones.and.the.Infernal.Machine.U.zip)

**Comment by m4xw** [comment]
@Gillou68310 
`/* Linker */
static void set_jump_target(intptr_t addr,uintptr_t target)
{
  u_int *ptr=(u_int *)addr;
  intptr_t offset=target-(intptr_t)addr;

  if(!ptr) // Indiana Jones is weird
    return;`

This fixes it for me. Not sure why addr is null tho, maybe stack corruption?
I remember scan build complaining about set_jump_target before, anyway this fixes the gun fire and at least in the first level after some testing no new issues arise.

**Comment by Gillou68310** [comment]
Weird I will investigate the issue. @fzurita sorry I missed this I was a bit busy lately ;-)

**Comment by Gillou68310** [comment]
hum looks like an issue in pagespan_assemble this is not happening with stop_after_jal = 1 btw

**Comment by Gillou68310** [comment]
This is not an arm64 specific issue btw! Also since this is not a regression caused by the arm64/x64 port, I will deal with it later.

**Comment by fzurita** [comment]
@Gillou68310 no problem. And thanks for checking.

**Comment by fzurita** [comment]
stop_after_jal may not be ready for prime time. I'm getting reports that save states are not reliable. I tried saving and loading a bunch of save states in paper Mario, and I was easily able to reproduce the issue. The game gets stuck in a black screen. Also, keep in mind that Mupen64plus-AE loads states at startup.

**Comment by m4xw** [comment]
@fzurita if it's loaded at startup, maybe stop_after_jal is overwritten in dynarec init?
I don't encounter any issues (or heard of simliar troubles) with my port (loads savestate after rom start)

**Comment by fzurita** [comment]
Yes, possibly. It seems that stop_after_jal is not being updated quickly enough.

**Comment by m4xw** [comment]
Since its only set in `new_dynarec_init` you could try to statically initialize it to zero and reset it in `new_dynarec_cleanup` to zero in case the dynarec is reinitialized.
Currently it's only defined as `unsigned int stop_after_jal;`

**Comment by fzurita** [comment]
Hmm, yeah, I will play around with it too see if I can get it to work more reliably.

**Comment by m4xw** [comment]
@fzurita were you able to resolve this or want me to take a look?

**Comment by fzurita** [comment]
You can if you are able to recreate it. I have not had a chance yet, but it's on my TODO list.

**Comment by m4xw** [comment]
Was there any specific reason for this:
```
// Default this to 1, it will be updated by the correct save state version later
stop_after_jal = 1;
```
I assume its to have it disabled on older savestates (since it was 1 on previous versions)? Tho shouldn't it just default to 0 and be changed automatically to 1 when the dynarec encounters troublesome cases (not counting the indi issue)

**Comment by m4xw** [comment]
@fzurita Can you try this commit https://github.com/libretro/mupen64plus-core/commit/09f17b08c20b727092b45091384e401485b16b0f

**Comment by fzurita** [comment]
I looked over the code, and it looks like it will behave the same unless an older save state is loaded.

**Comment by m4xw** [comment]
https://github.com/libretro/mupen64plus-core/commit/09f17b08c20b727092b45091384e401485b16b0f#r32947511

**Comment by m4xw** [comment]
@fzurita I pinged you about this issue on mupen fz on discord.
Give me a call when u have time to discuss.

**Comment by fzurita** [comment]
Ok, I see the ping, let me catch up to the conversation.

**Comment by Gillou68310** [comment]
@fzurita is this still an issue with https://github.com/mupen64plus/mupen64plus-core/pull/871?

**Comment by fzurita** [comment]
With #871, Indiana jones no longer crashes when firing the gun.
