### ISSUE TITLE
Display Issues when ResY > 1000

### ISSUE THREAD

**Issue by min1up** [mupen64plus/mupen64plus-core#633]
(Intel(R) Core(TM) i7-7550U CPU (x64), Intel(R) HD Graphics 620, Shared 12GB RAM)
(Win32 2.5.9 Bundle)

In resolutions where the vertical resolution exceeds 1000 (1280x1024, 1440x1050, 1680x1050, 1920x1080), a few interesting problems occur. Windowed mode shows much larger windows than usual while fullscreen mode has vertical cropping. All games have this problem, including Mupen64Plus Demo.

rice and glide64mk2 share the same issues. glide64mk2's `aspect` and `adjust_aspect` do not work. May be related to https://github.com/mupen64plus/mupen64plus-core/issues/625.

Examples of fullscreen vertical cropping:
![Incorrect Display](https://i.imgur.com/4synqNX.png)
_Majora's Mask GC, glide64mk2, fullscreen 1920x1080, incorrect_

![Correct Display](https://i.imgur.com/gkvq2t5.png)
_Majora's Mask GC, glide64mk2, fullscreen 1600x900, correct_

**Comment by WarlockPinkdoom** [comment]
this user min1up turned out to be a crazy pedophile lmfaoooo
