### ISSUE TITLE
screenshots can't be saved correctly when ROM had an invalid header.

### ISSUE THREAD

**Issue by nassau-tk** [mupen64plus/mupen64plus-core#634]
I'm useing Mupen64PlusFZ on Android OS 9.0.(I'm Japanese user.)
Header of several ROM turns into garbage word, and, it's recognized. A folder of the respective ROMs is made from an acquired header name, but it's the folder name which turned into garbage word as of it. When I take a picture of more screen shots, the file name in accordance with the header name arrives. It isn't possible to hold png filing of the screen shot which turned into garbage. Even if it's copied in Windows, this can't open. I thought the file name was a problem, so it'll be an error and you can't assume that I try to change the file name.
(ROM example:AI shogi 3,Famista64,and more...)
I take developer's notice of amateur's report like me even a little, and useful discussion and exchange of views are performed, and I think when it's something better.
At last,I'm not good at take English.The sentences written in clean Japanese were translated automatically. There may be a place with the not to be transmitted and to be strange meaning, but please pardon.

**Comment by fzurita** [comment]
I had a brief conversation with @nassau-tk to get a description of his problem. It seems like when saving screenshots, we are using the ROM header to determine the file name. It seems like a lot of games, have headers that don't work well as file names.

We should consider using something else as the file name when saving screenshots.

**Comment by rlabrecque** [comment]
Can you just use the rom's file name, is it available at the time?

**Comment by fzurita** [comment]
It's not since the ROM is loaded by the frontend. The core just gets a pointer to the memory.

**Comment by nassau-tk** [comment]
After all it's a question why it turns into garbage. A game name should be written in the title of Japanese by an alphabet basically. I can't think 2 byte character by which kanjis are hiragana and katakana, etc. is used. I can think the problem on the side of reading ROM. A game is also working by the garbage name folder. But it can't be said that it becomes stable under these conditions and is working. A screen shot is the trivial problem that a picture can't be taken now, but I think there is fact that information on specific ROM can't be read right. If possible, you'd like to be refreshed, right?

**Comment by Jj0YzL5nvJ** [comment]
The issue described here sounds like a [limitation](https://en.wikipedia.org/wiki/Long_filename#Limits) of FAT/FAT12/FAT16. What filesystem is @nassau-tk using?

**Comment by fzurita** [comment]
He is using an Android phone, so whatever file system Android uses.

**Comment by Jj0YzL5nvJ** [comment]
Some MicroSD cards come in FAT16 and the user never formats them before using them...

**Comment by nassau-tk** [comment]
microSD is 256GB.

**Comment by nassau-tk** [comment]
fmmm...
Why change the header(ROM name) to gabage character....?
Any one solve the issue!! pLz!z

**Comment by Mastergatto** [comment]
Could be a string coding issue? I found that using [cp932](https://en.wikipedia.org/wiki/Code_page_932_(Microsoft_Windows)) instead of utf-8 works better when you have to extract the header name from the ROM and you have to code it in a readable string.

**Comment by richard42** [comment]
I just pushed a change which fixes this issue under Linux, by translating the Shift-JIS character encoding used in the ROM header names to UTF-8 for screenshot file naming.
