### ISSUE TITLE
Elmo's Letter Adventure - keys are not responsive

### ISSUE THREAD

**Issue by erdosnew** [mupen64plus/mupen64plus-core#636]
hi, I was playing this game with my 4 yrs old,  it seems that in the submersible scene, all the buttons are non-responsive.  I ran mupen64 on an Android box and use a logitec gamepad for controls.

any ideas?

**Comment by quicksilver7837** [comment]
Same issue on raspberry pi. Music still plays but Ernie is stuck in a t-pose in the submarine. Buttons unresponsive.
