### ISSUE TITLE
LoS: Majoras Mask unable to move marker to items in inventory.

### ISSUE THREAD

**Issue by Ivy-Mike** [mupen64plus/mupen64plus-core#637]
After opening inventory (pressing start) you can move between the four windows with different types of items by moving analog stick left and right, and pressing R and Z. For some reason it's impossible to move the marker to the specific items that you can choose between within each window.

**Comment by HarryTheTurtle** [comment]
May be helpful to upload a save state so developers can load and test the problem quickly.

**Comment by Ivy-Mike** [comment]
I was wrong, needed to remap the buttons since analog left stick has the same input value as up,down,right,left (digital) on the switch controller.
