### ISSUE TITLE
Command Line Ends Process After Starting And Request A More Detailed Install Readme File

### ISSUE THREAD

**Issue by HarryTheTurtle** [mupen64plus/mupen64plus-core#638]
I can't get the command line to work correctly on 2.5.9 beta. It flashes the command line screen and ends the process immediately after. I can see the Mupen text on the command line but I can't do anything because it ends the process on it's own shortly after launch.

I downloaded the newest beta release (2.5.9) and I also downloaded M64py 2.4. M64py comes with an older version of Mupen64Plus it seems and the gui can run right after install. But to update the older version of M64py do I just copy and paste the files from 2.5.9 into the M64py folder and overwrite? I did that and it seems to work fine but I'm not certain if that was the correct way to do it. 

May I get some clarification on why the ui console ends itself after launch and request an few more update and install details on the readme file to eliminate any ambiguity?

**Comment by Jj0YzL5nvJ** [comment]
Are you executing from CMD or Windows Explorer?
In Windows Explorer case, then such behaviour is expected, that is what CLI applications do without parameters (run & exit). If you insist on using Windows Explorer, at very least drop a ROM on the EXE.

**Comment by HarryTheTurtle** [comment]
Ah ok I see. Thanks for the quick reply.
