### ISSUE TITLE
Retrolinc Controller not found - Arch Linux mupen64plus

### ISSUE THREAD

**Issue by zubalea** [mupen64plus/mupen64plus-core#645]
Retrolink controller is a N64 clone with USB connector.

/dev/input shows 2 joystick devices.   js0 and js1.    js0 is a paddle on my Roccat mouse.  js1 is the controller.

lsusb defines the controller as "DragonRise Inc. PC TWIN SHOCK Gamepad"
jstest /dev/input/js1 shows all buttons from controller working.

Tried using frontend m64.py.   m64 sees the controllers and lets me configure every button.

However, when mupen64plus launches it says "1 SDL joysticks were found" which is the Roccat paddle.   I removed the mouse for testing.   I got "0 SDL joysticks were found"    

This is not a config issue for the controllers, because it happens before it even has a chance to configure it.

Any ideas?

**Comment by Jj0YzL5nvJ** [comment]
```
dmesg | grep input
cat /var/log/syslog | grep input
cat /var/log/kern.log | grep input
```
Take a look at [InputAutoCfg.ini](https://github.com/mupen64plus/mupen64plus-input-sdl/blob/master/data/InputAutoCfg.ini)

**Comment by zubalea** [comment]
Issue resolved.   Sorry for having wasting your time.

Unplugged all USB devices from my PC.   Rebooted and it worked.  
Plugged my Razer Orbweaver back in.  Appears to be causing conflict for some reason.   

So solution no Orb Weaver with my N64 controller.

Thank you
