### ISSUE TITLE
Pausing causes the emulator to lock up

### ISSUE THREAD

**Issue by mountainflaw** [mupen64plus/mupen64plus-core#646]
As of late, it seems pausing the emulator causes it to lock up regardless of plugin configuration and CPU emulation setting on both of my Linux machines (running Fedora 29 and Ubuntu 18.10) on any game.

I am building from master.

**Comment by JaxonWasTaken** [comment]
I get this issue as well. I've used `git bisect` to find the commit that introduced the error. It's either 87b1946868472d739a58eca69261634970e8537a or 9aae471aa25909ec7da877337790b1a4b8a468a3. The former exits compilation with the message
```
make: *** No rule to make target '../../src/osd/osd.c', needed by '_obj/osd/osd.o'.  Stop.
make: *** Waiting for unfinished jobs....
    CXX _obj/osd/OGLFT.o
```
while the latter compiles and locks on pause.

I'm on Arch Linux with the most recent packages as of 18:06 April 16th, 2019 UTC+02.

**Comment by JaxonWasTaken** [comment]
Re-adding what the PR removed seems to fix the issue. More explicitly: adding `SDL_PumpEvents();` between lines 258 and 259 in src/main/main.c (at the end of `main_message()`).

**Comment by RhFortuna** [comment]
In the terminal I got "segmentation fault" when pausing a game.

> Core Status: Emulation paused.
> Falha de segmentação

In Mupen64Plus-Qt

> There was no output. If you were expecting Mupen64Plus to run, try copying
> the above command into a command prompt to see if you get an error.

Xubuntu 20.04.4 Kernel 5.13.0-30-generic
Mupen64plus 2.5.0 - Mupen64plus-Qt 1.14

**Comment by RhFortuna** [comment]
Thanks! This is the official repository version.
Well, I would like to say that pause worked normally before, for a long time it worked normally, and I don't know how it broke.
