### ISSUE TITLE
Opening game crashes on Mac

### ISSUE THREAD

**Issue by Pysis868** [mupen64plus/mupen64plus-core#653]
RetroArch 1.7.7 (for Mac OSX Metal2)
Mac OSX 10.13.6
Tried either:
 - Mupen64Plus
 - ParaLLEI N64

With PraLLEI the window opened without a rom loaded.  Once choosing in a dialog it crashed the same.

Seg fault kernel bad address at 0x0.

glsm_ctl function

NES/SNES games work fine.

**Comment by m4xw** [comment]
Why report a Issue here?
This is not related to mupen64plus-core
The Mupen64Plus libretro core is outdated and no longer maintained, same with parallel and Mupen64Plus-Next does not support OSX yet.
You are out of luck for now.

**Comment by richard42** [comment]
Yeah, we unfortunately get a lot of bug reports for RetroArch / libretro now, but you need to reach out to that development team.

**Comment by Pysis868** [comment]
I was trying not to post against the frontend, guess I need to try that other place.
If this project is dead, why not at least have a consolation edit atop the readme?

**Comment by richard42** [comment]
mupen64plus is not dead; the problem here is that libretro forked our code base and then haven't pulled updates from our changes over the last couple of years. So bugs with retroarch/libretro need to be reported to them.

**Comment by Narann** [comment]
mupen64plus is forked in many places (mostly frontends). What we should maybe do instead is add a note in the readme stating that you should contact front end dev team if you use RetroArch / libretro, or all other front ends, or enter a bug if you can reproduce using the official binaries.

I know github provide a way to template bug submission. Maybe those information should be exposed there.

**Comment by m4xw** [comment]
Our mupen64plus libretro core will soon be archived, don't worry.
We are still in the transition phase, mupen64plus-next will replace the old core (and its updated to latest mupen core and gliden), however we still don't support mac osx yet, since I have no means to develop for it.
