### ISSUE TITLE
[Glide64] Compilation error on char signedness

### ISSUE THREAD

**Issue by Narann** [mupen64plus/mupen64plus-core#655]
I don't want to lost this information and as Glide64 repo doesn't have the issue tab, I store it here.

It should be an easy fix.

`char` signedness is dependent [on the architecture](https://wiki.debian.org/ArchitectureSpecificsMemo). x86 is signed, arm is not, raising some compilation errors:

```
../../src/wrapper/filter.cpp: En la función ‘unsigned char* blur_edges(unsigned char*, int, int, int*, int*)’:
../../src/wrapper/filter.cpp:35:49: error: narrowing conversion of ‘-1’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
     char mx[3*3] = {-1, 0, 1, -2, 0, 2, -1, 0, 1};
```

Looks like we should simply add `signed` before `char` to explicit the sign.

Code is [here](https://github.com/mupen64plus/mupen64plus-video-glide64/blob/master/src/wrapper/filter.cpp#L35).

**Comment by Askmewho** [comment]
fixed on armhf with:

34    unsigned char *result, *temp, *temp2;
35   signed char mx[3*3] = {-1, 0, 1, -2, 0, 2, -1, 0, 1};
36   signed char my[3*3] = {-1, -2, -1, 0, 0, 0, 1, 2 ,1};
37 int i,j;

on /mupen64plus-video-glide64/src/wrapper/filter.cpp

**Comment by Narann** [comment]
Should be fixed by https://github.com/mupen64plus/mupen64plus-video-glide64/pull/18

I'm closing this one. :)
