### ISSUE TITLE
Failed to create GL context on RPI3 under mesa with GLideN64

### ISSUE THREAD

**Issue by Askmewho** [mupen64plus/mupen64plus-core#656]
I get a lot more performance on mesa 19 on RPI3 with plugins Rice (master) and Glidemk2 (master) and mupen64plus (master), but for some games these plugins are a bit buggy, so ive tried GlideN64 with no success. the dev on the reference issue on GlideN64 tell me than
the core makes the GL context and the pass to the plugin.... dont know how rice and Glidemk2
targeted to opengl (mesa) didint have the same issue!
 
mupen64plus crash output:

Core: SDL_SetVideoMode failed: Could not create GL context: GLXBadFBConfig

Ihave sdl 2.0.9 (master) with opengl

isuue reference: https://github.com/gonetz/GLideN64/issues/2060

**Comment by Jj0YzL5nvJ** [comment]
I know absolutely nothing about RPI3, but GLideN64 master is broken here, Xubuntu 16.04.6 LTS AMD64.
The issue has been previously reported to GLideN64 at least two more times... gonetz/GLideN64#2039 gonetz/GLideN64#2055
Try bisecting to https://github.com/gonetz/GLideN64/commit/3d74542d24eb9c559bbeb633781ad43fb0eb1f37 and behold.
