### ISSUE TITLE
Custom roms won't boot

### ISSUE THREAD

**Issue by Zapeth** [mupen64plus/mupen64plus-core#660]
All the roms I'm referring to can be found throughout [this forum thread](https://forums.nesdev.com/viewtopic.php?f=23&t=15988), as well as [this repository](https://github.com/conker64/libdragon/tree/master/examples) (all by the same guy)

After some debugging sessions I was able to get them to boot by removing [this](https://github.com/mupen64plus/mupen64plus-core/blob/77a2f8813251b5257382ec477c3f0ef3ea49c37f/src/device/rcp/rdp/rdp_core.c#L115) and [this](https://github.com/mupen64plus/mupen64plus-core/blob/77a2f8813251b5257382ec477c3f0ef3ea49c37f/src/device/rcp/rdp/rdp_core.c#L118) line in `rdp_core.c` (which shouldn't be there anyway as far as I can tell?), but only when running in "Pure Interpreter" mode, the other modes still don't work.

In addition to that, once they are booted they run at normal speed for a split second and then slow down to a crawl afterwards.
I'm guessing this is due to the CP0_CAUSE register pretty much constantly having the IP7 bit set (timer interrupt) and all the roms having some timer related logic (mostly fps calculation).
Though the overall implementation of interrupts in the core looks weird (and a bit messed up?) to me, so I'm not sure if this bit being constantly set isn't even intentional and it just causes problems in these particular cases.

Also all these roms run as intended in cen64 (no slowdown issues either), though most of them need to be byteswapped first.

**Comment by loganmc10** [comment]
Fixed by https://github.com/mupen64plus/mupen64plus-core/commit/0a2c4ba6b03a68e65634e929ddc31161181de8f3

**Comment by Narann** [comment]
@Zapeth can you confirm?

**Comment by Zapeth** [comment]
Only tested a few of the mentioned roms, but those worked as expected. Also the recent interrupt changes seem to have resolved the aformentioned slowdown issues in these roms, so thats neat.
