### ISSUE TITLE
VidExt_GL_SetAttribute sets SDL_GL_SetSwapInterval prematurely

### ISSUE THREAD

**Issue by dankcushions** [mupen64plus/mupen64plus-core#663]
The spec for VidExt_GL_SetAttribute says:
> This function is used to set certain OpenGL attributes which must be specified **before** creating the rendering window with VidExt_SetVideoMode

One of these attributes is `M64P_GL_SWAP_CONTROL`, which controls VSync via `SDL_GL_SetSwapInterval` See 
https://github.com/mupen64plus/mupen64plus-core/blob/master/src/api/vidext.c#L431
SetSwapInterval requires a context: https://wiki.libsdl.org/SDL_GL_SetSwapInterval - if you don't, it will error with `No OpenGL context has been made current` (you can see this error via my PR https://github.com/mupen64plus/mupen64plus-core/pull/662)

However, when launching mupen64 via command line on linux (not sure if that's relevant), it appears that GL context is only set via `VidExt_SetVideoMode` - see https://github.com/mupen64plus/mupen64plus-core/blob/77a2f8813251b5257382ec477c3f0ef3ea49c37f/src/api/vidext_sdl2_compat.h#L470

...but the API for VidExt_SetVideoMode says:
> This function creates a rendering window or switches into a fullscreen video mode. Any desired OpenGL attributes should be set **before** calling this function.

Interesting thread here: http://forums.libsdl.org/viewtopic.php?p=43308

should SwapInterval really be considered an attribute? It seems like it would be better as a parameter in SetVideoMode, however I'm sure you don't want to change the API at this stage.

@loganmc10 had a suggestion in https://github.com/gonetz/GLideN64/pull/2070:
> instead of trying to call SDL_GL_SetSwapInterval during VidExt_GL_SetAttribute, you could just set a variable to "true" and then call SDL_GL_SetSwapInterval in VidExt_SetVideoMode based on whatever the variable was set to

sound good?

**Comment by dankcushions** [comment]
I tried @loganmc10's idea - https://github.com/dankcushions/mupen64plus-core/commit/3e07fdd82d864ed22a1a665128d820948b56768e

seemed to work! I will PR after a proper test

**Comment by loganmc10** [comment]
You should probably set l_SwapControl to it's default value in the VidExt Init function as well

**Comment by dankcushions** [comment]
Done! see https://github.com/mupen64plus/mupen64plus-core/pull/670
