### ISSUE TITLE
Test ROM hangs emulator

### ISSUE THREAD

**Issue by Pixelnarium** [mupen64plus/mupen64plus-core#669]
While looking at [merging the upstream changes](https://github.com/mupen64plus/mupen64plus-rsp-cxd4/pull/45) on the cxd4 RSP plugin I tried [this test ROM](https://github.com/PeterLemon/N64/tree/master/RSPTest/CP2/VRCPL).

When running it in mupen it just hangs with 100% CPU usage and gives no screen output. It does this in pure interpreter mode too. You have to kill the process. The test ROM works in cen64.

**Comment by Zapeth** [comment]
Should be fixed with https://github.com/mupen64plus/mupen64plus-core/commit/67acb65107c73c543d751780617448a6be6f837b and https://github.com/mupen64plus/mupen64plus-core/commit/13d1ad4aa2e03297b67bca16a79a42b4c7c715d3

**Comment by Narann** [comment]
@Pixelnarium, can you confirm?

**Comment by Pixelnarium** [comment]
Yes. At least with the angrylion plugin. On GlideN64 mupen64plus just crashes for me now. But that seems to be another issue.

The test ROM reports some failing tests but that is also another issue. So I am closing this now. Thanks for the fix.

![MupenTestRom](https://user-images.githubusercontent.com/30435935/75657465-94239180-5c66-11ea-9ea4-57cd57f2542f.png)
