### ISSUE TITLE
CheckInterrupts is not implemented for Audio/Gfx/RSP plugins

### ISSUE THREAD

**Issue by Zapeth** [mupen64plus/mupen64plus-core#676]
If I understand it correctly, `CheckInterrupts` is intended as an interface for plugins to trigger interrupts in the core (and some plugins actually do use it).

However looking at the code it seems like `CheckInterrupts` is only initialized to `EmptyFunc` and never actually implemented for any plugin type, or am I completely missing something here?

**Comment by richard42** [comment]
I think this is just a deprecated part of the Zilmar plugin spec. I would guess that the core doesn't need the plugins to tell it after they have set an interrupt flag, because it will check the flag at an appropriate time.
