### ISSUE TITLE
Memory leak when playing Indiana Jones (musyx_v1/v2_task)

### ISSUE THREAD

**Issue by loganmc10** [mupen64plus/mupen64plus-core#711]
When I launch Indiana Jones, without pressing anything, just sitting on the "press start" screen, the memory usage of mupen64plus constantly goes up, bit by bit, non-stop.

I tested using Cached Interpreter + RSP-HLE + GLideN64. I believe it's probably not related to GLideN64, because I tested the game with Project64+GLideN64 and didn't see any leak.

**Comment by Narann** [comment]
Do you have the same behavior using `--gfx dummy`?

**Comment by loganmc10** [comment]
I'll try to get setup to try that in a bit.

It doesn't happen using rsp-cxd4, so when running in LLE, and it doesn't happen in PJ64. It also happens with Rogue Squadron.

I wonder maybe if it's the audio in rsp-hle? I think both games use musyx. I'll do some more digging

**Comment by loganmc10** [comment]
Yes I believe it is the musyx task in rsp-hle, commenting out the task:

https://github.com/mupen64plus/mupen64plus-rsp-hle/blob/master/src/hle.c#L286

stops the problem. I'll leave this issue open here since rsp-hle doesn't have an issue tracker

@bsmiles32

**Comment by Narann** [comment]
Thanks for investigation!

**Comment by Gillou68310** [comment]
@loganmc10 is it happening with interpreter too?
There's no dynamic allocation in rsp-hle as far as I know?

**Comment by bsmiles32** [comment]
Havan't checked lately, but I'm not aware of any dynamic memory allocation inside rsp-hle. However, in the musyx ucode I did a lot of DebugMessage which can maybe increase memory consumption. Does removing these extra logging fixes the issue ?

**Comment by loganmc10** [comment]
I know it seems strange, I looked through the code as well and didn't see anything.

I only tested with the interpreter. It seems to happen for me with any musyx game (Resident Evil 2 had the same issue).

I don't think it's the logging, most the logging looks like it only happens in verbose mode.

I'll try to run some kind of tool to find where it's happening

**Comment by loganmc10** [comment]
sorry @bsmiles32 you gave a good hint. My GUI wasn't handling debug messages properly, it was allocating some memory for each verbose message, even though they weren't being displayed.

Sorry for the false alarm
