### ISSUE TITLE
 fails to build with -fno-common or gcc-10

### ISSUE THREAD

**Issue by mazes-80** [mupen64plus/mupen64plus-core#712]
See:
[build.log](https://708054.bugs.gentoo.org/attachment.cgi?id=611408)
[gentoo bug](https://bugs.gentoo.org/708054)

Patch included as .patch.txt
[mupen64plus-core-no-common.patch.txt](https://github.com/mupen64plus/mupen64plus-core/files/4228561/mupen64plus-core-no-common.patch.txt)

**Comment by Narann** [comment]
Thanks for reporting! Anyone could review the patch and submit PR?

Looks OK to me.

**Comment by Gillou68310** [comment]
g_r4300_opcodes is not even used, @bsmiles32 I guess the opcode name table is for debugging purpose only?
Anyway I guess what is missing is a ```extern``` in front of  ```const char* g_r4300_opcodes[R4300_OPCODES_COUNT];```

```struct work_struct *work;``` is not used either, should be removed!

Building without M64P_PARALLEL is broken BTW
