### ISSUE TITLE
Incorrect Folder Name In Source Code

### ISSUE THREAD

**Issue by Yersho** [mupen64plus/mupen64plus-core#719]
When running the Solution File for Visual Studio to compile Mupen64plus on Windows, the mupen64plus-core project file fails to load. This is because the folder that contains the project file should be called "VisualStudio2017" not "msvc".
![Mupen64plus Visual Studio Incorrect Folder Name](https://user-images.githubusercontent.com/56962651/75176230-ca5e8f80-5701-11ea-9aef-03c04743ad90.png)

**Comment by Jj0YzL5nvJ** [comment]
https://github.com/mupen64plus/mupen64plus-ui-console/pull/56

**Comment by richard42** [comment]
this should be fixed now.
