### ISSUE TITLE
Build issue related to recent VFP changes

### ISSUE THREAD

**Issue by littleguy77** [mupen64plus/mupen64plus-core#72]
@gizmo98

I am having difficulty with [this line](https://github.com/mupen64plus/mupen64plus-core/blob/683127a1ae51998cfa22d8abc52fe5c827c90b40/src/r4300/new_dynarec/linkage_arm.S#L40) when I try to compile for Android.  In our [makefile](https://github.com/mupen64plus-ae/mupen64plus-ae/blob/288c29d5a05e31d2cdd7e0de021bdc490cc072fa/jni/Android.mk#L140), we set the following CFLAGS for ARM-v7a:
```
    LOCAL_CFLAGS += -mfloat-abi=softfp
    LOCAL_CFLAGS += -mfpu=vfp
```
The GCC 4.8 linker throws an error ```... new_dynarec/linkage_arm.o uses VFP register arguments, output does not```.

If I comment out the line [marked here](https://github.com/mupen64plus/mupen64plus-core/blob/683127a1ae51998cfa22d8abc52fe5c827c90b40/src/r4300/new_dynarec/linkage_arm.S#L40), everything builds again, so it seems to me that either
 - ```__VFP_FP__``` or ```__SOFTFP__``` is not being set properly in Android NDK 10d, or
 - the ```#ifdefs``` here need to be tweaked, or
 - we need to tweak something in the Android makefile

Any thoughts?

@Gillou68310, @paulscode, @xperia64 Here is the commit on my branch where you can test, if you have any ideas: https://github.com/littleguy77/mupen64plus-ae/commit/f75c70ee974adf73b76a9550e2d22cc5d975c707

**Comment by littleguy77** [comment]
The following will work if all else fails.  But it's just a band-aid and doesn't address the underlying issue.
```
#if (defined(__VFP_FP__) && !defined(__SOFTFP__) && !defined(__ANDROID__))
```

**Comment by littleguy77** [comment]
[This page](https://wiki.debian.org/ArmEabiPort) suggests that the problem is with the ```#ifdefs```.  They need to be tweaked to properly detect ```mfloat-abi=softfp```, and skip that line if so.

> Paradoxically, the -mfloat-abi=softfp does not set the __SOFTFP___ macro, since it selects real floating point instructions using the soft-float ABI at function-call interfaces.

**Comment by littleguy77** [comment]
I think this is the proper ifdef clause:
```
#if (defined(__VFP_FP__) && !defined(__SOFTFP__) && !defined(__ARM_EABI__))
```
This works for me, and was suggested [here](https://sourceware.org/ml/libffi-discuss/2009/msg00249.html).

@gizmo98 Could you please test this change to see if it still works for you?

**Comment by gizmo98** [comment]
According to this post (https://code.google.com/p/v8/issues/detail?id=2140#c5) the right ifdef clause should be:
#if (defined(__VFP_FP__) && defined(__ARM_PCS_VFP) && !defined(__SOFTFP__))

But only gcc 4.6 or higher version define __ARM_PCS_VFP.

**Comment by littleguy77** [comment]
Thanks much for looking into it.  For consistency with line 22, and to minimize diff, I used the original macros and just appended the new one:
```
#if (defined(__VFP_FP__) && !defined(__SOFTFP__) && defined(ARM_PCS_VFP))
```
This fixed the issue for me.  Would you mind testing this on your build platform?

**Comment by gizmo98** [comment]
I will test it.

**Comment by littleguy77** [comment]
Also, GCC 4.6+ is not a problem.  Android NDK uses 4.8 by default and 4.6 as an option will be removed in the next NDK release.  Thanks for the heads up though :+1:

**Comment by gizmo98** [comment]
Ok. It is working with VFP_HARD=1 (-mfloat-abi=hard -mfpu=vfp). Finally we should test with NEON=1.

**Comment by littleguy77** [comment]
We don't use that flag explicitly in Android.  When I defined NEON=1 in the makefile, everything built fine.  However, I don't know if that's even a meaningful test.

**Comment by gizmo98** [comment]
I will check NEON=1 this evening. Instead of NEON=1 you can also use -mfloat-abi=hard -mfpu=neon.

**Comment by gizmo98** [comment]
Ok. It builds with NEON=1. There is no error message.

**Comment by littleguy77** [comment]
Resolved, thanks!
