### ISSUE TITLE
Mupen64Plus Compiled With Visual Studio Solution File Has No Sound

### ISSUE THREAD

**Issue by Yersho** [mupen64plus/mupen64plus-core#720]
When I compiled Mupen64Plus using the Visual Studio Solution file located in the source code of mupen64plus-ui-console, the program failed to play any audio once ran from command line with all default settings. There was nothing done on my end as multiple trials with fresh git repository clones for each build trial and with a fresh Mupen64Plus config file being generated for each build trial had identical results. My build configurations were set to Windows 32 bit with everything being on release version (picture included).
![Mupen64Plus Build Configurations](https://user-images.githubusercontent.com/56962651/75204955-6909e100-5740-11ea-9aca-01db8c6aaeaa.png)
Considering every other thing worked fine, Core, Input, Graphics, and RSP, I believe there is something wrong with https://github.com/mupen64plus/mupen64plus-audio-sdl. I am also including a .txt file of my command line output for the program, it was always identical for every trial so I will only include one file.
[Mupen64Plus Command Line Output.txt](https://github.com/mupen64plus/mupen64plus-core/files/4247582/Mupen64Plus.Command.Line.Output.txt)

**Comment by loganmc10** [comment]
I noticed this as well, the key line in your output is here:
```
Audio Warning: Obtained audio format differs from requested.
```

I believe it because Mupen64Plus requests the SDL audio format as AUDIO_S16SYS, which is basically the "native format" of the N64, and Windows seems to want a floating point format.

In the audio plugin I wrote for https://m64p.github.io, I use AUDIO_F32 as the format, and I convert the samples to floating point samples, and that seems to work on any Windows or Linux system.

**Comment by Yersho** [comment]
Is there any way you can merge your fix into the main Mupen64Plus audio plugin or for me to change the audio format in my configuration files?

**Comment by loganmc10** [comment]
There is no way to fix it via config files.

I'll look into fixing the plugin, it supports multiple resamplers which makes it a bit more complicated, but it should be doable

**Comment by Yersho** [comment]
Alright thank you. Also just to make sure it isn't a problem with the Windows 32 dependencies provided here (https://github.com/mupen64plus/mupen64plus-win32-deps) for compiling with the Visual Studio Solution file and is just simply and issue with the plugin, correct?

**Comment by Gillou68310** [comment]
@loganmc10 I recently switched to SDL2 for vs build. It's most likely an issue with SDL.
Does it work on linux with SDL2?

**Comment by loganmc10** [comment]
For me it always worked on Linux, I think Linux works with the S16 samples. Windows seems to have a problem with the S16 samples. I can't remember if I was using SDL 1 or 2 when I last tried it

**Comment by Zapeth** [comment]
I worked around this issue by passing `NULL` to the `SDL_OpenAudio` call in `sdl_backend.c`, see the docs for an explanation -> https://wiki.libsdl.org/SDL_OpenAudio

I wasn't sure whether thats considered a fix or a hack, so I didn't open a PR for this, but if more people are experiencing/reporting this issue then I can do one now if you want.
