### ISSUE TITLE
Audio stops in Army Men Sarges Heroes

### ISSUE THREAD

**Issue by quicksilver7837** [mupen64plus/mupen64plus-core#723]
Audio drops out completely in the "Riff Mission" within a few minutes. Seems to only happen in this level, I tested leaving the game running on the main menu and several other levels and the audio didnt drop out. The "Riff Mission" can be accessed quickly by inputting the code MSTRMN from the main menu. I tested mupen64plus with gliden64 plugin, gles2rice plugin as well as libretro-mupen64plus-next. The bug occurs with all of them. I also had something similar happen in mario party 2 where after a period of time (maybe 20-30 mins?) the audio completely dropped out, but Im unsure if its a related issue. I am running mupen64plus from my raspberry pi 4.

Possibly related to this old issue report?: #174

**Comment by quicksilver7837** [comment]
Just tried using omx for audio instead of SDL and the issue still occurs

**Comment by loganmc10** [comment]
Does it happen using the cached interpreter instead of the dynarec? The other issue seems to indicate that the issue is specific to the dynarec

**Comment by quicksilver7837** [comment]
Just tested using cashed interpreter and the audio did not drop out. Sounds like its most likely the same issue as previously reported.

**Comment by quicksilver7837** [comment]
Should I close this issue since it duplicates the previous report?
