### ISSUE TITLE
Binary PIF ROM support

### ISSUE THREAD

**Issue by loganmc10** [mupen64plus/mupen64plus-core#730]
One feature I think would be cool to add to the emulator is the ability to execute the binary PIF ROM, instead of the HLE version.

This may help us find potential issues with the HLE PIF implementation.

I made a quick attempt at it here:
https://github.com/loganmc10/mupen64plus-core/tree/pifrom

This adds a new API call, M64CMD_PIF_OPEN, which allows the frontend to load pifdata.bin, very similar to the M64CMD_ROM_OPEN command.

It doesn't work right now, I tried with both interpreters, and the emulator stops at: ```Core Error: reserved opcode: BFC00014:4A4083C```. I don't really know enough about the PIF or R4300 execution in general to know what steps I might have missed.

@bsmiles32 is there something small I need to do to fix this? Or is this more work than I think?

**Comment by loganmc10** [comment]
The opcode that it appears to be failing on is "REGIMM opcode 4". I can't really find any documentation on what that is

**Comment by StenApp** [comment]
According to this http://datasheets.chipdb.org/NEC/Vr-Series/Vr43xx/U10504EJ7V0UMJ1.pdf
Opcode 4 is reserved.
Probably something is wrong with the adress?

https://sites.google.com/site/consoleprotocols/home/techinfo/lowlevel/pif12

**Comment by loganmc10** [comment]
Yes you are probably right, it's probably just a matter of the execution being messed up and executing the wrong opcode

**Comment by loganmc10** [comment]
I've gotten pretty far with https://github.com/loganmc10/mupen64plus-core/tree/pifrom, it still isn't quite there, I think there is probably some stuff to do with the CIC still
