### ISSUE TITLE
Fails to build under MSYS Windows 2004

### ISSUE THREAD

**Issue by CrankySupertoon** [mupen64plus/mupen64plus-core#760]
Makefile:55: *** OS type "MSYS_NT-10.0-19041" not supported.  Please file bug report at 'https://github.com/mupen64plus/mupen64plus-core/issues'.  Stop.

**Comment by richard42** [comment]
Do you have MinGW installed as well, or only MSYS?

Also, which versions of Windows and MSYS/MinGW are you running?

**Comment by CrankySupertoon** [comment]
I said Windows 2004 and this is fixed I needed to run it under the Mingw terminal and not msys
