### ISSUE TITLE
Dynamically switch output resolution to that of console

### ISSUE THREAD

**Issue by Slider-Whistle** [mupen64plus/mupen64plus-core#763]
A la [DOSBox](https://sourceforge.net/projects/dosbox/), [mednafen](https://mednafen.github.io/) (with [emu4crt](https://github.com/emu4crt/files) patch). Video of this kind of behaviour in demonstration here: https://youtube.com/watch?v=NjuSQzuVXg0

Games for the Nintendo 64 which change the output mid-gameplay (which there undoubtedly are) like the PlayStation and SEGA Saturn do would benefit from this by not having their output distorted at any point. Would also help users who have mistakenly set their resolution too high or low for a chosen game (I accidentally set the resolution to 320x240 in Super Mario 64 and was wondering why the text was unreadable, and the textures jiggly).

**Comment by dankcushions** [comment]
https://github.com/gonetz/GLideN64 already does this (native resolution option), which also permits it to be a factor of that resolution (1x, 2x, 3x, etc), which is useful for clean scaling of 2d elements.

i am not sure if such an option could be applied universally at the core end.

**Comment by Slider-Whistle** [comment]
If that's the case, those problems I've been experiencing must be something else. Tried increasing ScreenWidth and Height, and while the resolution still seemed to be consistent, the emulator introduced its own letterboxing which isn't a part of the console's native overscan. I suppose it still might be pleasant if the window scaled itself down to output size, at least in fullscreen mode.

># Width of output window or fullscreen width
The descriptions for ScreenWidth and Height in mupen64plus.cfg seem to imply that won't happen, in windowed or fullscreen mode.

**Comment by Narann** [comment]
It looks like a feature that need to be handled by the graphic part.

**Comment by Slider-Whistle** [comment]
@dankcushions and @Narann You guys are right about me posting in the wrong area, my apologies.
For future reference and testing purposes, games mentioned on these pages reportedly change resolution mid gameplay:
https://www.reddit.com/r/n64/comments/86snpl/which_nintendo_64_titles_change_resolution_while/
https://nintendo.fandom.com/wiki/Nintendo_64_Expansion_Pak

As for the visual bug I was experiencing earlier, I've since switched from Glide64mk2+RSP HLE to AngrylionPlus+cxd4-sse2 and it's been fixed. Don't know if I'll raise an issue for it, but it seems to have to do with a thin black overscan border on the left and right sides that Glide64mk2 failed to generate, creating distorted video.
