### ISSUE TITLE
mupen64plus-gui DK64 - Severe Slowdown

### ISSUE THREAD

**Issue by Zageron** [mupen64plus/mupen64plus-core#776]
(This also happens to Conker, and both Banjos)
So Donkey Kong 64 USA runs at 17fps / VI with default settings in the intro, start screen, and in game.
Front matter and start menu run at 60fps / VI.

CPU and GPU are running at full power.
I've tried fiddling with every setting with no effect.
Any ideas?

Microsoft Windows 10 Pro
10.0.19041 Build 19041

![image](https://user-images.githubusercontent.com/1892473/92424998-c395e800-f13a-11ea-8c29-bd69f94a4ebf.png)
![image](https://user-images.githubusercontent.com/1892473/92425012-cf81aa00-f13a-11ea-8b60-bcca4a599cfa.png)

**Comment by Jj0YzL5nvJ** [comment]
I think you are confusing [mupen64plus](https://mupen64plus.org/) with [m64p](https://m64p.github.io/).
The correct channel to report said bug is at https://github.com/loganmc10/m64p/issues

In any case, be sure to only report issues with the latest build to ensure they are still valid.

**Comment by Zageron** [comment]
Whoops, you're totally right. My bad.
