### ISSUE TITLE
Is there any way to add Gameshark Codes?

### ISSUE THREAD

**Issue by Toadfield** [mupen64plus/mupen64plus-core#777]
I didn't found a way to add gameshark codes in the gui I use,I can only use existing ones,but there aren't all gameshark codes that are available for that game.
So is there a way to add Gameshark codes?
Because in Project 64 it works,so it should in Mupen64Plus.

**Comment by richard42** [comment]
Yes, you can edit the mupencheat.txt file.  On unix systems this file resides at /usr/local/share/mupen64plus/

**Comment by Toadfield** [comment]
Where is that folder located on Linux?
I don't have that folder and I can't find mupencheat.txt

**Comment by richard42** [comment]
It depends on how you installed Mupen64Plus.  If you build it from source and install with "sudo make install" then it should be copied to /usr/local/share/mupen64plus.  If you just have a folder with all of the executables and libraries and data files in it, then it should probably be there. You can get the latest version of this file from github:

https://github.com/mupen64plus/mupen64plus-core/raw/master/data/mupencheat.txt
