### ISSUE TITLE
Every time I open mupen64plus-ui-console it crashes very quickly.

### ISSUE THREAD

**Issue by CarterLittler** [mupen64plus/mupen64plus-core#778]

**Comment by richard42** [comment]
Are you running Windows?  If so, be aware that mupen64plus-ui-console is a console application, designed to be run from a terminal window with parameters.  If you click on it from an Explorer window, it will just open a console window  and then quit very quickly.  Look at the quick start guide for information on how to run the emulator.

**Comment by CarterLittler** [comment]
Thanks.
