### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by polsvoice** [mupen64plus/mupen64plus-core#780]
Mupen64plus keeps giving me this error:

`Illegal instruction (core dumped)`

It doesn't matter what parameters I pass to it. I tried re-installing and then compiled from source and installed it. Same problem.

What's stranger was that it was working fine earlier today. Then, I started getting some graphics issues. While troubleshooting those, I ran into this mess.

Here's my hardware: https://pastebin.com/7faBMpkD

**Comment by Jj0YzL5nvJ** [comment]
Try: https://gist.github.com/Jj0YzL5nvJ/5242753837eed35768e61c240f572ecd
Angrylion-Plus examples: https://imgur.com/a/NpXxWh7

**Comment by polsvoice** [comment]
Where do I run this? In the root of mupen64plus-core?

**Comment by polsvoice** [comment]
Related to https://github.com/mupen64plus/mupen64plus-core/issues/641.

Oops. I should've posted there instead of creating a new thread.

**Comment by polsvoice** [comment]
It works! Thank you!

**Comment by Jj0YzL5nvJ** [comment]
Happy to know, you can now close the case.
