### ISSUE TITLE
Undefined behaviour in rsp-hle

### ISSUE THREAD

**Issue by loganmc10** [mupen64plus/mupen64plus-core#786]
Sorry, there isn't an issue tracker for rsp-hle.

I've been trying to resolve some undefined behavior issues in the emulator. Undefined behavior is very bad for netplay, since each client computer isn't guaranteed to execute the code in the same way. I've found a few in rsp-hle:

```
../../src/audio.c:123:40: runtime error: left shift of negative value -4096
../../src/alist.c:464:35: runtime error: left shift of negative value -12
```

I'm sure these aren't affecting netplay, since the audio output is never read back into the emulator, but I thought I would bring them up. @Gillou68310 or @bsmiles32 you know rsp-hle the best, hopefully one of you could take a look?

**Comment by orbea** [comment]
> Sorry, there isn't an issue tracker for rsp-hle.

https://github.com/mupen64plus/mupen64plus-user-issues/issues
