### ISSUE TITLE
Rat Attack Not Booting 

### ISSUE THREAD

**Issue by 40oztocumbias** [mupen64plus/mupen64plus-core#787]
I'm trying to play Rat Attack on OpenEMU for MacOS and just show a black screen

**Comment by Jj0YzL5nvJ** [comment]
[Looks good here.](https://imgur.com/a/gszV37r)

P.S: You need use `Pure Interpreter` or `Cached Interpreter` to avoid crashes...

**Comment by loganmc10** [comment]
Rat Attack was fixed somewhat recently, it's possible OpenEmu doesn't contain the latest mupen64plus code

**Comment by Jj0YzL5nvJ** [comment]
The OpenEmu core is 5 years old...

**Comment by 40oztocumbias** [comment]
> [Looks good here.](https://imgur.com/a/gszV37r)
> 
> P.S: You need use `Pure Interpreter` or `Cached Interpreter` to avoid crashes...


Are you using OpenEMU 2.2.1? Or the moped64plus?

**Comment by Jj0YzL5nvJ** [comment]
Upstream mupen64plus, `mupen64plus-ui-console` as interface.
