### ISSUE TITLE
Nuclear Escape button

### ISSUE THREAD

**Issue by renandr** [mupen64plus/mupen64plus-core#790]
Nowadays most of the software use the escape button to leave the full-screen mode. Most users are used to this functionality. It is very frustrating trying to exit full screen mode and end up nuking the game entirely.
I suggest the shortcut to stop the game to be something more specific like ctrl+esc or similar.

**Comment by Jj0YzL5nvJ** [comment]
Use `Esc` to exit is old school gamer logic (CLI / DOS) and panic button in Eroges. You can also use `Alt + F4` or `Alt + Space + C`.

If you come from PJ64, what you are looking for is `Alt + Enter`. If you don't like the CLI logic, use a [Frontend](https://emulation.gametechwiki.com/index.php/Frontends#Others) instead.

**Comment by loganmc10** [comment]
@Jj0YzL5nvJ a frontend will still honor these keyboard shortcuts, since they are acted upon by the core.

They are configurable, but the default for any frontend will still be Esc to exit the emulator

**Comment by Jj0YzL5nvJ** [comment]
WOW, in my defence I can only say that I only use CLI =P

**Comment by richard42** [comment]
That is correct, just change the keycode values for the "Kbd Mapping Stop" and "Kbd Mapping Fullscreen" configuration parameters to use different keys.
