### ISSUE TITLE
Unable to start Mupen64Plus on Slackware Linux (2.5.0)

### ISSUE THREAD

**Issue by Lodger** [mupen64plus/mupen64plus-core#797]
Hello, I just installed Mupen64Plus on Slackware Linux using [this](https://slackbuilds.org/repository/14.2/games/mupen64plus/) build script, and I am unable to start any games. I am using [this](https://www.emulatorgames.net/roms/nintendo-64/legend-of-zelda-the-majoras-mask/) ROM. [Here](https://pastebin.com/raw/6gTAxMW7) is the full output when I run `mupen64plus --verbose MajorasMask.z64`. The last line, `Core:     apply_speed_limiter(): Waiting 16ms` simply keeps printing indefinitely.

**Comment by Jj0YzL5nvJ** [comment]
https://gist.github.com/Jj0YzL5nvJ/5242753837eed35768e61c240f572ecd

Use `m64pp`...

**Comment by Lodger** [comment]
Thank you for your response, this worked! Out of curiosity though, what is different about that build script?

**Comment by Jj0YzL5nvJ** [comment]
Mmmm... that repository uses the latest "stable version" (more than 5 years old at the moment). Very possibly that code needs patches to compile correctly in current compilers and not generate additional bugs.
It's not recommended to continue using "stable versions" that have more bugs than beta/alpha versions.

I changed the title of the script to be a bit more descriptive, if you want further clarification, over here:
[Script to build standalone mupen64plus from upstream on Unix-like operating systems as "portable."](https://www.ngemu.com/threads/script-to-build-standalone-mupen64plus-from-upstream-on-unix-like-operating-systems-as-portable.207583/)
