### ISSUE TITLE
m64p_rom_header struct outdated?

### ISSUE THREAD

**Issue by Mastergatto** [mupen64plus/mupen64plus-core#800]
I have just stumbled across this document regarding the ROM header: https://n64decomp.com/basics/rom/rom_image_specification.html

Confronting it with [M64p's implementation](https://github.com/mupen64plus/mupen64plus-core/blob/master/src/api/m64p_types.h#L224), it seems there are some differences:
- For the first four bytes, we have a 32 bit integer called `BSD_DOM1_CONFIG` according to this document, meanwhile M64p uses a 8 bit integer for each byte. Also the name is a tad different: `init_PI_BSB_DOM1_*_REG`, was that a typo? (BSB or BSD)
- At 0x08 this field is called `Entrypoint` instead of `PC`, or what the hell is that on M64p.
- At 0x0C according to this document the field is called `ReturnAddress`, but for M64p it's `Release`. Who is right?
- At 0x38 it's `MediaFormat` vs `Manufacturer_ID`. What does `MediaFormat` mean? Also, in this case who's right?
- Lastly, in M64p's implementation apparently the last two bytes (0x3F and 0x40) are missing, that would respectively be an 8-bit integer (`Version`) and a char (`Bootstrap`).

Thoughts?

**Comment by Narann** [comment]
Most are just names.

First four bytes and last two bytes are note used by mupen64plus. I suspect only needed things are coded.

**Comment by bsmiles32** [comment]
short answer : m64p_rom_header is not perfect, but changing it now would break public API so I've refrained from implementing better support for header information. But if people feel like it is worth it we may change that.


longer answer :
I don't know of any official specification of the N64 ROM format.
Information below has been gathered thanks to other people work (especially zoinkity's work) and some reverse engineering of the boot procedure (because ROM format and boot procedure are tightly coupled).
Note: For simplicity I will exclude 5167 "64DD conversion ROM" which deviates in some parts from this format.


```
// 32 byte header, containing various information used during boot procedure
// Located at ROM offset 0x0000. Mandated by IPL2.
struct header {
    // Configuration of DOM1 BSD (="Bulk Storage Device")
    // 0x80000000 : BEM (Big Endian Marker) always set
    // 0x00300000 : release mask
    // 0x000f0000 : page size mask
    // 0x0000ff00 : pulse width mask
    // 0x000000ff : latency mask
    // This value is read during IPL2 and is used to configure PI DOM1 (rls, pgs, pwd, lat) for optimal access to ROM.
    // Cart ROM typically uses 0x80371240 (e.g. BEM=1, rls=0x3, pgs=0x7, pwd=0x12, lat=0x40)
    // DD ROM typically uses 0x80270740
    uint32_t pi_bsd_dom1_config;

    // Encodes clockrate override
    // 0xfffffff0 : clock mask - if zero, default to 0x03b9aca0 (= 62.5MHz)
    // Lower nibble is always set (and ignored)
    // Typical value is 0x0000000f (e.g. no clock override)
    uint32_t clockrate_override;

    // Program entrypoint, "address" (well, effective address will vary depending on CIC/IPL3 version used by the game) at which program code will be loaded and execution will start
    uint32_t entry_point;

    // Encodes OS version used by the game (just informative)
    // 0x0000ff00 : decimal version mask (d = major * 10 + minor)
    // 0x000000ff : revision (ASCII letter)
    // Typical value is 0x00001446 (e.g. 2.0F)
    uint32_t os_version;

    // CIC/IPL3 dependent checksum used to validate Program Code
    // In case of checksum mismatch, Program will not boot.
    uint32_t checksum[2];

    // ? For combo-carts encodes the expected disk code. See Product Code for more details.
    // ? I don't remember if this is standard or just some implementation details of 5167 64DD conversions.
    // Otherwise it is zero.
    uint8_t  disk_code[4];

    // Unknown/Padding ? Can be used by 5167 64DD conversion cartridges.
    uint32_t unk_1c;
};

// Registration data (only informational)
// Located at ROM offset 0x0020.
struct registration_data {
    // usually encoded using codepage 932,  padded with SPACE, not zero-terminated
    uint8_t title[20];
    // padding
    uint8_t zeros[7];
    // 4-ASCII char that (almost) uniquely identify officially released game (see Product Code for more details)
    uint8_t code[4];
    // Encodes the major/minor version (high nibble = major number - 1, low nibble = minor number)
    // 0x00 = 1.0, 0x01 = 1.1, 0x13 = 2.3, ...
    uint8_t mask_rom_version;
};

// Product Code is composed of 4 ASCII chars.
// 1st char encodes media type :
// 'C' : cartridge-part of a Cart/DD combo
// 'D' : 64DD disk
// 'E' : disk-part of a  Cart/DD combo
// 'N' : cartridge
// 'Z' : Aleck64
// 2nd and 3rd encodes "game unique ID" (for example Super Mario 64 gets 'SM')
// 4th encodes standard destination code (non exhaustive)
// 'B' : Brazil, ...'E' : North America, ... , 'P' : Europe, ...
```

Just after the header + registration data, we have at offset 0x40 the IPL3 code (4032 bytes).
And after IPL3 code at offset 0x1000,  we have Program Code (that will be loaded to RAM according to entry_point value.

Note, that strictly speaking only the bsd_dom1_config and ipl3 code are hard-requirements because it comes from IPL2 which is hardcoded into the PIF BootROM. Standard IPL3 will use the other fields such as entry_point or checksum. But custom IPL3 may not. Also there are many IPL3 variants:
- 5101 (Aleck64)
- 5167 (64DD conversion)
- 6101 
- 7102
- 6102/7101
- 6103/7103
- 6105/7105
- 6106/7106
- 8303 (64DD IPL)
which may do things slightly differently regarding checksum computation and verification, entrypoint loading, ...

**Comment by m4xw** [comment]
I actually wrote those docs based on what we have reversed (thanks for adding the mask btw smiles!)

> But custom IPL3 may not. Also there are many IPL3 variants:
> ...
> which may do things slightly differently regarding checksum computation and verification, entrypoint loading, ...

https://git.m4xw.net/n64ret/decomp-framework/-/blob/master/N64RET/Loader/N64/N64RomImpl.py#L6-12 is what we've gathered so far

As for the Version flag thats like the "game version".
Also a little side note we found reversing is that the last byte in what I spec "ReturnAddress" is the used libultra version 
https://github.com/ethteck/n64splat/blob/master/util/rominfo.py#L66
This matches what we worked with so far as well.

And at last:
> At 0x08 this field is called Entrypoint instead of PC, or what the hell is that on M64p.

It means the same in this context, Entrypoint is just the value IPL jumps to (after applying its modifcation, or not) so the initial programm counter addr on the bus

**Comment by Mastergatto** [comment]
Thanks for your replies that are very informative. They helped me understand more the header format. I can see why you're hesitating to change the API for such small, maybe not really necessary details, and I respect that.

**Comment by Narann** [comment]
I will close this issue, as I think we can consider the rationals have been exposes.
