### ISSUE TITLE
World Driving Championship doesn't boot with new dynarec

### ISSUE THREAD

**Issue by fzurita** [mupen64plus/mupen64plus-core#806]
World driving championship doesn't seem to not with the new dynarec. It booths fine with interpreter or cached interpreter.

I'm not sure if it ever worked with the new dynarec.

**Comment by Gillou68310** [comment]
@fzurita is this fixed by https://github.com/mupen64plus/mupen64plus-core/pull/871?

**Comment by fzurita** [comment]
This is fixed with #871.
