### ISSUE TITLE
Mario Kart 64 - Black Screens On Multiplayer

### ISSUE THREAD

**Issue by whoot** [mupen64plus/mupen64plus-core#81]
Hey,
thank you for this wonderful emulator!
But I have an issue with Mario Kart 64:
When playing Mario Kart 64 in multiplayer, only Player 1 is visible. All other players have a black screen.

Any suggestions?

Greetings

**Comment by ricrpi** [comment]
This may be a GLES video plugin issue so is probably not applicable to the mupen64plus-core

**Comment by conchurnavid** [comment]
Wasn't the bug in the google issue tracker enough to explain that mupen64plus doesn't have the component which has this problem: https://code.google.com/p/mupen64plus/issues/detail?id=641

**Comment by Narann** [comment]
Hi @whoot!

Happy to see you enjoying mupen64plus. :)

I'm sorry, you will not get support here.

It's quite hard to have a place where devs can have technical-only discussions.

That's why we _try_ to keep the repo for dev discussions only. :)
