### ISSUE TITLE
Unknown "no name" ROMs passes as known without even checking the MD5/CRC

### ISSUE THREAD

**Issue by Jj0YzL5nvJ** [mupen64plus/mupen64plus-core#812]
[squaresdemo.n64](https://github.com/jsdf/n64-sdk-demo)
[gameoflife.n64](https://github.com/jsdf/n64-gameoflife)
[Kumi-Daiko Beatoff 64.n64](https://github.com/ptimonen/n64-riistahillo)

Those three homebrews work, but they are not detected as unknown ROMs.

In the logs, the only thing in commune is:
```
Core: Goodname: Z64 BIOS V2.20cf
Core: Name: 
Core: CRC: 00000000 00000000
```
[Precedent...?](https://github.com/mupen64plus/mupen64plus-core/pull/687#discussion_r347391297)

**Comment by Mastergatto** [comment]
It may work if you try to remove every 'CRC: 00000000 00000000' from database. Have you tried it?

**Comment by Jj0YzL5nvJ** [comment]
If this were about of masking the issue, it would be easier to add the MD5... Is valid to define a known ROM with no name?
The current process uses three identifiers to classify a ROM as unknown, MD5, Name and CRC.

Apparently an no name ROM is an undefined code path, the unknown ROM passes as known without even checking the CRC...
```
[E0530F182EA3BB780A6264B1D06737A1]
GoodName=Z64 BIOS V2.20cf
CRC=00000000 00005053
```

**Comment by richard42** [comment]
ok I just pushed a fix for this.
