### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by gloatoriginal** [mupen64plus/mupen64plus-core#822]
This happens with m64py and executing mupen64plus directly from CLI
I'm on Ubuntu 20.04, I'v been working at this for about an hour and have tried cloning and building from the git repo, as well and trying to use the mupen64plus-gui.
![thisisgarbage](https://user-images.githubusercontent.com/47373236/104145240-1ac2f800-537b-11eb-9e0e-7538bb68f2de.png)
Hoping there is some answer out there....
```
uname -a:
Linux gloat-bedroom 5.4.0-58-generic #64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

```

**Comment by Jj0YzL5nvJ** [comment]
#797
