### ISSUE TITLE
Various input-related bugs in Paper Mario

### ISSUE THREAD

**Issue by Villager02** [mupen64plus/mupen64plus-core#823]
I started playing Paper Mario but encountered various bugs, all related to controlling or opening in-game menus, somehow.

I'm using a GUI frontend (m64p) but I don't think the issue is there because I tested the game with another one and the same problems arise. It's also not a controller issue because in Mario 64 everything works normally.

**The start button:** the start button works on the title screen, but does not open the menu during gameplay except during the tutorial where you're taught how to equip your first badge.

**The C stick:** opening your inventory using C-left does not work. Strangely, talking with Goombario using C-down does.

**Battle menus:** during battles, in the items menu and in the partner's ability menu the cursor moves down on its own without any input.

I haven't found any other issue with the same problems so I decided to post one because being able to open the menu in an RPG is kind of important.

**Comment by Jj0YzL5nvJ** [comment]
I can't reproduce your problems, none of them.

> **The C stick**

**C buttons**, if you are using an axis to simulate buttons, you have to set a reasonable amount of dead zone for them to work properly.

**Comment by Villager02** [comment]
Thanks for the tip

Regarding the rest of the problems, could it be that my frontend uses an outdated version of mupen64plus-core?
I'm asking because there's an "advanced settings" window with a single tab called "Core" and a "version" property showing "1.01"
![Screenshot (3)](https://user-images.githubusercontent.com/77363790/104513668-4995d400-55f0-11eb-8991-4f8eaff1ae1d.png)
This would be weird though because I downloaded the latest release which was literally this month: [https://github.com/loganmc10/m64p/releases](url)

**Comment by Jj0YzL5nvJ** [comment]
> Regarding the rest of the problems, could it be that my frontend uses an outdated version of mupen64plus-core?
> I'm asking because there's an "advanced settings" window with a single tab called "Core" and a "version" property showing "1.01"

```
# Mupen64Plus Core config parameter set version number.  Please don't change this version number.
Version = 1.010000
```

That's normal, the current version of mupen64plus-core in [m64p](https://github.com/loganmc10/m64p/releases) is synchronized with upstream.
m64p uses [mupen64plus-input-qt](https://github.com/m64p/mupen64plus-input-qt) instead of [mupen64plus-input-sdl](https://github.com/mupen64plus/mupen64plus-input-sdl), so if adding a deadzone doesn't help, you must report directly to m64p.

**Comment by Villager02** [comment]
I tried using the keyboard and everything works perfectly, so it probably is a problem with input-qt. At least the controller still works in Mario 64.
Should I close this issue?

**Comment by Narann** [comment]
If you consider the problem with the core closed, then yes. :)
