### ISSUE TITLE
PR #788 breaks build of mupen64plus-video-rice

### ISSUE THREAD

**Issue by charlemagnelasse** [mupen64plus/mupen64plus-core#826]
The rice plugin cannot be build anymore against the current mupen64plus-core since c9def89c0a08bd95067cab7acd5b2fa59446f525:

    In file included from ../../src/liblinux/BMGDLL.h:48:0,
                     from ../../src/TextureFilters.cpp:44:
    ../../src/liblinux/tiffrw.h:33:28: error: redeclaration of 'NONE'
     enum TiffCompressionEnum { NONE, CCITTRLE, CCITTFAX3, CCITTFAX4, LZW, JPEG6,
                                ^
    In file included from ../../../mupen64plus-core/src/api/m64p_config.h:29:0,
                     from ../../src/Video.h:30,
                     from ../../src/RenderBase.h:26,
                     from ../../src/TextureFilters.cpp:23:
    ../../../mupen64plus-core/src/api/m64p_types.h:232:4: note: previous declaration 'm64p_rom_save_type NONE'
        NONE

Please never ever add some symbol or constant definition without project specific prefix to a global public include file.

This was done by #788 Rosalie241/settings which was merged by @richard42

**Comment by charlemagnelasse** [comment]
@Rosalie241 can you please add some kind of M64P_ROM_SAVE_TYPE_  like prefix?

**Comment by Rosalie241** [comment]
sorry, I didn't mean to break things, will open a new PR later today which resolves this issue.
