### ISSUE TITLE
Input Mapping Location Question 

### ISSUE THREAD

**Issue by KMFDManic** [mupen64plus/mupen64plus-core#837]
Incredible work you guys have done with this Core! I have a simple question, relative to input mapping (N64 Cores in general)...specifically with the file and location that controls auto remapping for retroarch, settings, controls.  In playing around with some forks and RetroArchs, I've run into an oddball conflict, after compiling, where A and B are swapped on remaps and one of them is attributed to the value of Left C.  So, I ask, the location where this can be modified to fix up this pesky bug (for some forks!). Thanks in advance for any response!  I simply want to be able to swap B and A and ensure Left C has a proper controller connotation.  Thanks again:)

**Comment by Jj0YzL5nvJ** [comment]
RetroArch is a world apart and this repository has no relation to it.

[RetroArch Joypad Autoconfig is the right place to report and fix that bug. ](https://github.com/libretro/retroarch-joypad-autoconfig)

**Comment by KMFDManic** [comment]
@Jj0YzL5nvJ I thought would be the key factor to this.  Thanks:)
