### ISSUE TITLE
Dinosaur planet beta TLB exceptions in new dynarec

### ISSUE THREAD

**Issue by fzurita** [mupen64plus/mupen64plus-core#842]
The 64 bit ARM new dynarec is causing TLB exceptions in dinosaur planet.
[game crash.Dinosaur Planet (Dec 2000 Beta).zip](https://github.com/mupen64plus/mupen64plus-core/files/6028933/game.crash.Dinosaur.Planet.Dec.2000.Beta.zip)

In the attached save state, it crashes about 30 second in. With the game reporting a TLB exception and providing a backtrace.

The crash doesn't happen on cached interpreter.

**Comment by Gillou68310** [comment]
What about x86/x64/ARM32 new dynarec?

**Comment by Gillou68310** [comment]
Ok I'll test don't worry. Does it crash after 30sec with or without user input?

**Comment by fzurita** [comment]
I just tested arm32 new dynarec, it also crashes, but the game soft locks, it doesn't go into the debug screen.

The game crashes with no user input, it's in a cut scene.

**Comment by Gillou68310** [comment]
Cool it's gonna be easier to track down the issue then.
