### ISSUE TITLE
video-glide64mk2 won't start game

### ISSUE THREAD

**Issue by KXncX** [mupen64plus/mupen64plus-core#845]
When I select mupen64plus-video-glide64mk2 on both mupen64plus-qt and in the .cfg file, I get "Mupen64Plus quit unexpectedly. Check the log for more information." when trying to run mario 64.
![ok](https://user-images.githubusercontent.com/79894105/109604961-6039b100-7af2-11eb-8445-3416b997e643.png)

**Comment by Narann** [comment]
Your .so has been compiled with libboost-filesystem 1.55 but you doesn't seems to have this version on your system.

**Comment by Jj0YzL5nvJ** [comment]
[1.55.0 is really ancient...](https://www.boost.org/users/history/version_1_55_0.html) 2013-11-11
