### ISSUE TITLE
Virtual N64 controller Notches

### ISSUE THREAD

**Issue by digitaldelboy** [mupen64plus/mupen64plus-core#846]
The Dolphin emulator recently got a feature where it uses virtual notches to mimic a GC controllers octagonal gates which is great for those who are using a more modern controllers that have circular analog gates. The N64 controllers gates are totally different compared to the gc unfortunately most third party n64 controllers use GC gates and precise platformers like mario 64 and Donkey Kong 64 play imperfectly.

Would be great if this was added but I'll understand if it's not.

**Comment by richard42** [comment]
I already did this. I used a real N64 controller and modeled the exact extent of the physical joystick in all directions, and added this into the emulator. And people complained that it caused problems for some specific games so we removed it.

**Comment by digitaldelboy** [comment]
Well thanks anyway, I wonder why it didn't work if it was modeled around the joystick.
