### ISSUE TITLE
Random Game Crash/Freeze in Ocarina of Time with Dynamic Recompiler 

### ISSUE THREAD

**Issue by Clownacy** [mupen64plus/mupen64plus-core#849]
Hi, I just wanted to bring your attention to [this issue](https://github.com/libretro/mupen64plus-libretro-nx/issues/180). The dev claims it is an upstream bug, but I can't find any open or closed issues in this repo mentioning it.

**Comment by Jj0YzL5nvJ** [comment]
gonetz/GLideN64#2249

Random issues are more difficult to solve. And even more harder if the problem resides in Core / Dynarec #572
@Gillou68310 seems to be [doing something](https://github.com/Gillou68310/mupen64plus-core/commits/debug)...

**Comment by m4xw** [comment]
Yep we are on it, since over a year.
Had to improve the dynarec tooling a lot and we finally just got able to reproduce it consistently a few days ago.
![grafik](https://user-images.githubusercontent.com/13141469/112754748-bf99bc80-8fdd-11eb-8dca-2c3ccc7faa8c.png)

**Comment by m4xw** [comment]
It ends up random because is depends on r5 being written back as a 64bits regs previously

**Comment by m4xw** [comment]
We confirmed a fix, now its down to regression testing

**Comment by orbea** [comment]
@m4xw Was this issue ever resolved?

**Comment by m4xw** [comment]
> @m4xw Was this issue ever resolved?

This was part of one of the many dynarec changes at that point in time.

There should be no register promotion issue left

**Comment by Jj0YzL5nvJ** [comment]
Fixed by #871

**Comment by Clownacy** [comment]
Oh, whoops, I forgot that it was me that opened this issue.
