### ISSUE TITLE
Mupen64Plus Core Configuring gamepad buggy

### ISSUE THREAD

**Issue by shinra358** [mupen64plus/mupen64plus-core#850]
Have to choose between using the left or right stick. Can't use both. C-button settings are a nightmare and if you turn off remap buttons for this core in RA settings, the c modifying button disappears. This is what I want my n64 controller to look like in which it is currently impossible to do:

    (sony controller)
    L1 = L
    L2= Z
    R1 = R
    Start = Start
    Select = C mod button
    Dpad = Dpad movement
    LStick = Stick movement
    LStick Button = C mod button
    RStick = C buttons
    RStick Button = C up
    Square = B, C left if C mod is held
    X = A, C down if C mod is held
    Triangle = C left, C up if C mod is held
    Circle = C down, C right if C mod is held
    R2 = C Right

This is how I got it set up on standalone pj64 and standalone mupen with krossx's pokopom input plugin.

**Comment by richard42** [comment]
This doesn't have anything to do with mupen64plus core. It looks like you are using RetroArch, which is a downstream project and not supported by us.  It also looks like you are trying to configure your controller with a modal layout whereby the mapped buttons change when a modifier button is pressed.  Theoretically this kind of layout could be supported with changes to the logic in the mupen64plus-input-sdl plugin, but with the current code it is not possible.
