### ISSUE TITLE
Forcing ROM-side High VSync Mode Gets Ignored By ALL Mupen Forks

### ISSUE THREAD

**Issue by PyroJay4** [mupen64plus/mupen64plus-core#856]
Having a ROM's VI mode set to a really high number gets ignored by **any** form of Mupen, which increases emulation speed on most other emulators, (ParaLLEl-N64 core, any pj64, etc.) gets ignored completely, seemingly getting forced inaccurately to a standard, but arbitrary low value. Setting High ROM-side VSync is very useful for some dev friends of mine and I for emulator support, and all Mupen forks supporting it properly would be very useful and more accurate.

**Comment by loganmc10** [comment]
When you say more accurate, what do you mean exactly? What is the behaviour on a real N64 when you set the vsync value very high?

**Comment by PyroJay4** [comment]
Console flatlines when it's set high, but it's something that never occurs in standard games, and is generally interpreted as a CPU speed adjustment (speeding up when set high) by emulators, wherein it is a very useful feature for homebrew to have it change speed like that. Having mupen replicate exactly how console can't handle it is essentially useless and hard to translate to an emulator setting as it's never been done before, but the ability to take advantage of setting a high vsync to a rom and having it translate into faster cpu emulation is very useful to creators and end users.

**Comment by loganmc10** [comment]
> generally interpreted as a CPU speed adjustment (speeding up when set high) by emulators, wherein it is a very useful feature for homebrew to have it change speed like that. Having mupen replicate exactly how console can't handle it is essentially useless

I strongly disagree with this, I'd much rather emulate how the hardware behaves

**Comment by PyroJay4** [comment]
As much as it would be accurate to the hardware, it'd also just mess up a lot of casual users with it. Having it as a toggle that by default doesn't crash would be nice, but at some point it'd just be enabling a crash the developer knows would crash and end up just helping nobody, honestly. With difficulty of implementing the logistics of the crash in mind, there's bigger fish to fry, imo.

**Comment by loganmc10** [comment]
What you are asking for is a Projec64 emulator. Mupen64plus is an N64 emulator. I don't think we should be trying to emulate the inaccurate behavior of other emulators.

**Comment by richard42** [comment]
I agree that our priority is to accurately emulate the original console and not to implement extra non-standard core behavior, however useful it might be to certain classes of users.  We do have a related feature which is about to (if it hasn't already) been merged, which allows a form of overclocking by setting the clock ticks per instruction to be less than one.

**Comment by PyroJay4** [comment]
That does sound like a suitable alternative, I will have to check that feature out then, thanks!
