### ISSUE TITLE
Error LNK1181 cannot open input file 'Win32\Release\dyna_start.obj'

### ISSUE THREAD

**Issue by RossenX** [mupen64plus/mupen64plus-core#862]
Hey, i've been trying to compile mupen64plus and all the other parts seem to compile fine and all is well but the core for some reason is giving my a linker error dyna_start.obj missing and for the life of me i can't figure out where i'm supposed to get that from.

I downloaded all the dependencies and put them in the correct folders and all the other parts of mupen compile just fine.

Error LNK1181 cannot open input file 'Win32\Release\dyna_start.obj'

Any advice would be much appreciated.

**Comment by Jj0YzL5nvJ** [comment]
From your Developer Command Prompt:

```
cd /d "%USERPROFILE%"
md build
cd build
git clone --depth 1 https://github.com/mupen64plus/mupen64plus-win32-deps.git
git clone https://github.com/mupen64plus/mupen64plus-core.git
git clone https://github.com/mupen64plus/mupen64plus-ui-console.git
git clone https://github.com/mupen64plus/mupen64plus-audio-sdl.git
git clone https://github.com/mupen64plus/mupen64plus-input-sdl.git
git clone https://github.com/mupen64plus/mupen64plus-rsp-cxd4.git
git clone https://github.com/mupen64plus/mupen64plus-rsp-hle.git
git clone https://github.com/mupen64plus/mupen64plus-video-glide64mk2.git
git clone https://github.com/mupen64plus/mupen64plus-video-rice.git
msbuild mupen64plus-ui-console\projects\msvc\mupen64plus-ui-console.sln /p:Configuration=Release;Platform=Win32
md mupen64plus
set "DESTINY=%CD%\mupen64plus"
cd mupen64plus-ui-console\projects\msvc\Win32\Release
copy *.exe "%DESTINY%"
copy *.dll "%DESTINY%"
copy *.ini "%DESTINY%"
copy *.ttf "%DESTINY%"
copy mupencheat.txt "%DESTINY%"
explorer "%DESTINY%"
```

**Comment by RossenX** [comment]
Same issue :\ Do i need anything other than what's stated above? I am using Visual Studio 2015 also. Do i need 2017 or 2019 maybe?

![Screenshot_2](https://user-images.githubusercontent.com/11183420/120929974-f08c2100-c6f3-11eb-8e7c-9777c23f2418.png)

**Comment by Jj0YzL5nvJ** [comment]
Your error tells me absolutely nothing, but you have 15 warnings. That's abnormal.
https://ci.appveyor.com/project/Narann/mupen64plus-core/builds/39118047/job/gxiglicwxt9f3cjj#L160

> I am using Visual Studio 2015 also. Do i need 2017 or 2019 maybe?

[AppVeyor](https://ci.appveyor.com/project/Narann/mupen64plus-core/branch/master) also uses VS2015. With some tweaking and resolving some dependencies, using VS2012 or VS2013 could be a possibility.

It's possible that during the installation of VS2015 you have omitted the installation of some tools, C++ libraries or SDKs.
It's a guarantee that most emulators will not compile correctly with a Visual Studio installed with the default settings.

**Comment by RossenX** [comment]
I know that doesn't say much i'm sorry. But that's all it's giving me right now i got it down to 10 .Which are mostly like possible loss of data because of variable conversion so nothing that bad. (None of them are in the core project) Warnings which is the same as the link above. I think it might be the prebuild event "gen_asm_script.cmd"
Attached a log file just in case but it doesn't really say much. I've compiled a couple of emulators before with little issue, but i'm sure i messed something up in my setup somewhere.

I'll keep messing with it until it works and get back to you. 
If you have any tips on what might be causing it please let me know, thanks for the quick replies!

[error.txt](https://github.com/mupen64plus/mupen64plus-core/files/6605102/error.txt)

**Comment by Jj0YzL5nvJ** [comment]
Mmm... your log is missing almost half of the compilation tasks.

```
InitializeBuildStatus:
  Touching "Win32\Release\mupen64plus-core.tlog\unsuccessfulbuild".
```

```
ClCompile:
  All outputs are up-to-date.
  All outputs are up-to-date.
```

Try with:
```
taskkill /im msbuild.exe /f 2>nul
taskkill /im vctip.exe /f 2>nul
taskkill /im mspdbsrv.exe /f 2>nul
cd /d "%USERPROFILE%"
md build2
cd build2
git clone --depth 1 https://github.com/mupen64plus/mupen64plus-win32-deps.git
git clone https://github.com/mupen64plus/mupen64plus-core.git
msbuild mupen64plus-core\projects\msvc\mupen64plus-core.vcxproj /p:Configuration=Release;Platform=Win32;PlatformToolset=v140 /t:Rebuild
```

If it fails show me the full log.

**Comment by RossenX** [comment]
No luck, Here's the log.
[FullLog.txt](https://github.com/mupen64plus/mupen64plus-core/files/6605306/FullLog.txt)

**Comment by Jj0YzL5nvJ** [comment]
Try with:

```
cd /d "%USERPROFILE%"
md build3
cd build3
git clone --depth 1 https://github.com/mupen64plus/mupen64plus-win32-deps.git
git clone https://github.com/Jj0YzL5nvJ/mupen64plus-core.git
cd mupen64plus-core
git checkout get_info
msbuild projects\msvc\mupen64plus-core.vcxproj /p:Configuration=Release;Platform=Win32;PlatformToolset=v140 /t:Rebuild
msbuild projects\msvc\mupen64plus-core.vcxproj /p:Configuration=Release;Platform=x64;PlatformToolset=v140 /t:Rebuild
```

**Comment by RossenX** [comment]
Pretty much the same result i think nasm for some reason hates my system or something i even tried installing NASM from their site both 32 and 64 and whatnot, not sure what else it could be.

Would you mind sending me just the latest mupen64plus.dll that my core is failing to make? I'm mostly interested in changing the console ui for a netplay launcher anyway i don't think i'll be editing the core too much, at most i might edit the video plugin for nameplates i don't think i'll be messing with the actual core too much.

Logs:
[build3.txt](https://github.com/mupen64plus/mupen64plus-core/files/6607799/build3.txt)
[build4.txt](https://github.com/mupen64plus/mupen64plus-core/files/6607801/build4.txt)

**Comment by Jj0YzL5nvJ** [comment]
[mupen64plus-core_v2.5.9-207-gc9f49e2e_x86-Release.7z](https://ci.appveyor.com/project/Narann/mupen64plus-core/builds/39118047/job/gxiglicwxt9f3cjj/artifacts)
[mupen64plus-core_v2.5.9-207-gc9f49e2e_x64-Release.7z](https://ci.appveyor.com/project/Narann/mupen64plus-core/builds/39118047/job/14178fecl9a33xau/artifacts)

**Comment by RossenX** [comment]
Thanks for the dlls! Those seem to work just fine with what i compiled.
As for the core itself that command-line didn't recognize mklink as a command so i'm sure there's something messed up with my system. (It's very old system that probably needs to be formated but i have so many projects on it that i'm paranoid of losing any of them) I'm in the process of installing the build tools and all that on a laptop and going to try to build it on that since it's relatively new and clean build of windows. Sorry to taking up your time but much appreciated i have enough to get started on modifying the ui-console and that's what i wanted mainly.

**Comment by RossenX** [comment]
Yup it compiled just fine (well 14 warnings but it compiled) on a clean version of windows with the buildtools for 2017 and windows SDK 8.1 and nothing else was needed. I'll just compile it on that pc if i need to compile the core. Thank you for your time!
