### ISSUE TITLE
Core won't compile.

### ISSUE THREAD

**Issue by Jabir-Srj** [mupen64plus/mupen64plus-core#864]
I was compiling the core but it appears that something is missing in the git repo.
 $ make all
    CC  _obj/api/callbacks.o
    CC  _obj/api/common.o
    CC  _obj/api/config.o
    CC  _obj/api/debugger.o
    CC  _obj/api/frontend.o
    CC  _obj/api/vidext.o
    CC  _obj/backends/api/video_capture_backend.o
    CC  _obj/backends/plugins_compat/audio_plugin_compat.o
    CC  _obj/backends/plugins_compat/input_plugin_compat.o
    CC  _obj/backends/clock_ctime_plus_delta.o
    CC  _obj/backends/dummy_video_capture.o
    CC  _obj/backends/file_storage.o
    CC  _obj/device/cart/cart.o
    CC  _obj/device/cart/af_rtc.o
    CC  _obj/device/cart/cart_rom.o
    CC  _obj/device/cart/eeprom.o
    CC  _obj/device/cart/flashram.o
    CC  _obj/device/cart/sram.o
    CC  _obj/device/controllers/game_controller.o
    CC  _obj/device/controllers/paks/biopak.o
    CC  _obj/device/controllers/paks/mempak.o
    CC  _obj/device/controllers/paks/rumblepak.o
    CC  _obj/device/controllers/paks/transferpak.o
    CC  _obj/device/dd/dd_controller.o
    CC  _obj/device/dd/disk.o
    CC  _obj/device/device.o
    CC  _obj/device/gb/gb_cart.o
    CC  _obj/device/gb/mbc3_rtc.o
    CC  _obj/device/gb/m64282fp.o
    CC  _obj/device/memory/memory.o
    CC  _obj/device/pif/bootrom_hle.o
    CC  _obj/device/pif/cic.o
    CC  _obj/device/pif/n64_cic_nus_6105.o
    CC  _obj/device/pif/pif.o
    CC  _obj/device/r4300/cached_interp.o
    CC  _obj/device/r4300/cp0.o
    CC  _obj/device/r4300/cp1.o
    CC  _obj/device/r4300/idec.o
    CC  _obj/device/r4300/interrupt.o
    CC  _obj/device/r4300/pure_interp.o
    CC  _obj/device/r4300/r4300_core.o
    CC  _obj/device/r4300/tlb.o
    CC  _obj/device/rcp/ai/ai_controller.o
    CC  _obj/device/rcp/mi/mi_controller.o
    CC  _obj/device/rcp/pi/pi_controller.o
    CC  _obj/device/rcp/rdp/fb.o
    CC  _obj/device/rcp/rdp/rdp_core.o
    CC  _obj/device/rcp/ri/ri_controller.o
    CC  _obj/device/rcp/rsp/rsp_core.o
    CC  _obj/device/rcp/si/si_controller.o
    CC  _obj/device/rcp/vi/vi_controller.o
    CC  _obj/device/rdram/rdram.o
    CC  _obj/main/main.o
    CC  _obj/main/util.o
    CC  _obj/main/cheat.o
    CC  _obj/main/eventloop.o
    CC  _obj/main/rom.o
    CC  _obj/main/savestates.o
    CC  _obj/main/screenshot.o
    CC  _obj/main/sdl_key_converter.o
    CC  _obj/main/workqueue.o
    CC  _obj/plugin/plugin.o
    CC  _obj/plugin/dummy_video.o
    CC  _obj/plugin/dummy_audio.o
    CC  _obj/plugin/dummy_input.o
    CC  _obj/plugin/dummy_rsp.o
    CC  _obj/osal/dynamiclib_unix.o
    CC  _obj/osal/files_unix.o
    CC  _obj/osd/osd.o
    CC  _obj/device/r4300/recomp.o
    CC  _obj/device/r4300/x86_64/assemble.o
    CC  _obj/device/r4300/x86_64/dynarec.o
    CC  _obj/device/r4300/x86_64/regcache.o
    CC  _obj/subprojects/md5/md5.o
    CC  _obj/asm_defines/asm_defines.o
    CXX _obj/osd/oglft_c.o
    CXX _obj/subprojects/oglft/OGLFT.o
bash ../../src/../tools/gen_asm_script.sh "../../src/asm_defines" "_obj/asm_defines/asm_defines.o"
    AS  _obj/device/r4300/x86_64/dyna_start.o
/bin/sh: line 1: nasm: command not found
make: *** [Makefile:789: _obj/device/r4300/x86_64/dyna_start.o] Error 127

**Comment by Narann** [comment]
```text
/bin/sh: line 1: nasm: command not found
```
`nasm` doesn't seems to be installed on your system.

**Comment by Jabir-Srj** [comment]
Thanks, it worked!
