### ISSUE TITLE
Smash Remix 0.9.7 locked at 30fps on Retroarch Mupen64Plus-Next core

### ISSUE THREAD

**Issue by Greatscoot** [mupen64plus/mupen64plus-core#870]
Game is locked at displaying 30fps. This doesn't seem to happen in vanilla Super Smash Bros. The game plays at 60fps on ParaLLEl. Just not on Mupen64 core. https://youtu.be/5qOCa1hAyM8 

Here's a comparison video.

**Comment by loganmc10** [comment]
The Retroarch core has its own issue tracker: https://github.com/libretro/mupen64plus-libretro-nx/issues you should file this there.

If you'd like to test it on upstream mupen64plus (this repo) you can download: https://github.com/loganmc10/m64p/releases

**Comment by Greatscoot** [comment]
Thanks, I'll upload a ticket there. Sorry about that! For the record, I did just try it on the latest release you linked. It does play at 60fps without issue! 
![mupen64plus-gui](https://user-images.githubusercontent.com/85816742/121796055-03f32c80-cbcb-11eb-80d0-c1570db6e254.png)
