### ISSUE TITLE
[Feature Request] Overclocking support

### ISSUE THREAD

**Issue by SlushThorsten** [mupen64plus/mupen64plus-core#875]
I want to overlock the N64,cause many games have lags with the normal N64.

**Comment by jpike88** [comment]
@richard42 I recall on older mupen64, there was an overclocking option (mupen64-virefresh). Is it tricky to implement on this newer version?

**Comment by jpike88** [comment]
looks like VIRefresh was added for certain games, so maybe its as simple as just adding a global override option

https://github.com/mupen64plus/mupen64plus-core/pull/204/files

**Comment by Jj0YzL5nvJ** [comment]
#789
