### ISSUE TITLE
Road rush 64 black screen on new game with new dynarec

### ISSUE THREAD

**Issue by fzurita** [mupen64plus/mupen64plus-core#886]
@Gillou68310 It looks Road Rush 64 got broken by recent new dynarec changes. It works fine in interpreter. 

Starting a new game causes a black screen after entering a name.

**Comment by thekovic** [comment]
Same issue as Indiana Jones, it seems https://github.com/loganmc10/m64p/issues/202

**Comment by Gillou68310** [comment]
@fzurita can you confirm that https://github.com/mupen64plus/mupen64plus-core/pull/887 fixes both road rush and indiana?

**Comment by fzurita** [comment]
Road Rush 64 is fixed. @thekovic Can you test Indiana jones with this?

**Comment by thekovic** [comment]
I tested Indiana Jones and I can confirm the issue is fixed
