### ISSUE TITLE
MINGW32 -> x86 compilation

### ISSUE THREAD

**Issue by SpiceyWolf** [mupen64plus/mupen64plus-core#888]
Hi. If using a tool like msys2 with mingw32(on a 64bit host) to compile, with the provided tech I could not get a binary to compile.
I added this:

`ifeq ("$(patsubst MINGW32%,MINGW32,$(UNAME))","MINGW32")`
`  HOST_CPU = X86`
`  CPU := X86`
`  ARCH_DETECTED := 32BITS`
`  PIC ?= 0`
`endif`

to the unix/makefile under the 

`# detect system architecture`
`HOST_CPU ?= $(shell uname -m)`
`CPU := NONE`

and it successfully produces the binary. I was trying to attempt pulling just that update from my fork for a pull request but I dunno how to ... do that properly so Im submitting this here if anyone is willing to put this into the project for others to benefit from.

Note: this would otherwise not be important to have in normal circumstances, but I have a modding emulator powered by mupen and keeping up to date with any changes in the number of available plugins really sucks, so Ive been attempting to use github actions to automate a rebuild of everything to make distributions for all the platforms so mingw/msys2 are my goto option here.

Id also be happy to share that work if anyone is interested once I'm done working out the remaining kinks :D

**Comment by Jj0YzL5nvJ** [comment]
```
if ${{runner.os == 'windows'}}; then
  rm ../src/plugin/zilmar/config.rc
  sed -i s/\377\376//g ../src/plugin/zilmar/resource.h
fi
```
https://github.com/ata4/angrylion-rdp-plus/blob/master/CMakeLists.txt#L122-L123

**Comment by SpiceyWolf** [comment]
lol i dont understand the end bit xD seems to be from my attempt at automating the compile against angrylion for windows.. i kinda got that figured out how to fix now too, the file itself from resource.h is borked, but even if i replace the file with one that isnt borked the config.rc gets used as a backup to re-bork. removing both of them and remaking the resource file fixes it.

**Comment by Jj0YzL5nvJ** [comment]
```
enable_language(RC)
file(GLOB SOURCES_PLUGIN_ZILMAR "${PATH_PLUGIN_ZILMAR}/*.c" "${PATH_PLUGIN_ZILMAR}/*.rc")
```
FOR
```
file(GLOB SOURCES_PLUGIN_ZILMAR "${PATH_PLUGIN_ZILMAR}/*.c")
```
OR
```
if(WIN32)
...
endif(WIN32)
```
FOR
```
if(MSVC)
...
endif(MSVC)
```

**Comment by SpiceyWolf** [comment]
Got my problems fixed, and ty i got that pullrequest sent in for core :D
