### ISSUE TITLE
unzip.h not found

### ISSUE THREAD

**Issue by thesourcehim** [mupen64plus/mupen64plus-core#894]
Can not cot compile commit a605261, ../../src/main/savestates.c:34:10: fatal error: unzip.h: No such file or directory.
File present in ./subprojects/minizip

**Comment by thesourcehim** [comment]
Workaround: replace
#include <unzip.h>
#include <zip.h>
with
#include "../subprojects/minizip/unzip.h"
#include "../subprojects/minizip/zip.h"

**Comment by loganmc10** [comment]
You just need to install the minizip development files, the name would depend on your Linux distro

**Comment by thesourcehim** [comment]
I have it installed, header files are in /usr/include/minizip, not in /usr/include, but pkg-config --cflags minizip returns nothing. I guess it's fedora packaging bug. Can I add include dir for the build somehow?

**Comment by Jj0YzL5nvJ** [comment]
First, execute `ldconfig` with root privileges, and try to build again. If the problem persist, then search for `libminizip.so` directory location:
```
make CFLAGS="-I/usr/include/minizip" LDFLAGS="-L/usr/lib/your_libminizip_directory_location"
```

[See this for reference.](https://unix.stackexchange.com/questions/149359/what-is-the-correct-syntax-to-add-cflags-and-ldflags-to-configure/149361#149361)

P.S: This is my `minizip.pc`...

`$ cat /usr/lib/x86_64-linux-gnu/pkgconfig/minizip.pc`
```
prefix=/usr
exec_prefix=${prefix}
libdir=${prefix}/lib/x86_64-linux-gnu
includedir=${prefix}/include/minizip

Name: minizip
Description: Minizip zip file manipulation library
Requires:
Version: 1.2.8
Libs: -L${libdir} -lminizip
Libs.private: -lz
Cflags: -I${includedir}
```

**Comment by thesourcehim** [comment]
Mine listed includedir=/usr/include which totally explains my problem.

**Comment by leodexe** [comment]
Alternatively, you may want to temporarily edit the /usr/lib/pkgconfig/minizip.pc file and replace this line:

`Cflags: -I${includedir}`

With this new line:

`Cflags: -I${includedir}/minizip`

Then revert the changes after you are done.

If you are on Arch or any other Arch-based distro and you are trying to build this package from AUR but gives the same error as OP, try replacing the build() function in PKGBUILD with this one:

```
build() {
    local _component
    for _component in $_m64p_components
    do
        printf '%s\n' "  -> Building component '${_component}'..."

        make -C "mupen64plus-${_component}/projects/unix" clean

        # Fix minizip include path for Arch (unzip.h / zip.h live in /minizip subdir)
        # This overrides the Makefile’s pkg-config logic cleanly.
        make -C "mupen64plus-${_component}/projects/unix" \
            PREFIX='/usr' NETPLAY='1' \
            MINIZIP_CFLAGS="-I/usr/include/minizip" \
            MINIZIP_LDLIBS="$(pkgconf --libs minizip)" \
            all
    done
}
```
Either method worked for me in Arch Linux
