### ISSUE TITLE
South Park - Chef's Luv Shack	 Not working 

### ISSUE THREAD

**Issue by christopher3242** [mupen64plus/mupen64plus-core#915]
can fix please!

**Comment by Jj0YzL5nvJ** [comment]
[Don't fix what isn't broken.](https://imgur.com/a/7uSvzno)

**Comment by Narann** [comment]
We need more info on the mupen64plus version you use.

@Jj0YzL5nvJ, you are confirming its working?

**Comment by christopher3242** [comment]
i can't move control .

**Comment by Jj0YzL5nvJ** [comment]
> @Jj0YzL5nvJ, you are confirming its working?

Yes... ¬¬

This game uses the D-Pad, not the Stick.

**Comment by Narann** [comment]
Thanks.

Closing. I will reopen it if we get more information about the problem.

**Comment by christopher3242** [comment]
HEY!
