### ISSUE TITLE
Bottom of the 9th - some images are Blue tinted

### ISSUE THREAD

**Issue by Meerkov** [mupen64plus/mupen64plus-core#928]
This only seems to affect Mupen64plus, not other mupen based emulators (or else, maybe it's a recent regression).

1. start Bottom of the 9th
2. The title cards are blue (they should be white backgrounds)
3. This also affects player portraits in game (they are missing the red and green channels for some reason).

**Comment by Meerkov** [comment]
I'm using m64p using default settings.

However, Bizhawk 2.7 which also uses mupen64plus doesn't have this issue.

**Comment by loganmc10** [comment]
This is probably an issue with the graphics plugin (parallel-rdp), I've opened an issue here: https://github.com/Themaister/parallel-rdp/issues/37

**Comment by Meerkov** [comment]
Thanks, sorry for filing in the wrong place :)
