### ISSUE TITLE
Fix FBInfo implementation (for Jet Force Gemini)

### ISSUE THREAD

**Issue by avengah** [mupen64plus/mupen64plus-core#931]
The FBInfo implementation is broken and causes problems in Jet Force Gemini with the GLideN64 plugin. Apparently it needs fixing in Mupen64Plus itself, not the plugin. It works in original Mupen64 but broke in Plus. More info here:

https://github.com/gonetz/GLideN64/issues/2653

**Comment by loganmc10** [comment]
Did you try it with the Cached Interpreter? I think it might just be broken with the dynarec

**Comment by Jj0YzL5nvJ** [comment]
[mupen64plus/mupen64plus-core/issues/773#issuecomment-682141910](https://github.com/mupen64plus/mupen64plus-core/issues/773#issuecomment-682141910)

**Comment by avengah** [comment]
It works with the Cached Interpreter but the game runs slower. I am able to set the game to use the Cached Interpreter using Rosalie's GUI, but m64p doesn't seem to have a setting for Cached Interpreter, unless I just can't find it. Is it going to be fixed in the Dynamic Recompiler?
