### ISSUE TITLE
Buck Bumble hangs on the ending cutscene of Mission 3

### ISSUE THREAD

**Issue by thekovic** [mupen64plus/mupen64plus-core#933]
I'm playing Buck Bumble and after I finish Mission 3, the ending cutscene is stuck in an endless loop, never progressing to the score screen and then the next mission.

OS: Windows 10
CPU Intel i5-8300
Frontend used: m64p by @loganmc10 
Dynamic recompiler used.

![image](https://user-images.githubusercontent.com/72971433/154985793-0bda4452-079a-4264-a9a8-390bdad56031.png)

**Comment by loganmc10** [comment]
It doesn't get stuck for me, it goes to Mission Complete, then lets me start Mission 4.

Do you have any custom CountPerOp/overclock settings?

**Comment by thekovic** [comment]
Well, deleting the emulator folder as well as all configs in AppData and then downloading a completely fresh install has fixed the issue. I still have no idea what setting might have gotten wrong, especially since I reset the config to default settings several times. Maybe there's a bug connected with that in the GUI somewhere. Anyway, I am closing this issue, I thought this might have been a core issue but it doesn't seem like it anymore.
