### ISSUE TITLE
Diddy Kong Racing freezes at 2nd Wizpig race cut scene

### ISSUE THREAD

**Issue by jwillson** [mupen64plus/mupen64plus-core#945]
I'm using version 2.59 as a core within OpenEmu. This issue has existed for a few years now, across at least the last three releases of macOS (Intel).

**Comment by Jj0YzL5nvJ** [comment]
That's a problem with the core in OpenEmu, it's not reproducible in standalone.

https://imgur.com/a/Tm4PJ5E
mupen64plus/mupen64plus-user-issues#708

**Comment by jwillson** [comment]
Roger that, I'll file an issue with OpenEmu/Mupen64Plus-Core and reference this issue.
