### ISSUE TITLE
Per-Rom configuration C# interop broken

### ISSUE THREAD

**Issue by Aurumaker72** [mupen64plus/mupen64plus-core#948]
Invoking per-rom configuration from C# results in a memory corruption.

`Example A`
```
int sizeSettings = Marshal.SizeOf(typeof(m64p_rom_settings));
result = m64pCoreDoCommandROMSettings(m64p_command.M64CMD_ROM_GET_SETTINGS, _rom_settings, ref sizeSettings);
```
I assume removing this line impacts game-specific setup of plugins and may result in an unplayable experience.

**Comment by Jj0YzL5nvJ** [comment]
"_Getting_" and "_applying_" configurations are two completely different things... I only use the UI Console, don't pay much attention to me.

https://github.com/mupen64plus/mupen64plus-ui-python/blob/0a08a32481f3de8bb91d5f3e2c653ed9114e5347/src/m64py/core/defs.py#L189
https://github.com/mupen64plus/mupen64plus-ui-python/blob/0a08a32481f3de8bb91d5f3e2c653ed9114e5347/src/m64py/core/core.py#L478
https://github.com/m64p/mupen64plus-gui/blob/f984b462382536fd8ed61fe4ed26533e902a7f67/workerthread.cpp#L57
https://github.com/Rosalie241/RMG/blob/93c7ef1de8f1985b667ea2dbf4d1f09f001dd456/Source/RMG-Core/RomHeader.cpp#L26
https://github.com/Rosalie241/RMG/blob/66133975ad8c6faee45790612a4c1a6e6c934658/Source/RMG-Core/RomSettings.cpp#L29
https://github.com/Rosalie241/RMG/blob/66133975ad8c6faee45790612a4c1a6e6c934658/Source/RMG-Core/RomSettings.cpp#L97

**Comment by Aurumaker72** [comment]
I'm not applying the configuration, just fetching it. Sorry for the misunderstood wording.
 
The issue here lies in the unidentifiable reason of memory corruption after the config fetch call; I have confirmed I have correctly connected and redefined all types and functions on C# side.

**Comment by bsmiles32** [comment]
Try with ref on _rom_settings parameter, not sizeSettings:


```
int sizeSettings = Marshal.SizeOf(typeof(m64p_rom_settings));
result = m64pCoreDoCommandROMSettings(m64p_command.M64CMD_ROM_GET_SETTINGS, ref _rom_settings, sizeSettings);
```

**Comment by Aurumaker72** [comment]
Indeed, you are right. My C#-side definition was wrong
