### ISSUE TITLE
Unable to build from source on Windows

### ISSUE THREAD

**Issue by Meerkov** [mupen64plus/mupen64plus-core#955]
1) Download source
2) Open mupen64plus-core.vcxproj
3) Try to build

Result:
Custom build for ../../src/device/r4300/new_dynarec/x86/linkage_x86.asm' exited with code 3.

Lookin for advice on how to build from source (with updated instructions for non-linux users) before I can attempt to contribute to this project.

**Comment by Jj0YzL5nvJ** [comment]
All projects have one to two CI/CD, [AppVeyor](https://github.com/mupen64plus/mupen64plus-core/blob/master/appveyor.yml) and [GitHub Actions](https://github.com/mupen64plus/mupen64plus-core/blob/master/.github/workflows/build.yml), if you understand batch the process is much simpler to understand by taking a look at YAML.

Cloning [mupen64plus-win32-deps](https://github.com/mupen64plus/mupen64plus-win32-deps) and [mupen64plus-core](https://github.com/mupen64plus/mupen64plus-core) is a prerequisite for building any other project for MSVC.

[This code was more direct](https://github.com/mupen64plus/mupen64plus-ui-console/commit/0a15c7dda5c25653ca66812e65d9d227b5f56252), but was rejected =P
Either way, you can always use [nightly builds](https://github.com/mupen64plus/mupen64plus-core/releases/tag/nightly-build).

**Comment by Meerkov** [comment]
Nightly build isn't good enough for development purposes.

I've clones both of those projects, and now I see:
`\mupen64plus-core\src\device\r4300\new_dynarec\recomp_dbg.c(142,10): fatal error C1083: Cannot open include file: 'capstone.h': No such file or directory`

**Comment by Jj0YzL5nvJ** [comment]
The only code paths supported in MSVC are:
```
Configuration:
  - New_Dynarec_Debug
  - New_Dynarec_Release
  - Debug
  - Release
Platform:
  - Win32
  - x64
```

**Comment by richard42** [comment]
Right, from the error message given it appears that you are trying to make an ARM64 build, and as a result it's getting stuck on that missing header.
If you don't mind adding ARM64 project support for Windows, I'm sure there are a few other people out there who would appreciate the effort.
