### ISSUE TITLE
Add CMake project

### ISSUE THREAD

**Issue by jgcodes2020** [mupen64plus/mupen64plus-core#956]
This would greatly reduce the amount of build scripting that needs to be maintained.

**Comment by orbea** [comment]
Cmake would be a downgrade to the current makefiles, its a significantly heavier dependency and more complicated to do correctly.

**Comment by richard42** [comment]
Yeah I'm not a big fan of cmake.  The nice thing about it is that you can have a single configuration file which handles (from a high level) the project build on both Windows and Linux.  But the downside is that it adds an extra step to the compilation, and extra dependency to the build system, and is not really "native" to either platform.
