### ISSUE TITLE
Document Vidext_GL_GetDefaultFramebuffer

### ISSUE THREAD

**Issue by jgcodes2020** [mupen64plus/mupen64plus-core#966]
The current API documentation does not mention this function at all. Such a function is actually incredibly useful for integration with libraries like GTK.

**Comment by Jj0YzL5nvJ** [comment]
Then we're not looking at exactly the same "current" API documentation...
[Mupen64Plus-v2.0-API-Versioning](https://github.com/mupen64plus/mupen64plus-core/blob/master/doc/emuwiki-api-doc/Mupen64Plus-v2.0-API-Versioning.mediawiki)
[Mupen64Plus-v2.0-Core-Video-Extension](https://github.com/mupen64plus/mupen64plus-core/blob/master/doc/emuwiki-api-doc/Mupen64Plus-v2.0-Core-Video-Extension.mediawiki)

**Comment by richard42** [comment]
Do I need to update the wiki?
[https://mupen64plus.org/wiki](https://mupen64plus.org/wiki)

**Comment by Jj0YzL5nvJ** [comment]
Maybe...

**Comment by richard42** [comment]
OK I have updated these 2 pages
