### ISSUE TITLE
Crash with Core Error: SDL_SetVideoMode failed and multiple Core Warnings

### ISSUE THREAD

**Issue by polsvoice** [mupen64plus/mupen64plus-core#969]
I get a crash with this error whenever I try to open a ROM:

```
Video: Initializing OpenGL Device Context.
Core: Setting 32-bit video mode: 640x480
Core Error: SDL_SetVideoMode failed: Parameter 'pitch' is invalid
Video Error: Failed to set 32-bit video mode: 640x480
Core Status: Rom closed.
```
Above that is

```
Core Warning: ROM Database: Unknown property on line 20
Core Warning: ROM Database: Unknown property on line 29
Core Warning: ROM Database: Unknown property on line 38
Core Warning: ROM Database: Unknown property on line 212
Core Warning: ROM Database: Unknown property on line 227
Core Warning: ROM Database: Unknown property on line 252
Core Warning: ROM Database: Unknown property on line 275
Core Warning: ROM Database: Unknown property on line 330
Core Warning: ROM Database: Unknown property on line 454
Core Warning: ROM Database: Unknown property on line 477
Core Warning: ROM Database: Unknown property on line 505
Core Warning: ROM Database: Unknown property on line 553
```
and it goes on like that for dozens and dozens of lines.

I get this error on every ROM, regardless of the format. I also compiled and built from source and got the same problem.

Here are my system specs:

**CPU + GPU:** AMD Ryzen 5 5600G with Radeon Graphics

**OS:** Garuda Linux (Arch-based)

**RAM:** 16 GiB

**Mupen64Plus Version:** 2.5.0

**Comment by Narann** [comment]
Hello, can you share your `mupen64plus.cfg` file?

**Comment by polsvoice** [comment]
[Here it is.](https://gist.github.com/polsvoice/742ca157894fe3e03832e43459dd9659)

**Comment by VarNepvius** [comment]
I get the same error, resulting in a program crash.

My system specs for completeness:
**CPU + GPU:** AMD Ryzen 5 PRO 4650U with Radeon Graphics
**OS:** Arch Linux
**RAM:** 32GB
**Mupen64Plus Version:** 2.5.0

**Comment by VarNepvius** [comment]
In my case, i'm pretty sure, that the problem is related to the SDL 2.0 compatibility code, since `SDL_SetVideoMode` does itself not have a parameter called `pitch`.

@polsvoice Since your Distro is based on Arch, i assume your Mupen64plus installation runs on SDL 2.0 too?

**Comment by VarNepvius** [comment]
I have created #970, that fixes the problem for me.

**Comment by polsvoice** [comment]
@VarNepvius Yes, that's correct. It runs on SDL2.

**Comment by VarNepvius** [comment]
My Pull Request has been merged to `master` and i have just tried a installation from that (by way of `mupen64plus-git` in the [AUR](https://aur.archlinux.org/packages/mupen64plus-git)). The crash is indeed gone.

@polsvoice Can you try if it works for you too?

**Comment by polsvoice** [comment]
@VarNepvius It works! Thank you!

**Comment by Narann** [comment]
Thanks @VarNepvius.
