### ISSUE TITLE
Crash from Core Error: SDL_SetVIdeoMode failure due to invalid 'pitch'

### ISSUE THREAD

**Issue by ninjacatz** [mupen64plus/mupen64plus-core#971]
Installed mupen64plus on macOS 12.5.1 64bit Intel using Homebrew. Did not change anything after install. Get this error when simply loading a rom:

Config file: [https://github.com/ninjacatz/mupen_config/blob/main/mupen64plus.cfg](url)

```Video: Initializing OpenGL Device Context.
Core: Setting 32-bit video mode: 640x480
Core Error: SDL_SetVideoMode failed: Parameter 'pitch' is invalid
Video Error: Failed to set 32-bit video mode: 640x480
Core Status: Rom closed.

**Comment by Jj0YzL5nvJ** [comment]
See: #969

[It's they who have to fix their recipe](https://github.com/Homebrew/formulae.brew.sh/blob/1cfcb8d65ec784231d3de9f62122e509d08d1672/_data/formula/mupen64plus.json#L22)

**Comment by VarNepvius** [comment]
Given, that this issue is a duplicate and already fixed, i guess it can be closed?
