### ISSUE TITLE
Audio crackling problem with ParaLLEl-RDP

### ISSUE THREAD

**Issue by lucasmr** [mupen64plus/mupen64plus-core#972]
RetroArch 1.10.3 (Linux)
GPU Intel(R) HD Graphics 620 (KBL GT2)
Core Mupen64Plus-Next (2.4-Vulkan c10546e), with the options:

Drivers
GPU: vulkan
Audio Driver: pulseaudio

Core Options
RDP Plugin: ParaLLEl-RDP
CPU Core: Dynarec
RSP Plugin: ParaLLEl

The CPU and GPU usage are never going above 70% according to intel-gpu-top and htop, using the performance governor and maximum gpu frequency. However, there's constant audio crackling and skipping. Changing the audio latency to 512ms doesn't fix the issue. Tested under X and KMS with the same results.

Maybe it's a sync issue? Using GLideN64 as the RDP Plugin immediately fixes the problem, even with 1ms audio latency. Game tested was "Quake II (USA)" with the expansion pak enabled.

**Comment by loganmc10** [comment]
Wrong repo, should be reported here: https://github.com/libretro/mupen64plus-libretro-nx/issues

**Comment by lucasmr** [comment]
Alright, thanks.
