### ISSUE TITLE
With `AutoStateSlotIncrement = True` `CurrentStateSlot` is not updated

### ISSUE THREAD

**Issue by rafaelbeirigo** [mupen64plus/mupen64plus-core#978]
Steps to reproduce:

1. Set the following options in `mupen64plus.cfg`:
    AutoStateSlotIncrement = True
    CurrentStateSlot = 0
2. Open a game
3. Save the state (`F5`) twice; the emulator uses the slots 0 and 1; current slot is 2
4. Close the game
5. Check `mupen64plus.cfg` to see that `CurrentStateSlot` was not updated:
    CurrentStateSlot = 0

**Comment by richard42** [comment]
This is not a problem with the mupen64plus core. Each time the slot is updated, via any of the methods of updating the savestate slot number, the current value is stored in the emulator's internal configuration map. I believe the reason why you are observing the behavior you outlined is that the front-end application which you are using does not save the configuration data back to disk after closing the game.  Which front-end are you using?

**Comment by rafaelbeirigo** [comment]
Oh, sorry for the inconvenience, I didn't know that.

The frontend I'm using is the one I get running `apt install mupen64plus-ui-console` on `Debian GNU/Linux 10 (buster)`:

    rafa@bach:~$ mupen64plus --version
     __  __                         __   _  _   ____  _             
    |  \/  |_   _ _ __   ___ _ __  / /_ | || | |  _ \| |_   _ ___ 
    | |\/| | | | | '_ \ / _ \ '_ \| '_ \| || |_| |_) | | | | / __|  
    | |  | | |_| | |_) |  __/ | | | (_) |__   _|  __/| | |_| \__ \  
    |_|  |_|\__,_| .__/ \___|_| |_|\___/   |_| |_|   |_|\__,_|___/  
                 |_|         http://code.google.com/p/mupen64plus/  
    Mupen64Plus Console User-Interface Version 2.5.0

    UI-Console: attached to core library 'Mupen64Plus Core' version 2.5.0
    UI-Console:             Includes support for Dynamic Recompiler.
    UI-Console:             Includes support for MIPS r4300 Debugger.
    UI-Console Error: couldn't open ROM file '--version' for reading.
    rafa@bach:~$

**Comment by richard42** [comment]
Okay that is the front-end application that we maintain. From looking at the code, I think it ought to be saving all of the config file parameters after shutting down the game.  Are you by any chance giving it the "--nosaveoptions" command-line parameter?

**Comment by rafaelbeirigo** [comment]
> Are you by any chance giving it the "--nosaveoptions" command-line parameter?

No. I'm running `$ mupen64plus rom.z64` with no options whatsoever.

> From looking at the code, I think it ought to be saving all of the config file parameters after shutting down the game. 

I did a test, and
1. If I *manually* select the State Slot, it saves OK. Meaning, I press the digit to select it. For instance, when I open the emulator, the save slot is 0. If I press `5` it changes the slot to 5, and if I immediatelly close the emulator, and open it again, the save slot is still 5---it was properly saved;
2. If I use the auto-increment functionality, it does not save OK. For instance, when I open the emulator, the save slot is 0. If I press `F5` it saves the state, and changes the slot to 1. But if I immediatelly close the emulator, and open it again, the save slot is still 0---it didn't save the result of the auto-increment.

**Comment by richard42** [comment]
thanks for the testing; this led me to the exact source of the problem. I just pushed a fix in the core for this.
